### ISSUE TITLE
Bootleg versions

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/APSIMClassic#1757]
Minutes from RP meeting:
Discussion around bootleg models (models that haven’t gone through the Reference Panel) and whether they should be made available.
It was noted that this had been discussed at length a number of years ago - 3+. At the time, a decision was made not to include them in the standard release of APSIM. Instead a special bootleg version of APSIM was made available via Bob’s web page. This was prior to APSIM Next Gen and when APSIM Classic was being updated/maintained.
It was agreed that for APSIM Classic, bootleg models should be made available in the standard release of APSIM, otherwise development in this space won't be able to be shared. This means that the bootleg installation of APSIM can be discontinued and we can move to a single released installation.
Requirement - make it clear that if the bootleg models are made available, these models are not supported, have not been reviewed by the RP and have not been validated through the rigorous process required for APSIM 'official' models.
Only for APSIM Classic. Single release of APSIM Classic – differentiate validated and non-validated release
ACTION: @hol353 and @peter-devoil to start an "non-validated" category/tool box and work through this process.

**Comment by peter-devoil** [comment]
Here's the "readme" in the "Non-Validated" toolbox (was developers):
---
NB. The models in this folder have not been through the APSIM validation process.

These models are not supported, have not been reviewed by the APSIM Reference Panel and have 
not been validated through the rigorous process required for APSIM 'official' models.

They may be incomplete, non functional, or worse. They are intended for the use of the 
developer community.
---
