### ISSUE TITLE
Compiling with VS 2019 on Windows 10

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/APSIMClassic#1760]
What changes do I need to make to be able to compile the code with VS 2019? The attachment is the output of the process.

[BuildAllOutput.zip](https://github.com/APSIMInitiative/APSIMClassic/files/3660482/BuildAllOutput.zip)

**Comment by hol430** [comment]
Do you have git installed and on PATH?

**Comment by BenAbabaei** [comment]
I just installed it. It is on the PATH.

**Comment by hol430** [comment]
If you've just installed it, you might have to restart your terminal session...can you post the output of running `where git`?

**Comment by BenAbabaei** [comment]
It is "C:\Program Files\Git\cmd\git.exe"

I restarted the terminal. Also changed the BuildAll to use "call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
" instead of 2017. I still get the same output.

**Comment by hol430** [comment]
Just to confirm - are you running latest code?

Looks like there are two errors here - the first problem is the version stamper can't find git on the path. This is a non-fatal error I think, but it would be good to fix it nonetheless. Can you add this line of code to VersionStamper.cs on line 121, after we set the `PathVariable` variable, then rerun and post the output?

```csharp
Console.WriteLine(PathVariable);
```

Regarding the second error - is `make` installed and on PATH? Can you post the output of `where make`?

**Comment by BenAbabaei** [comment]
OK. I installed `make` and now Build is finished. I got a couple of erros, I am not sure if either are major.

`
[Fail] Compile tav_amp [1sec]
    gfortran -c tav_amp.for -cpp -D'ml_external=!' -D'STDCALL(x)=GCC$ ATTRIBUTES STDCALL :: x' -static -static-libgfortran -fno-underscoring -ffree-line-length-none -finit-integer=0 -finit-real=zero -finit-logical=false -O3 -frounding-math -g -m32 -march=pentiumpro -mtune=pentiumpro  -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/FortranInfrastructure -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropTemplate -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropMod


    process_begin: CreateProcess(NULL, gfortran -c tav_amp.for -cpp -Dml_external=! "-DSTDCALL(x)=GCC$ ATTRIBUTES STDCALL :: x" -static -static-libgfortran -fno-underscoring -ffree-line-length-none -finit-integer=0 -finit-real=zero -finit-logical=false -O3 -frounding-math -g -m32 -march=pentiumpro -mtune=pentiumpro -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/FortranInfrastructure -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropTemplate -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropMod, ...) failed.
    make (e=2): The system cannot find the file specified.
    make: *** [tav_amp.o] Error 2
`

`
[Fail] Compile FortranInfrastructure [3sec]
    gfortran -c DataTypes.f90 -cpp -D'ml_external=!' -D'STDCALL(x)=GCC$ ATTRIBUTES STDCALL :: x' -static -static-libgfortran -fno-underscoring -ffree-line-length-none -finit-integer=0 -finit-real=zero -finit-logical=false -O3 -frounding-math -g -m32 -march=pentiumpro -mtune=pentiumpro  -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/FortranInfrastructure -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropTemplate -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropMod


    process_begin: CreateProcess(NULL, gfortran -c DataTypes.f90 -cpp -Dml_external=! "-DSTDCALL(x)=GCC$ ATTRIBUTES STDCALL :: x" -static -static-libgfortran -fno-underscoring -ffree-line-length-none -finit-integer=0 -finit-real=zero -finit-logical=false -O3 -frounding-math -g -m32 -march=pentiumpro -mtune=pentiumpro -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/FortranInfrastructure -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropTemplate -IC:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/CropMod, ...) failed.
    make (e=2): The system cannot find the file specified.
    make: *** [DataTypes.o] Error 2
`
`
[Fail] Project: BuildAll [360sec]

[Fail] Target: BuildAll [0sec]
[Fail] Target: Compile [356sec]
[Fail] Target: Post-Compile [0sec]
`

**Comment by hol430** [comment]
Do you have gfortran installed? I'm guessing if you didn't have make installed, gfortran might also not be installed.

**Comment by BenAbabaei** [comment]
Fixed! Thanks.
