### ISSUE TITLE
The paremeter "tpla_inflection_ratio" has been discraded from Sorghum.xml

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1761]
The parameter **tpla_inflection_ratio** has been discraded from **Sorghum.xml** along with a number of other parameters. I am working on an older version of the code which tries to read it. Is there any reason it has been removed? Does it make a major change in the results?

_**<tiller_coef description="exponent for determining leaf area on each additional tiller">0.66</tiller_coef>
<tpla_inflection_ratio description="inflection coefficient of TPLA curve">0.66</tpla_inflection_ratio>
<main_stem_coef description="Power coeff for TPLAmax=TLN^coef">2.90</main_stem_coef>
<tpla_prod_coef units="1/oC" description="curvature coefficient for leaf area">0.018</tpla_prod_coef>
<GrainTempOrdinals>36 40</GrainTempOrdinals>**_

**Comment by jbrider** [comment]
In the latest release of apsim classic, the leaf calculations were changed
from tpla to bell curve. The latest xml file is not compatible with earlier
versions.

**Comment by BenAbabaei** [comment]
Thanks Jaso. But I see that in [Leaf.cpp](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/Sorghum/Leaf.cpp) all of these parameters are still in use (see Lines 271 and 562). Could you please point me to where the bell-type curve is calculated?

**Comment by jbrider** [comment]
In plant.cpp (101) it initiates the class LeafCulms_Fixed - the if
statement there for 'bellcurve' is for the dynamic tillering that is
currently being worked on.

LeafCulms_Fixed derives from LeafCulms which derives from Leaf.

Leaf.cpp hasn't been cleaned up which I should add to my list of jobs.
