### ISSUE TITLE
Question: 'StringSetter' does not behave like 'FloatSetter'

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/APSIMClassic#1762]
I am trying to read a string, **psType**, from a manager. 

I start by this in the leaf class constructor::
```
psType = "rue";
scienceAPI.exposeWritable("psType", "", "Photosynthesis model name", StringSetter(&Leaf::onSetPSModel));
```

Then:

```
void Leaf::onSetPSModel(string Factor)
{
	psType = Factor;
	printf("psType: %10s", psType);
}
```

In the manager:
`MyPaddock.Set("psType", "TEST");
`

But the model crashes and I get no error in the summary file. I don't have the same problem with float variables. Any reason/solution?

**Comment by peter-devoil** [comment]
try printf("psType: %10s", psType**.c_str()**);

**Comment by BenAbabaei** [comment]
Thanks Peter. I just found it out :)
