### ISSUE TITLE
irrigation on fixed date gives fatal error and and ca not recognise date column from met data

### ISSUE THREAD

**Issue by rahulrajias** [APSIMInitiative/APSIMClassic#1764]
APSIM  Fatal  Error
                      -------------------
     Cannot find date columns in file:
     The file must have one of the following combinations:
        a date column
        a year and day column
        a year, month and dom column. This error occurred while trying to read from input file C:\ProgramData\APSIM710-r4158\Examples\MetFiles\ARI_data_for_APSIM.met
     Component name: met
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by BenAbabaei** [comment]
It would help if you could share your simulation and met files.

**Comment by rahulrajias** [comment]
Hi Ben,
Please find the simulation and met file attached. 
[sim_met_file.zip](https://github.com/APSIMInitiative/APSIMClassic/files/3777067/sim_met_file.zip)

**Comment by peter-devoil** [comment]
Hi - don't try to use tabs (\t) in your met file. Spaces only.

**Comment by peter-devoil** [comment]
Hi rahul - did that fix your problem? If so, you can close the issue. P

**Comment by rahulrajias** [comment]
I guess it was not the issue of met file. I had to put the irrigation module in the paddock, then it successfully got simulated.
