### ISSUE TITLE
Making changes in Leaf and GenericLeaf to incorporate DCaPST into Plant model

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/APSIMClassic#1766]
Following our discusstion with @jbrider and Graeme and Alex, I made these changes in Leaf and GenericLeaf claases so users would have the option to dynamically switch between photosynthesis modules during the simulation. Two versions of DCaPST photosynthesis module have been implemented, 'dcapst' which is a stand alone module, and 'dcapstold' which is the old implementation of the module which was developed by Al (it starts with the RUE model and then switchs to DCaPST when LAI > 0.5).

**Comment by jbrider** [comment]
@BenAbabaei This probably isn't ready to go into release. I think I misunderstood what it was exactly. 
 I didn't realise there were 2 versions of the dcaps code - where do these fit in with the latest version that Alex is working on with sorghum?
A couple of helpful tips:  you shouldn't have any files from the Release or Debug folders included in version control, and changing the solution file is likely to be significant as well - particularly with reference to Toolset versions and SDK settings. I would avoid committing changes to the solution file unless you understand what the implications are in doing so.

**Comment by BenAbabaei** [comment]
You're right Jason. I hadn't done this in classic so I thought those files would be ignored by default.

Regarding the two versions, it's not something of importance. We can drop the old version and only keep the standalone version.

I will make the changes later today. Cheers.

On 30 Oct. 2019 10:36, Jason <notifications@github.com> wrote:

@BenAbabaei<https://github.com/BenAbabaei> This probably isn't ready to go into release. I think I misunderstood what it was exactly.
I didn't realise there were 2 versions of the dcaps code - where do these fit in with the latest version that Alex is working on with sorghum?
A couple of helpful tips: you shouldn't have any files from the Release or Debug folders included in version control, and changing the solution file is likely to be significant as well - particularly with reference to Toolset versions and SDK settings. I would avoid committing changes to the solution file unless you understand what the implications are in doing so.
