### ISSUE TITLE
APSIM7.10 compile ERROR No rule to make target 'RDataTypes.o'

### ISSUE THREAD

**Issue by sunqingmeteo** [APSIMInitiative/APSIMClassic#1773]
Hi APSIM team,

First, thanks for building a great tool for our researchers.

When I compile APSIM 7.10, I faced a problem that I searched all the internet but still can't find an answer.

My system is Ubuntu 18.04.1. So I am afraid that I can't use Docker under Ubuntu18. Then I only set the environment using command line.
Linux version 4.15.0-65-generic (buildd@lgw01-amd64-006) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))

My mono version is 4.8.1.
Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7).

I followed the linux environment in /Release/Containers/Docker.ubuntu.latest/.
All libs installed successfully. Libs included g++ gfortran libxml2-dev tcl8.5 tcl8.5-dev tcllib subversion p7zip p7zip-full mono-devel mono-vbnc mono-runtime  r-base r-base-dev r-recommended.

But still have an error which listed below.

```
[Fail] Compile RLink [1sec]
    
    
    Makefile.linux:66: warning: overriding recipe for target 'clean'
    /home/parallels/Desktop/APSIMClassic-master/Model/Build/LinuxCPP.make:83: warning: ignoring old recipe for target 'clean'
    make: *** No rule to make target 'RDataTypes.o', needed by '/home/parallels/Desktop/APSIMClassic-master/Model/RLink.so'.  Stop.
```

I thinks this error maybe caused by this line in /home/parallels/Desktop/APSIMClassic-master/Release/Containers/Docker.ubuntu.latest/Dockerfile:
```
RUN Rscript -e "install.packages(c(\"Rcpp\",\"RInside\", \"XML\"), repos =\"http://mirror.aarnet.edu.au/pub/CRAN/\")"
```

But I after I installed these three packages using R:
```
install.packages("XML", dependencies = TRUE, repos = "http://cran.rstudio.com/") 
install.packages("Rcpp", dependencies = TRUE, repos = "http://cran.rstudio.com/") 
install.packages("RInside", dependencies = TRUE, repos = "http://cran.rstudio.com/") 
```
I still got same error. What should I do?

Thanks a lot for advance.

**Comment by peter-devoil** [comment]
Hi, congratulations making it this far - it's not simple!

Did you get the latest source from git? There was a patch made (https://github.com/APSIMInitiative/APSIMClassic/commit/7784e895fa77bb657da0e69b35fb1d847917b95a) that split RDataTypes in two , and you shouldnt be getting this error any longer. 

Note that RLink is not used often, and you may be able to ignore it.

P

**Comment by sunqingmeteo** [comment]
Hi Peter,

Thanks so much for your help. I will try this version and let you know my compiling result.

Best regards,

Qing

**Comment by peter-devoil** [comment]
Hey qing - I've just realised that the linux makefile was incorrect. There should be a fix available by updating your repo very soon. P

**Comment by sunqingmeteo** [comment]
Hi Peter,

Thanks so much. I complied successfully and run without any issue when I using the latest version.
