### ISSUE TITLE
Is 'MaxOutputLines' switch removed?

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/APSIMClassic#1774]
I used to use the **MaxOutputLines** option with Apsim.exe to keep the model from generating summary files. For the first time I am using simulations with multiple paddocks in each and I am getting an error stating that some of the files are being used by another process. When I remove this switch from the command it works. Does it not work anymore? Is there any other/new way to keep the model from writing big summary files?

Cheers.

**Comment by peter-devoil** [comment]
Yeah, who cares about errors and warnings in summary files? They only get in the road.. :)

I never used MaxOutputLines. But there's a very good chance the time that each (sub) process starts will be different between the two options, so I'd check that you havent uncovered a race condition.  

If you really care about disk space, write batch files for ApsimToSim and ApsimModel, discarding the output of ApsimModel to nul. Or just finish the run with "del *.sum"...

**Comment by BenAbabaei** [comment]
Thank Peter. I dropped that switch from the command. I think it's best not to use it for now. Cheers.
