### ISSUE TITLE
APSIM failes without any of the jobs failing

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1777]
In this example, all the simulations have 'Pass' as their status but APSIM failed at the end and I cannot find any error in the summary files, except a couple of warnings. I am using **Apsim7.10-r4191.ubuntu.sapp**. I dont get the error with **Apsim7.10-r4186.ubuntu.sapp**.

[Ben-Ababaei.o140575.zip](https://github.com/APSIMInitiative/APSIMClassic/files/3929706/Ben-Ababaei.o140575.zip)

**Comment by peter-devoil** [comment]
I've noticed this too. Never found a reason why. All subprocess stdin/out will be in the summary file, and they show up as clean.
The answer would be found by creating a jobscheduler xml file (eg from the RunOnCluster code) - which can give output a bit like Build/BuildAllOutput.xml. It has the exit codes of each job.
