### ISSUE TITLE
Creat a new wheat cultuvar (APSIM Parametrization)?

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1780]
I want to parametrize APSIM by a new wheat cultuvar, please can you show me how can i do this?

**Comment by BenAbabaei** [comment]
In the APSIM installation directory (e.g. C:\Program Files (x86)\APSIM710-r4158\Model), there is a file named **Wheat.xml**, in which you can find wheat parameters at different levels. Most of the parameters are defined for the base cultivar (Hartog). You can define cultivars, which are based on this base cultivar but are different in a couple of parameters. For example, search for 'janz' in the file and see how it is created.

**Comment by peter-devoil** [comment]
Please use the "ini" component ([example here, s6](https://www.apsim.info/support/apsim-training-manuals/apsim-training-simlesa/climate-change-projections/)) when doing these experiments - it's important (for scientific repeatability) to not modify the installation directory.

**Comment by BenAbabaei** [comment]
Good point Peter.

**Comment by Achraf-UM6P** [comment]
Thank you so much. Can you help me and show me how can i use ini component to creat new cultuvar of wheat?

**Comment by peter-devoil** [comment]
I'll put something on the website how to do the technical side. Any volunteers for the science side?

**Comment by BenAbabaei** [comment]
@Achraf-UM6P do you have trouble calibrating the cultivars or you don't know how to change the Wheat.xml file?

**Comment by Achraf-UM6P** [comment]
Good morning, I want to use a Moroccan wheat variety in a simple crop growth simulation, I have phenological data (the sum of the degree days between the growth phases of the variety) and I want to parametrise the APSIM model with these data and to use this variety in the simulation, I am a beginner in the APSIM model and I want to know how can I do this step in detail?

**Comment by peter-devoil** [comment]
Hey Achraf - try this - https://www.apsim.info/documentation/model-documentation/crop-module-documentation/adding-new-cultivars-to-an-existing-crop-module/ - suggestions welcome.

**Comment by peter-devoil** [comment]
@BenAbabaei  - could you ask around the crop module people who might contribute a few words/links/references that could go at the end of that page regarding scientific procedures?

**Comment by BenAbabaei** [comment]
I will ask a couple of people whether they have something. Cheers.

**Comment by xiaozhhenu** [comment]
> Please use the "ini" component ([example here, s6](https://www.apsim.info/support/apsim-training-manuals/apsim-training-simlesa/climate-change-projections/)) when doing these experiments - it's important (for scientific repeatability) to not modify the installation directory.

Hi, Mr Devoil, I had used the 'ini' component to creat a new maize cultuvar, but in the maize.xml file, I didn't find the parameters related to grain filling, so I try to add '<grain_gth_rate units="mg/grain/dd">1</grain_gth_rate>' into the cultuvar, but It has no effect on the result. Could you tell me how to change the grain filling parameter for specific cultivar?

**Comment by peter-devoil** [comment]
As you've found, if there isnt a part of the model reading a parameter, then there wont be any change in behaviour. If you're convinced the parameter is being read, then changing it to impossible values (eg negative) may throw an error to confirm your thinking.

But in this case it wont. Maize uses a source/sink relationship to fill grain: the biomass source consists of production from (green) LAI, and retranslocation. The sink size is simply grain number times grain weight. The only "controls" are seed size, number and duration of filling. The potential rate of filling is determined by the potKernelWt (seed size) parameter divided by the duration of grain filling phase.

The usual process is to simply get the phenological stages correct (flowering & maturity). Unless you have very unusual genetic material, often this is all that is needed (let alone justify).
