### ISSUE TITLE
Degree days

### ISSUE THREAD

**Issue by Afiasarwar** [APSIMInitiative/APSIMClassic#1788]
There is a variable in output file of APSIM named "maturityTTTarget".When i manually calculate degree days for growing season of wheat the total degree days are higher than that provided by this variable? what is the reason? should i need to use tracker module to accumulate the total degree days for growing season of wheat?

**Comment by BenAbabaei** [comment]
Degree days in Apsim output is adjusted by vernalisation and photoperiod. You should use a tracker or a manager scrip to calculate unadjusted degree days.

**Comment by Afiasarwar** [comment]
Thank you for your response...I am a bit confused.My model gives me maturity_TTTarget 1(oCday) where as end_cropTTTarget is 1000 (oCday) what is the difference between two? where as degree days that i calculate from met file is 1600(oCday).

**Comment by BenAbabaei** [comment]
**end_cropTTTarget** is the thermal time required to reach **EndnCrop** from **HarvestnRips**. **maturity_TTTarget** is the same from **Maturity** to **HarvestnRips**. It is best to have a look at APSIM technical manual.

[WheatDocumentation.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/3965469/WheatDocumentation.pdf)

**Comment by Afiasarwar** [comment]
Thank you Benbabaei.
