### ISSUE TITLE
APSIM Fatal Error

### ISSUE THREAD

**Issue by Afiasarwar** [APSIMInitiative/APSIMClassic#1797]
I am facing this problem.Does anyone have any idea how to solve this issue?
                  -------------------
     Cannot sow plant - lsni-2008: wheat is still in the ground -
      Unable to sow until it is taken out by "end_crop" action.
     
     Component name: paddock.wheat

**Comment by BenAbabaei** [comment]
You are trying to plant wheat while the previous crop is still on the ground. Perhaps you are using a wring genotype which doesn't reach maturity after one whole year.

**Comment by Afiasarwar** [comment]
Thank you for your response. I am basically running APSIM for multi years furure simulation.I set clock from 2019 to 2099 and it gives output upto 2090 but for the last nine years it gives me error mentioned above.If this is because of previous crop then what should i do?

**Comment by BenAbabaei** [comment]
An easy way would be to make sure that Harvest occurs after an specific number of days after sowing, e.g. 300. But the best way to fix this is to find out why ctop doesn't reach maturity in those years, while one would expect phenology to be boosted due to warming.

**Comment by Afiasarwar** [comment]
Thank you
