### ISSUE TITLE
SWIM3 not producing subsurface_drain or subsurface_drain_no3 output

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#1798]
I've made an APSIM 7.10-r4171 wrapper with SSURGO soils, and I'm trying to get SWIM subsurface_drain and subsurface_drain_no3 output, but it's very inconsistent. Sometimes I'll get a SWIM failed to find solution error, but most of the time I get the standard "lower exceeds upper bounds" etc. and nothing else.

* My soil profiles look reasonable
* My met file has plenty of precip
* I'm running sims for multiple years.
* I've given the last two Water layers very low KS values and 0.0 KL
* Set the drainage depth at the beginning of the 2nd-to-last layer
* Set bbc_gradient to -1 as found in an APSIM workshop file, though this doesn't seem to make a different unless changed to anything other than -1, in which case I then get a lot of unrealistic numbers.

At this point I'm at a loss of what to do. Maybe my wrapper .apsim files are missing something crucial? Simulations from the APSIM workshop on tile drainage produce output just fine. Any help or advice would be appreciated. I've attached an example sim file as well.

[swim-sim.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4036027/swim-sim.zip)

**Comment by mnowatzke** [comment]
setting bbc_potential seems to have fixed the issue.

**Comment by germanmandrini** [comment]
I'm having the same issues. Would you tell me what value did you set the bbc_potential to?
Thanks

**Comment by mnowatzke** [comment]
I should open this again as it only sporadically works, but you can try making an empty manager with bbc_gradient = -1 or bbc_potential = 200 - 100
