### ISSUE TITLE
potato crop file

### ISSUE THREAD

**Issue by VGPChimonyo** [APSIMInitiative/APSIMClassic#1806]
Dear ALL

Im trying to simulate potato and im getting this error msg

The phenology class in potato has tried to move to phase number 10 but there aren't that many phases in the model.
     Component name: paddock.potato
 I have been to the crop file and i see that it has 8 stages

    <stage_code_list>1            2             3               4         5         6               7              8        </stage_code_list>
    <stage_names>sowing    germination    emergence     floralinit   tuberinit    flowering        fullsenescence  maturity </stage_names>

how can i work around this error

Regards

**Comment by BenAbabaei** [comment]
Check the 'harvest' manager script and see at what stage harvest occurs.

**Comment by peter-devoil** [comment]
Can you post a sample simulation please? This looks like an internal error that shouldnt occur.

**Comment by f-avendano** [comment]
Hey guys, I'm having exactly the same problem. Any thoughts?
Here some files that could help, 
Cheers


[Potato.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4211706/Potato.zip)
![potato error1](https://user-images.githubusercontent.com/61127136/74622025-30985f00-51a4-11ea-9569-6549c65ca56a.jpg)

**Comment by BenAbabaei** [comment]
Can you post what you have in the harves manager script?

**Comment by f-avendano** [comment]
![image](https://user-images.githubusercontent.com/61127136/74622131-879e3400-51a4-11ea-9f75-f70522c2df13.png)

**Comment by BenAbabaei** [comment]
What happens if you change 'harvest_ripe' to 'mature' or 'matiruty'? @f-avendano

**Comment by VGPChimonyo** [comment]
Thank you all for the comments and suggestions.@f-avendano yes exactly the same problem. @BenAbabaei I will work on the manager file and revert -  for us we are trying to adapt the potato file to mode sweet potato. what we want to do first is have a working potato crop file and then do an iterative adjustment of leaf and branching parameters to depict the sweet potato.

**Comment by f-avendano** [comment]
> What happens if you change 'harvest_ripe' to 'mature' or 'maturity'? @f-avendano

That worked pretty well! Thanks a lot @BenAbabaei :)

**Comment by VGPChimonyo** [comment]
It worked!

**Comment by BenAbabaei** [comment]
@peter-devoil is what I suggested the right way to fix this? I am not sure about the potato model and whether it needs some extra time between maturity and harvest. If this solution seems sufficient to you, please close this issue.

**Comment by peter-devoil** [comment]
Yes, it works, but there must be some hard wired code in Plant's phenology class that is trying to go past the end of the list of phases.. This might be triggered if the plant dies before maturity. 

I'll have a look for it one day..

**Comment by VGPChimonyo** [comment]
@Peterdevoil  Yah I understand what you saying, the phenological class in
potato are less than for most crops in APSIM. Thank you for looking into it
Vimbayi Chimonyo
