### ISSUE TITLE
Simulating CRF

### ISSUE THREAD

**Issue by f-avendano** [APSIMInitiative/APSIMClassic#1807]
Hi guys,

I would like to simulate a controlled release fertiliser trial. The release rate depend strongly on growing degree days. Do you have any clue on how to build a script for this? Like, how do I tell Apsim "please release this N daily depending on average temp"?

Thanks in advance!

**Comment by BenAbabaei** [comment]
You need a manager script. You can find examples in the Toolbox which will give you ideas how to do it.
