### ISSUE TITLE
Tracker 

### ISSUE THREAD

**Issue by Thobekakunene** [APSIMInitiative/APSIMClassic#1808]
Hi everyone 

I am struggling to get output using a tracker module. I have specified all my variables but the .out file come as blank
![Tracker issue](https://user-images.githubusercontent.com/61177165/75007450-db976a00-547d-11ea-8d3a-262e687479de.PNG)

**Comment by jbrider** [comment]
Does the summary file show crops being planted and harvested?

If it does, then try using sowing instead of canola.sowing.
I'm not sure if canola.sowing is the proper syntax, so I would start by
testing the same syntax as on the right side, the making the change too see
if it works.

**Comment by peter-devoil** [comment]
If the output file is completely empty (ie column headers only), then the output event (in My Variables Events) didnt happen.

If the tracker variables are showing "??" marks then something went wrong with tracker - either one of the events didnt occur, or the variable being tracked misbehaved.

**Comment by Thobekakunene** [comment]
Thank you for your suggestion however I still can not get output for the tracker variables. This time around I am tracking one variable

![Capture 1](https://user-images.githubusercontent.com/61177165/75320180-d61f9280-5876-11ea-93dc-4941e4eae24b.PNG)
![Capture 2](https://user-images.githubusercontent.com/61177165/75320192-dc157380-5876-11ea-96e1-1a4054e2fdc8.PNG)
![Capture 3](https://user-images.githubusercontent.com/61177165/75320342-27c81d00-5877-11ea-8c61-981b2eb6bdf2.PNG)

**Comment by peter-devoil** [comment]
In your output file  (amaranth) variables, change "sum of ..." to just "rainfall".
"sum of ..." is tracker-like syntax
the report component wants a different syntax
is there a fatal error further down in the summary file?

**Comment by Thobekakunene** [comment]
I have changed the variable name. 
There is no fatal error. But the output is still empty

![Capture 4](https://user-images.githubusercontent.com/61177165/75327470-2140a200-5885-11ea-980c-1d847128c9d9.PNG)

**Comment by peter-devoil** [comment]
Contrary to what I said above, if the reporting event never occurs, you'll get an empty file.
Is the "My Variables Events" output frequency set to harvesting?
If it is, can you see the crop being harvested in the summary file?

**Comment by Thobekakunene** [comment]
It wasn't. But now that it is set, the tracker variables are showing the "?" marks. So it goes back to what you were saying before, that either the variable is misbehaving or event did not occur

**Comment by peter-devoil** [comment]
Can you check that the events (sowing, harvesting) occur - the summary file should have some messages saying so.

**Comment by Thobekakunene** [comment]
Thank you so much for your suggestions. I have finally managed to get an output. Under the "My Variables Events" I changed to harvesting and under harvesting rule, stage name was set to "floral_initiation"

**Comment by peter-devoil** [comment]
Ah. 

It's worth remembering that variables are not events - even if you see a variable (eg stagename) set to floral_initiation, it's not necessarily the case that a floral_initiation event was sent out. Unfortunately, each crop module does this phase transition differently (some do, some dont), so the only reliable method is to write some manager logic that watches for the stage of interest occuring, and do something at that time (eg trigger a line of output in the report).

**Comment by Thobekakunene** [comment]
This is noted. Thank you

**Comment by peter-devoil** [comment]
@Thobekakunene - you can close this issue if you think it has been answered. People can still find it by searching.
