### ISSUE TITLE
Maize should use structures instead of variants on sowing

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/APSIMClassic#1812]
Maize uses an old-style variant to pass in the sowing arguments. Manager2 cant deal with this and crashes.

**Comment by peter-devoil** [comment]
Resolved in https://github.com/APSIMInitiative/APSIMClassic/pull/1813

**Comment by BenAbabaei** [comment]
Hi @peter-devoil . Is Manager2 the .NET one?

**Comment by peter-devoil** [comment]
Yes - it's worth persisting with as it can be extended to work in multipaddock/crop situations.

**Comment by BenAbabaei** [comment]
It sure is.
