### ISSUE TITLE
Irrigation Effect

### ISSUE THREAD

**Issue by Afiasarwar** [APSIMInitiative/APSIMClassic#1815]

**Comment by Afiasarwar** [comment]
Thank you peter for your kind words
1.I have added Cum_irrig to report variables which is 165 mm.
2.i disabled phosporus module.
3.i am using spring wheat.
4.Initial water is 132 mm, cum rain is 23.2 mm, irrig is 4*55mm, Cum_transpiration is 108.99mm.
5.there is a little stress of water  0.013 , 0.042 in a stage of flowering to start grain fill units while 0.017, 0.022 stress from start grain fill to end grain fill units.
But still i am unable to figure out the issue .here is my .xml file attached(pdf format) please have a look
[xml file.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4341735/xml.file.pdf)

Thanks with anticipation

**Comment by peter-devoil** [comment]
Hi afia, can you please post the raw file (not a pdf) - you may need to rename it to .txt or add to a zipfile. The pdf format mucks up the xml.. 

As well, when do you expect your crop to flower and reach maturity?

Thanks

**Comment by Afiasarwar** [comment]
Here is Xml file attached.
[Wheat.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4374934/Wheat.zip)
flowering is expected in february and maturity in march.

**Comment by peter-devoil** [comment]
Hi afia,
I've been able to run your simulation - your flowering and maturity dates are reasonable, so we can explore further. 

As you see only very small water stresses in the summary, you can say there is plenty of water in this system, and as you've found, reducing it (by a total of 40mm, - 10mm at each irrigation) will have only a minor effect. 

To guage the models response you'll have to remove more water - for example, by removing entire irrigation applications. Removing the 4th (scheduled for the day after harvest) encouragingly had no effect. The third reduced final transpiration by 4mm and biomass by 120kg. The second by 750kg. and so on. If you are adding water that the plant cannot use (at the top end of yields), the plant wont respond.

If you do enough of these "what ifs" you'll discover a moderately linear relationship between yield & transpiration - the French & Schultz relationship, popular in categorising rainfed systems down here. If you can [confirm that experiment](https://grdc.com.au/__data/assets/pdf_file/0028/207667/water-use-efficiency-southwest.pdf.pdf) you should be happy.

But I expect that APSIM won't do a very great job in repeating your experiment a) if you haven't got measured starting water, and b) haven't got a timecourse of plant growth observations through the winter.
