### ISSUE TITLE
dlt_no3_net?

### ISSUE THREAD

**Issue by f-avendano** [APSIMInitiative/APSIMClassic#1817]
Hi everyone,

I just bumped into this variable and was wondering if I can use it as an equivalent to nitrate leaching when applied to the last layer (e.g. when it gives negative values). And if not, is there any reportable variables from ApSIM modules that are equivalent to nitrate leaching or do I have to create one in a manager script?

Thanks,

**Comment by JNGH** [comment]
leach_no3 will report nitrate leached out of the profile for the day.

**Comment by f-avendano** [comment]
Thank you very much John!
