### ISSUE TITLE
Modelling crop growth with hourly radiation

### ISSUE THREAD

**Issue by l4h4rl** [APSIMInitiative/APSIMClassic#1821]
Hi there,

I am currently doing research on modelling an agrivoltaics system (agriculture and solar photovoltaics). One of my goals is to get the effect of shading from the solar panels during different hours of the day on crop growth or yield. E.g. providing shading during intense irradiation period at noon.

Is there a way to input hourly solar radiation data for the modelling? Will manually changing the weather files daily values into hourly values have the same effect?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note question from @l4h4rl

**Comment by yashvirchauhan** [comment]
The radiation values used in the APSIM model are daily cumulative hourly values, so if you add up hourly values, which will incorporate shading effect,  will be good.

**Comment by l4h4rl** [comment]
> The radiation values used in the APSIM model are daily cumulative hourly values, so if you add up hourly values, which will incorporate shading effect, will be good.

@yashvirchauhan thanks for the quick reply. Yes, you are correct, up until that point that is possible.

However, it doesn't show the effect of shading during different hours of the day, although it may add up to the same daily value. According to the literature, providing shading at noon when irradiation is typically the highest will have a different effect as opposed to morning shade.

**Comment by peter-devoil** [comment]
You could input hourly data (there are hydrological modules that use per-minute inputs), but unless something is using it, it will be ignored. As yash says, the crop model uses a daily sum, so it only remains for you to aggregate your loggers watts/hr (that span both shaded and unshaded times of day) to mj/m2.
