### ISSUE TITLE
Apsim-Tropical Pasture model

### ISSUE THREAD

**Issue by jusamayer** [APSIMInitiative/APSIMClassic#1829]
Hello APSIM Team

I am a PhD student and new to APSIM. I am interested in using the APSIM-Tropical Pasture model. The model was used for modelling the Palisade grass in Brazil, and I would like to use the same model and adapt it to my country Paraguay. I can't find the model under the crops options or in the APSIM website. I will appreciate your assistance in finding the model, please

Regards,

Julio Mayeregger

P.S.> I have attached the PhD thesis of the Brazilian research
[Palisade grass model.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4473757/Palisade.grass.model.pdf)

**Comment by hol353** [comment]
@mpandreucci Can you respond to this question for old APSIM?

**Comment by zur003** [comment]
@jusamayer - The Tropical Pasture model was developed using APSIM Next Generation (also known as ApsimX), not the classic version of APSIM, so you need to be looking at the [ApsimX respository](https://github.com/APSIMInitiative/ApsimX). More specifically, the model and associated files can be found [here](https://github.com/APSIMInitiative/ApsimX/tree/master/Prototypes/TropicalPasture).

**Comment by mpandreucci** [comment]
Hi Julio (@jusamayer ).
As Eric (@zur003 ) mentioned, this is a APSIMX model, so it's in the new set of APSIM models, not the old APSIM (classic).
Yes the model was developed using braquiaria. It's not in release yet and that's why it's under the prototypes, as you can see in the link Eric sent you.
What type of grass do you want to model?

**Comment by jusamayer** [comment]
Morning Dean (@hol353), Eric (@zur003)

Thanks for your quick reply! I was working with APSIM Classic, but I now will be switching to APSIMX. I am trying to model Brachiaria brizantha (cv Marandu or Piata). I feel so happy that Eric sent me the repository (is like striking gold for me). I have the parameters for my pasture, met data, and soil data.  My next issue is that I don't know how to upload the model into APSIMX. Would you have a guide or a page where I can go and learn the steps to upload the model?

Thanks in advance

Julio

**Comment by sarahcleary** [comment]
for single files, you will want to use the raw button on the file:
![github](https://user-images.githubusercontent.com/47995399/79287208-6472d500-7f06-11ea-93b5-e2b44784dc13.png)

 For directories, any of the solutions here: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo

**Comment by mpandreucci** [comment]
@jusamayer 
Could you please send me your email? I can send you everything and have a chat to you about what's been done so far

**Comment by jusamayer** [comment]
@mpandreucci 

yes please! my email is jusamayer@gmail.com

Cheers

Julio
