### ISSUE TITLE
maize-wheat rotation with Apsim

### ISSUE THREAD

**Issue by Lsbrd** [APSIMInitiative/APSIMClassic#1830]
Hello,

I am a student and new to APSIM. As part of my internship, I try to represent with APSIM a maize-wheat rotation (image 1) under temperate climate. When i use rotation sample provide with APSIM 7.10, there is a message error which appears when i add maize crop to the paddock (image 2). Can you help me ?
So i started a new simulation using Maize Legume and Weeds Rotation as a template and following the help available on APSIM Training (SIMLESA) "Maize-Legume crop simulations", but when i set the fallow periods (image 3), they are not respected during the simulation (image 4). Can you help me again ?

Regards,

Louis BOURDIN

image 1
![image 1](https://user-images.githubusercontent.com/63654070/79244956-be788980-7e77-11ea-8a77-b29f7eec5d25.png)
image 2
![image 2](https://user-images.githubusercontent.com/63654070/79244961-bfa9b680-7e77-11ea-9014-6dfff2d52b33.png)
image 3
![image 3](https://user-images.githubusercontent.com/63654070/79244962-bfa9b680-7e77-11ea-8b02-df5a80e03593.png)
image 4
![image 4](https://user-images.githubusercontent.com/63654070/79244965-c0424d00-7e77-11ea-8753-98fa0372d47c.png)

**Comment by peter-devoil** [comment]
This was a bug in the maize module. You can get an updated version that fixes it from [here](https://apsimdev.apsim.info/APSIMClassicFiles/1828.apsimsetup.exe).

**Comment by hol430** [comment]
The installer for #1828 won't be generated until it's merged, assuming my changes work out. If you're looking for the latest installer, [this](https://apsimdev.apsim.info/APSIMClassicFiles/1813.apsimsetup.exe) might do the trick.

I will have to change the Bob webpage so that the installer links don't show up until the build is merged.

**Comment by peter-devoil** [comment]
Thanks, drew.

**Comment by Lsbrd** [comment]
Thanks a lot i'm going to check this

**Comment by Lsbrd** [comment]
it works ! thanks
