### ISSUE TITLE
Crop failed due to loss of leaf area 

### ISSUE THREAD

**Issue by Attia81** [APSIMInitiative/APSIMClassic#1833]
Hello
I'm calibrating new maize cultivar in arid sandy soil and have a problem with crop phenology. The observed phenology is late-medium maturity with anthesis at 65 DAS and physiological maturity at 114 DAS. While the simulated anthesis is good (64 DAS), the crop is terminated early at 98 DAS due to loss of leaf area. Is it too hot for APSIM or what's the problem. 

some info

   Crop Sowing Data
         -------------------------------------------------------
         Sowing   Depth  Plants Spacing Skiprow Cultivar
         Day no     mm     m^2    mm     code     name  
         -------------------------------------------------------
            139   100.0     7.0   700    1.0     mh12
         -------------------------------------------------------
     
      - reading constants for plant(maize) - mh12
         tt_emerg_to_endjuv       =  290.00
         tt_endjuv_to_init        =    0.00
         tt_init_to_flower        =   50.00
         tt_flower_to_maturity    =  750.00
         tt_flag_to_flower        =   10.00
         tt_flower_to_start_grain =  170.00
         tt_maturity_to_ripe      =    1.00
         ------------------------------------------------------

     Average Stress Indices:                          Water Photo  Water Expan  N Photo
        Emergence           to End of juvenile           1.0          1.0        1.0    
        End of juvenile     to Floral initiation         1.0          1.0        1.0
        Floral initiation   to Flag leaf                 0.8          0.5        1.0
        Flag leaf           to Flowering                 1.0          1.0        1.0
        Flowering           to Start grain fill          0.6          0.3        0.9
        Start grain fill    to End grain fill            0.9          0.8        1.0      #is this too much stress

```
24 August 2011(Day of year=236), maize:   
      ********** Crop failed due to loss of leaf area ********     Plant Death. Standing above-ground dm = 12080.02 (kg/ha)
```

*Note: using a late maturity cultivar in the default continuous maize example produced the same problem?

*Update: the 7.5 version worked fine and did not show this problem noted in 7.10 version!

Best, Ahmed

**Comment by sarahcleary** [comment]
@mcleang - are you able to assist?

**Comment by BenAbabaei** [comment]
@Attia81 I am not experienced with Maize mode. But you can add some irrigation to see whether it can help. If it does, plant might have started to senescene earlier or faster due to water shortage and you may need to calibrate with stress sensitivities.

**Comment by Attia81** [comment]
@BenAbabaei Tried this and it did not resolve the problem. Not sure how to interpret the stress indices; is 1 indicates high or low stress? 

The older version of APSIM 7.5 did not show this problem

**Comment by BenAbabaei** [comment]
For water stress, 1 means no stress and zero means severe water limitation.

Dr Ben (Behnam) Ababaei

Research Fellow in Crop Modelling and Physiology, The Centre for Crop Science,
The Queensland Alliance for Agriculture and Food Innovation (QAAFI),
The University of Queensland, Australia.

Address: Demountable A, Leslie Research Facility, Toowoomba, QLD 4350, Australia
Mobile: +61 (0) 4 81 708 020
Email: b.ababaei@uq.edu.au<mailto:b.ababaei@uq.edu.au> , behnam.ab@gmail.com<mailto:behnam.ab@gmail.com>
Profiles: @UQ<https://qaafi.uq.edu.au/profile/3389/behnam-ababaei> , @ResearchGate<https://www.researchgate.net/profile/Behnam_Ababaei> , @LinkedIn<https://www.linkedin.com/in/behnam-ababaei/> , @Twitter<https://twitter.com/AbabaeiBen>

**Comment by leandrogiovannini** [comment]
I've also had this problem. It seems this issue was introduced after release 4194. I don't have this problem with APSIM 7.10r4194

**Comment by peter-devoil** [comment]
There were some canopy changes related to frost sensitivity introduced then. If you can find an example of misbehaviour, I'm sure @jbrider would be interested. Make sure you include your met file in the example.

**Comment by XijuanXu** [comment]
Hello
I had the same problem. What do you find to be the cause of it? How did you solve it in the end?
thanks

**Comment by peter-devoil** [comment]
Look for a very cold day in the met record.

**Comment by XijuanXu** [comment]
Dear sir 
I don't understand what you said. If I find the cold day in my met file. I used APSIM7.10-r4216 for my simulation. What should I do next?
thanks

**Comment by BrianCollinss** [comment]
@XijuanXu Hi. Check your weather data (.met file) to see if you have very cold days during the growing season.

**Comment by XijuanXu** [comment]
I don't find extreme cold days during the maize growing season.

**Comment by XijuanXu** [comment]
Dear sir 
I studied yield changes in winter wheat-summer maize rotation under rainfed conditions from 1965 to 2100. I found that the leaf area of both wheat and corn was at a very low value, and the yield of wheat and corn was simulated to be very low. What causes their leaf area to be so low? What should I look for?

**Comment by jbrider** [comment]
If the temperature falls below 1.0 degrees it will remove nearly all of the current leaf area due to a frost event.
Quite often the plant will not recover from this vent.

If the temperature falls below -3.5 it will kill the plant.

**Comment by XijuanXu** [comment]
hi
I found it was probably due to the lack of water. When I added irrigation, I solved this problem. However, my experiment was rainfed, and there was a lot of rain during the summer corn growth period.

**Comment by jbrider** [comment]
If you graph the LAI you will be able to tell if it was from a frost event - there will be a sudden loss of LAI.
You should also check your met file for any bad records - 0 values in summer for instance.  
Looking at the LAI graphs should highlight any bad records.
