### ISSUE TITLE
Irrigation management options in APSIM

### ISSUE THREAD

**Issue by Attia81** [APSIMInitiative/APSIMClassic#1838]
What are the irrigation management options in APSIM? Where to find good documentation of irrigation options in APSIM?
Is there growth stage based irrigation management or ET based irrigation management options in APSIM?

**Comment by peter-devoil** [comment]
The [documentation](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/irrigation/) is mostly concerned with efficiencies & budgeting, and little on dynamic application. It assumes basic knowlege of manager scripts and how to write them. The module itself is basic, as the manager(s) provide far more flexible means to control it.

You could easily adapt the growth stage fertiliser application code (eg "fertilise on a zadok stage window") to irrigation application, remembering that not every plant module uses Z stages.

But to make a water stress problem go away, most people simply turn on automatic irrigation (in the irrigation component itself), and set a high ESW threshold for topping up.

**Comment by Attia81** [comment]
@peter-devoil Thanks that's very helpful.

**Comment by peter-devoil** [comment]
No worries, @Attia81 - you can close this issue if you think it's been resolved.
