### ISSUE TITLE
Modelling soil phosphorus in maize-wheat rotation

### ISSUE THREAD

**Issue by Lsbrd** [APSIMInitiative/APSIMClassic#1848]
Hello,
I am trying to simulate a 6-year corn-wheat rotation with APSIM 7.10-r0 but when I drag a phosphorus node into my soil node, the simulation does not work. So I tried again with a wheat sole crop but the summaryfile node says: "Cannot find a value for the parameter: x_p_stage_code Component name: paddock.wheat". 
I tried to write parameters adapting for wheat crop in section 10 of the wheat.xml file but it doesn't work. Could you please help me? Is there a solution?

**Comment by peter-devoil** [comment]
Hi,

I doubt anyone's put together a P parameterisation for cereals, but here's how to make a start. In https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/Cowpea.xml, lines 101:129, you'll find  block of parameters that is repeated for just about every other crop that is "P sensitive". I'd hazard a guess that most are simply copied. Nevertheless, those same parameters will be read by the wheat module, and as you see, it's not finding them. 

Things to try are: a) intentionally corrupt your xml file to be sure apsim is reading it and not something else, b) put outrageous / impossible values in there and make sure it generates an error.

If you're really stuck, you can post your modified files here and we'll have a look.

You're aware of [some bugs](https://github.com/APSIMInitiative/APSIMClassic/issues/1736) in the maize P code at the moment? I think they may have been resolved in a recent update (which you can get [here](https://apsimdev.apsim.info/APSIM.Registration.Portal/Main.aspx) ) but you should check.

**Comment by peter-devoil** [comment]
Have you made progress on the simulations? If your questions have been answered here, you can close the issue

**Comment by Achraf-UM6P** [comment]
Hello,

I found the same probleme with a simple wheat simulation.
I tried to integrate the line 101-128 in my wheat.xml document and it is working. The question is, if the values used in the cowpea are the same in wheat?

Thank you
Best regards

**Comment by peter-devoil** [comment]
Most likely wheat & cowpea would not share the same values. I have some data from @EnliWang that will find it's way into the version control system within a fortnight - perhaps that will be illuminating when it appears. Watch this space.

**Comment by EnliWang** [comment]
Thanks Peter, if you could manage to get the data in and the simulations working, that would be really great! We will try to do some further work as well (with new data).

**Comment by peter-devoil** [comment]
Perhaps somebody has a clue on this: in the Phosphorous module, it asks for the value of p_demand for each crop. It does a bound check on this value, and generates a warning message if it exceeds 2 g/m2. Is this (2 g/m2 / day) a reasonable upper limit?
