### ISSUE TITLE
requesting for AusfarmPasture.xml

### ISSUE THREAD

**Issue by 20091108wl** [APSIMInitiative/APSIMClassic#1849]
I am running the APSIM7.10 version. I intend to change several genetic paramaters for AusfarmPasture, but I can not find where this .xml file is. I have used APSIM-wheat before, and I can find wheat.xml file in  C:APSIM710-r4158\Model\wheat.xml, so my question is where to find AusfarmPasture.xml?

**Comment by her123** [comment]
To use different parameters with the AusFarmPasture you will need an external parameter file. Here is one you can download: https://cloudstor.aarnet.edu.au/plus/s/oX33naSSuw9z7jZ
To attach it to the model you need to set the property: 
![image](https://user-images.githubusercontent.com/11879671/80655154-4c33b600-8ac1-11ea-96e9-a6db3d78aebb.png)
If you want to edit the parameters you should know what they are. You can access the pasture model document at: https://cloudstor.aarnet.edu.au/plus/s/HJRfYznZr4uN6YR
The parameters are in an XML document but there is a GUI editor you can use from: https://cloudstor.aarnet.edu.au/plus/s/BZzII8qYPHiMFno

**Comment by peter-devoil** [comment]
Feel free to raise another issue if you need.
