### ISSUE TITLE
Update DCaPST dll and examples

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/APSIMClassic#1857]
DCaPST was updated so need to update the dll and example file scripts.
Also add a sorghum example file

**Comment by hol430** [comment]
Why have we committed a dll?

**Comment by jbrider** [comment]
Good question. That's how it was developed initially and I can't say I know exactly why it was done that way. We haven't looked to change the way it integrates with Classic as it was working just fine.  Now that we've started work on integrating it with NextGen, we should look at doing it the right with Classic as well.
