### ISSUE TITLE
Apsim french interface?

### ISSUE THREAD

**Issue by Hadir2020** [APSIMInitiative/APSIMClassic#1861]
Hi, I am a new user of APSIM, I am using APSIM for non commercial use, I was just wondering if there is a possibility to change the language of the APSIM interface from english to french?+
Thanks,

**Comment by peter-devoil** [comment]
Hi Hadir,

I'm afraid that that's unlikely for Apsim Classic, but highly likely with Apsim NextGen.

One of the reasons we switched to the new framework was to cope with internationalisation issues just like this. It's very tricky in the old framework - much of it is written in fortran which has no concept of commas being decimal separators etc..

**Comment by Hadir2020** [comment]
Hi Peter,

thanks for your reply, does the Apsim Nextgen also offer the same options and also as stabil as the classical one?

**Comment by peter-devoil** [comment]
It depends. It doesn't have the range of crops & soil processes (yet) but it is constantly improving. Check out the [documentation](https://apsimnextgeneration.netlify.app/modeldocumentation/). From a software perspective, it's new and hasn't had 20 years of use and bugfixing; but the new framework has been designed with 20 years of experience and a solid understanding of the application domain.

**Comment by zur003** [comment]
@peter-devoil - Are we actually giving consideration to true internationalisation in Nextgen? By that, I mean all the textual material, not just number and date formatting.

**Comment by hol353** [comment]
No we're not. We don't have the resources to do that unfortunately.

**Comment by peter-devoil** [comment]
Feel free to raise another issue if you need.
