### ISSUE TITLE
 A biochemical photosynthesis module in apsim classic

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/APSIMClassic#1862]
A biochemical photosynthesis module, DCaPS, is being incorporated into sorghum, [maize](https://github.com/APSIMInitiative/APSIMClassic/issues/1850) & [wheat](https://github.com/APSIMInitiative/APSIMClassic/issues/1766).  

...

**Comment by shaoyuGao** [comment]
Where can I find the answer

**Comment by shaoyuGao** [comment]
How can I use DCaPS in the APSIM-maize

**Comment by peter-devoil** [comment]
After you update your installation (from [https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx](https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx)), you'll find a sorghum example in the "new simulations" folder. The maize implementation should be using the same manager (DCaPS_C4_short).
