### ISSUE TITLE
Oat cultivars Australia-specific?

### ISSUE THREAD

**Issue by adam-weis** [APSIMInitiative/APSIMClassic#1863]
A little background: we're interested in running some corn-soy rotations integrating oats to varying degrees. However, when setting up oat simulations, the yields are just really really low. Typical US Midwest oat yields appear to be upwards of 60-70+ bushels/acre. However in APSIM, without fertilizer, I get about 7-8 bushel/acre. With N fertilizer, they can hit that 60-70 number but from what I've read, oats don't often receive very much fertilizer.

APSIM comes with 14 oat cultivars: 

Algerian
Barcoo
Coolibah
Drummond
Echidna
erect
Kojohup
Mitika
Potoroo
prostrate
semi-erect
Taipan
Williams
Wintaroo

All but one (Echidna) follow the trend of needing 150+ lbs N/ac to achieve 60 bu/ac yields (the expected yield). Echidna, however, gives much higher yields per N amount. Echidna gives 60 bu/ac with just under 50 lbs N/ac, which seems closer to a typical US Midwest fertilizer application. (I've included a plot of these patterns below, where Wintaroo is representative of all cultivars other than Echidna)

Question: does anyone know if crop cultivars/varieties are often Australia-specific in APSIM? Could that be why these oats are not giving more typical yields?

Or does anyone have other thoughts concerning this oats issue?

Thank you!

![oat_yields_plot](https://user-images.githubusercontent.com/65413232/82074829-f6eecb80-96a0-11ea-8218-02fa17917d59.png)

**Comment by sarahcleary** [comment]
@hol353 and/or @peter-devoil - can you please suggest someone to answer this?

**Comment by hol353** [comment]
@HamishBrownPFR any clues what is happening here?
