### ISSUE TITLE
the summaryfile and outputfile is empty

### ISSUE THREAD

**Issue by guochaoqiong** [APSIMInitiative/APSIMClassic#1864]
Hello everyone, I am a novice. When I run the model, I have a problem and I can't find the reason. I hope I can seek help here. After I practice Exercise 1: Fallow Water Balance. After building the model, I click the "run" button and it shows 100% completion. However, "File does not exist" is displayed under the "output file" component, and then look at  "summary file" ,which shows no running process and is almost blank. I tried to change a computer and another version of the software, the results are the same, I do not know where the problem is.

**Comment by BrianCollinss** [comment]
[Fallow water balance.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4654642/Fallow.water.balance.zip)

Are you using a working version of the model and the example? I tried the same file from Example folder and it worked.

![image](https://user-images.githubusercontent.com/39573622/82405419-3190a380-9aa7-11ea-90e4-80fe2c0f75ab.png)

**Comment by guochaoqiong** [comment]
@BrianCollinss 
Thank you for your reply. I used the software to open the file you uploaded, and the result was empty. Does that mean there's something wrong with my software?
![2](https://user-images.githubusercontent.com/65606864/82421496-ab2e8e80-9ab3-11ea-840e-95c348a1f5b1.JPG)

**Comment by BrianCollinss** [comment]
How about summary files?

**Comment by guochaoqiong** [comment]
@BrianCollinss 
The result is the same.
![3](https://user-images.githubusercontent.com/65606864/82425265-dcf62400-9ab8-11ea-9889-5543a424befc.JPG)

**Comment by guochaoqiong** [comment]
![4](https://user-images.githubusercontent.com/65606864/82425555-3f4f2480-9ab9-11ea-9c33-23ec97be12fe.JPG)

**Comment by peter-devoil** [comment]
All the apsim examples should run out of the box. So opening, immediately saving, and running should be ok.

If that doesnt work, I'd take a punt on regionalisation issues: try setting your computers [regionalisation settings](https://support.microsoft.com/en-au/help/4027266/microsoft-store-how-to-change-your-country-or-region) to australia (you can always switch them back).

In this case, the simulation has stopped when loading the modules (dlls) from disk, well before it has started to feed them paramaters. That's unusual.

**Comment by zur003** [comment]
@peter-devoil - Any chance this could be a problem with .Net support?

**Comment by peter-devoil** [comment]
Yes. The next step would be to run ApsimToSim.exe or Apsim.exe from command line and see if errors are shown on the stderr stream.

**Comment by guochaoqiong** [comment]
Thank you all, my problem is solved. But I don't know where the specific problem is. Because there are adjustments in NET Framwork , software installation path, and re-installation, etc., so I am not sure where the problem is.
