### ISSUE TITLE
Can apsim handle concurrent requests?

### ISSUE THREAD

**Issue by shrestha94sujan** [APSIMInitiative/APSIMClassic#1866]
say i execute command ../apsim a.apsim and immediately execute ../apsim b.apsim again,  is there a way apsim can handle those requests concurrently?

**Comment by hol430** [comment]
You should be able to run `../apsim a.apsim b.apsim`.

**Comment by peter-devoil** [comment]
Apsim.exe is basically a job scheduler that takes its jobs from a command line, the workers are ApsimToSim.exe (convert .apsim to .sim) and ApsimModel.exe. 

I dont think giving it pipes or fifos would work as it doesnt do anything until it knows what to do..

**Comment by shrestha94sujan** [comment]
@hol430 yes, that works if i want to run them together, but i am trying to run them as separate processes because say when i am running  a.apsim file i may not have b.apsim file on hand. But, say a request was made to a micro service and b.apsim file was generated. So, my question is how do i run b.apsim separately while ./apsim a.apsim is waiting to be finished in a thread?

**Comment by peter-devoil** [comment]
You'll have to use some sort of batch scheduler. Perhaps https://www.gnu.org/software/parallel/ can help.

You should also beware of having the same simulation name in more than one .apsim file: they will overwrite each others inputs (the sim file) and outputs.

**Comment by shrestha94sujan** [comment]
@peter-devoil yes, that looks like the only option, however i was hoping to find apsim would have some hidden feature for parallel processing. and, i am aware of the overwrite and i do have solution for that but thanks for the heads up.

**Comment by peter-devoil** [comment]
Sorry - it's all out there on the command line. While Apsim.exe is OK for workstation - level parallellism, there are better ways to do it on larger scales. There are a few [bits of code](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/ApsimFile/RunCondorJob.cs) to build condor/pbs batch scripts that you may be able to adapt - but most of that stauff is site-specific and may not suit everybody.

**Comment by shrestha94sujan** [comment]
@peter-devoil Thanks

**Comment by peter-devoil** [comment]
Feel free to raise another issue if you need.
