### ISSUE TITLE
measure units of the variables in the XY graphic

### ISSUE THREAD

**Issue by samarambar** [APSIMInitiative/APSIMClassic#1867]
Hi!
I start at this time on APSIM. I'm training in the YouTube video on APSIM channel. I'm using every example of suggestions, the same in videos. So, something is strange for me... my measure units when I finish the simulation is different than those shown in the video training. 
For example in the "Continuous sorghum: some columns appear as multiplied for 1000 as: 
**dlayer** =150000;
 **sw** = 490; 
**LAI** = 12... 107...; 
and **Biomass** and **Yield** appear as multiplied for 10.

How I can fix this? I cannot understand why this occurs since I do everything the same in the training. 
      Thanks!               

![issue](https://user-images.githubusercontent.com/66262573/83423224-adb8ae80-a3f8-11ea-9dd2-ce97a4af027f.png)

**Comment by peter-devoil** [comment]
Hmmm. That's interesting. I suspect that your regionalisation settings is dropping the decimal.

Try setting your region (https://support.office.com/en-us/article/change-the-windows-regional-settings-to-modify-the-appearance-of-some-data-types-edf41006-f6e2-4360-bc1b-30e9e8a54989) to australia and see if it goes away. When you change it back, can you tell us your native region so we know about it. Thanks.

**Comment by samarambar** [comment]
Thank you so much, Peter! Your advice worked for me! 
I had a Brazilian configuration before and when I go back for this the units really change. I will need to keep in Australian configuration on my computer for the best performance.
Thanks!

**Comment by peter-devoil** [comment]
Feel free to create another issue if you have questions.
