### ISSUE TITLE
Irrigation systems

### ISSUE THREAD

**Issue by Attia81** [APSIMInitiative/APSIMClassic#1871]
Hello, 

I would like to know how to account for different irrigation systems in the model. I have two experiments; one was conducted under surface drip and another one was conducted under furrow irrigation. Amounts of irrigation water were measured at each experiments. I want the model to consider the different irrigation systems used in these studies, what is the best way to do this?

Best, Ahmed

**Comment by peter-devoil** [comment]
As you're aware, the irrigation component implements "top down" application with little flexibility in 
(vertical) distribution.

If you're using the cascading bucket water balance, you can use the manager component to add water to individual layers by setting a variable "dlt_sw_dep" - a (daily, mm/layer) change in soil water content - be careful to set sensible values as it's not bounded by bucket size.

With swim, you'd have to calculate the value of "sw" after the irrigation event and set it directly

Manager1 scripts can set vectors, but the procedure will be easier in a manager2 script.

**Comment by Attia81** [comment]
Hi Peter, 

This is very helpful, I'll try to implement it. thanks. In addition to "dlt_sw_dep", I saw an "irrigation_efficiency" parameter in the swim Script, which I think can be adjusted based on irrigation systems, e.g., the efficiency of furrow irrigation should be less than drip-irrigation in terms of delivering the water to plants root zone. Do you think this parameter should vary between the two systems?
note: the water amounts are measured based on the discharge rate at the main water source. 

Best, Ahmed

**Comment by peter-devoil** [comment]
I suspect the irrigation efficiency parameter refers to a simple scalar multiplier used by the irrigation module. If you're using the manager option (sending resets/deltas directly to soil) you won't b eusing the irrigation module.

WRT your measurements: apsim's ignorant of transmission efficiencies unless you explicitly tell it (like the efficiency parameter above) - the water bore/channel/etc components were set up to explore those efficiencies _in the long term_ - they dont concern themselves much about the immediate application of water beyond dumping it onto the soil.
