### ISSUE TITLE
Weird relationship between N stress and Maize yield

### ISSUE THREAD

**Issue by martividal** [APSIMInitiative/APSIMClassic#1876]
Hello,

Running a long term maize simulation under cc scenarios, I was exploring the relationship of Nfact_photo (nitrogen stress factor) and yield reported at the end of the season. Weirdly, there seems to be a very strong correlation between increased stress (nfact_photo closer to 0) and increased yield.

Are the reported Nfact_photo factors at the end of season an average? Am I understanding correctly the Nfact_photo as an estimation of the N stress experienced by the plant on the season (=1 no stress, =0 complete stress)?

Thank you!

**Comment by peter-devoil** [comment]
Hi,
nfact_photo is calculated every day, so if you're reporting at harvest, then you're looking at the N stress on the final day. It does bounce around from day to day..

You can calculate an average with the tracker module, eg "average of nfact_photo on end_of_day from flowering to now as nfact_avg"
