### ISSUE TITLE
How to calibrate in APSIM

### ISSUE THREAD

**Issue by DLam1510** [APSIMInitiative/APSIMClassic#1886]
Dear Users,
I am beginner with APSIM model. I have practiced some training exercises but i do not know where to find crop parameters to calibrate the model. Anyone can help? Thanks in advance.

**Comment by BrianCollinss** [comment]
Look in the folder **C:\Program Files (x86)\APSIM{Version}\Model**. For example for wheat, there is a file named **Wheat.xml** which contains the parameters you are looking for.

**Comment by DLam1510** [comment]
Dera BrianCollinss,
Thanks for your advice. 
I understood your mean that i will adjust parameters in Wheat.xml during calibration  until the simulated values (e.g. Yield, Biomass) match well the observed values. Is that right?
If i want to calibrate water balance/ soil water content at different soil layers/nutrient balance, please tell me which and where parameters can i find to adjust?
For other models, for example WOFOST, DSSAT models, i can adjust parameters directly from the model, but it seems to be different from APSIM.
Please help  advise me the about concern.
Thanks in advance,
Dlam1510

**Comment by BrianCollinss** [comment]
Soil parameters reside in APSIM/SIM files. You can find them under "Soil" node. Just open the file in a text editor and search for Soil module.

**Comment by peter-devoil** [comment]
Hi Dlam,

The water balance parameters are set in the soil component of the GUI. You'll find a description of how to use the GUI in the exercises [here](https://www.apsim.info/support/apsim-training-manuals/apsim-training-simlesa/fallow-water-balance-simlesa/), and [here](https://www.apsim.info/support/apsim-training-manuals/fallow-water-balance/), there's also an exercise relevant to the [N module](https://www.apsim.info/support/apsim-training-manuals/the-nitrogen-cycle/). Each of these exercises introduces the functionality of apsim from a beginners perspective.

The usual procedure when simulating an experiment is to firstly describe the components of your experiment - met, soil, agronomy and genetics - that you have _measured_. If you haven't measured it, then you need to estimate it - from nearby experiments, from books if need be. If you find yourself "tweaking" a parameter to fit your data you should be concerned - are you simply guessing a parameter that you should have measured in the first place? What justification can you provide that says a fitted parameter is better than an observation?

Lastly, try not to change the xml files in your installation. It's guaranteed to make **all** of your subsequent simulations unreapeatable, as the original point of reference is lost. Make a copy of it, and use an .ini file component similar to the process described [here](https://www.apsim.info/support/apsim-training-manuals/apsim-training-simlesa/climate-change-projections/).

**Comment by DLam1510** [comment]
Hi Peter-devoil,
Thanks for your help and giving useful information.
I have a question regarding to soil water content variables in APSIM as follows: I will measure soil moisture at 3 layers beneath the top soil (0-30 cm, 30-50 cm, and 50-100 cm) at an experiment site. Could you pls. show me which variable  in Output file (Output file>component filter>soil>.....)  can be extracted to compare with the observed values? I have found some variables such as SW, SW-depth, SWCON, and SWS, but i do not know exactly which variable is used for comparing with soil moisture at different soil layers.
Thanks in advances,
DLam

**Comment by peter-devoil** [comment]
Hi DLam,

sw or sw_dep will be what you're after. The first is mm/mm, the second is mm. It will follow the same layer structure as you define in the soil water component - if your top layer is described as 0:300, then sw_dep(1) will be absolute soil water content for 0:300. sw_dep(2) will be the second, etc.

With arrays, you can sum all elements with (),  subset via (a-b) whereas &b are layer numbers. 

Mapping from one profile structure to another isnt supported in the GUI.

Some crop modellers prefer to convert absolute water content (sw, sw_dep) to a relative amount (esw - rel ll15, or esw_layr, rel crop ll) for analysis.

P

**Comment by DLam1510** [comment]
Hi Peter,
Thanks,
I do not know how to evaluate the APSIM model performance when simulating runoff curve in water balance. 
If assessing total runoff in a hydrological watershed, we can measured runoff (discharge) at the watershed outlet. Those measured values will be used to compare with simulated discharge values in order to assess the model performance.

Could you please tell me which kinds of measured data can be used to compare with runoff in APSIM model? and how to collect that data at the field (a farm level)?
Thanks in advance,
DLam

**Comment by peter-devoil** [comment]
You need a runoff plot. Perhaps more than one.. There's a lot of background chapter 3 & 7 of [here](http://www.fao.org/3/t0848e/t0848e00.htm#TopOfPage) that tries to talk you out of it. [Spatial aggregation](https://pdfs.semanticscholar.org/b293/80f489a99adc1c2a25f0b0cd1446208bf7d3.pdf) of plot level data to a farm / catchment level is the common approach, and some people have managed to [model subsurface flows](https://www.researchgate.net/profile/Zahra_Paydar/publication/237533400_Applying_a_spatial_modelling_framework_to_assess_land_use_effects_on_catchment_hydrology/links/00b49533c98d85c4a7000000.pdf).

I also remember that the runoff model is of most utility in a comparative mode, eg "what happens if I change _x_ ha to pasture (scenario b) instead of cropping (scenario a)" - which may not require the [same level of detail](https://doi.org/10.1016/S0308-521X(98)00044-4) in parameter fitting. Precise runoff  / erosion prediction is always going to be sub optimal with a daily timestep model.

**Comment by peter-devoil** [comment]
DLam - here's some supplementary information from Mark Silburn who did a lot of the initial APSIM runoff/erosion development:

Various statistics are used to evaluate model performance  ie modelled vs measured
- Get means/total the same
- Root mean square error (minimise)
- Nash-Sutcliffe R2 around one to one line – same as Mayer & butler I guess
- Visual evaluation of X-Y scatter plot valuable
- can look at daily, monthly & annual
  - cumulative runoff or soil loss useful
  - testing on other measurements (eg cover, soil water etc) is useful
  - Moriasi gives good rules

Can use optimiser (eg [PEST](http://www.pesthomepage.org/)) but better way is manual calibration – set most parameters using measured values ie:
- get crop/vegetation working eg get LAI or % green cover right, 
- get soil water holding capacity independently ie measure or estimate using equations, 
- set U and cona to published values – end up with only CN2bare and CN-red (for cover effect) unknown 
- calibrate CN2bare for bare treatments or periods and then Cn-red using data when cover is high (see Owens etal, Littleboy et al) 
- ignore tillage effects are tillage is buried in cover effect. 

[MODSIM09_cropping system_model_uncertainty_chamberlain.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910121/MODSIM09_cropping.system_model_uncertainty_chamberlain.pdf)
[EcolMod(1993)_statistical_validation_Mayer&Butler.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910122/EcolMod.1993._statistical_validation_Mayer.Butler.pdf)
[TASABE(2015)_model_performance_Moriasi_etal.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910123/TASABE.2015._model_performance_Moriasi_etal.pdf)
[AJSR34(1996)91-102 Littleboy etal India I.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910124/AJSR34.1996.91-102.Littleboy.etal.India.I.pdf)
[AJSR41(2003)_1467-1488 Owens etal pasture runoff model.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910125/AJSR41.2003._1467-1488.Owens.etal.pasture.runoff.model.pdf)
[AJSR30(1992)547-564 Silburn&Freebairn CREAMS_III_hydrology.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910126/AJSR30.1992.547-564.Silburn.Freebairn.CREAMS_III_hydrology.pdf)
[AJSR30(1992)757-774 Littleboy etal PERFECT_I.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/4910127/AJSR30.1992.757-774.Littleboy.etal.PERFECT_I.pdf)

There are a lot of books on measurement practise using various flumes and weirs
