### ISSUE TITLE
Phenology stress not responding enough

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/APSIMClassic#1887]
Adjusting Phenology response to water stress in sorghum and maize.

**Comment by JJguri** [comment]
@jbrider @hol353 I am conducting a factorial combination across environments (soil x climate x years) for different maize cultivars. The plot below shows the effect of water stress (actual evapotranspiration/potential evapotranspiration) on days from sowing to flowering. I can see how the maize model is sensible to these two factors. Could you please let me know where in the code it is described and if I can setup different stress factors by cultivar? The colours in the first figure indicate levels of N rate (ACT=41kgN/ha, ATT=100kgN/ha and POT=400kgN/ha) and in the second figure different cultivars (EE=early, LL=late).
![Pheno_stress](https://user-images.githubusercontent.com/41041705/158932185-1dba1a31-4fad-410c-ac3c-613e71812d2f.png)
![Pheno_stress2](https://user-images.githubusercontent.com/41041705/158932267-5c8cba07-771e-4342-a1d4-0ad9f5eda21c.png)

**Comment by hol353** [comment]
@JJguri Sorry but this isn't my area of expertise. I haven't used APSIM 7.10 in 5 years and I've never looked at the maize source code.

**Comment by JJguri** [comment]
> @JJguri Sorry but this isn't my area of expertise. I haven't used APSIM 7.10 in 5 years and I've never looked at the maize source code.

thanks @hol353 Maybe @peter-devoil, @HamishBrownPFR or @hut104 know?
