### ISSUE TITLE
Identification/adjustment of ending date (harvest date) for a specific crop

### ISSUE THREAD

**Issue by DLam1510** [APSIMInitiative/APSIMClassic#1889]
Dear User,
DAS is the time (days) from sowing date, but some crops (e.g. Maize) will have longer/shorter growing season in different regions. Sowing rule table in APSIM shows only start date of sowing and the crop growing period (from sowing - harvest time) seems to be set default by model.  How can i identify/change ending date (harvest date) of the growing crop season? Can anyone help and show me the option to set ending date?
Thanks in advance,
DLam

**Comment by peter-devoil** [comment]
Apsim does that bit for you... It calculates crop development from a variety of temperature functions, mostly.. See the Phenology section of this [general document on crop growth](https://www.apsim.info/apsim-model/description-of-crop-growth-and-development-framework-in-apsim-crop-models/).

If you "sow on a fixed date", apsim will sow the crop on the day you nominate.

When you tell apsim to sow in a window, it will wait until it reaches a rainfall / soil water threshold and sow the crop then. If you've ticked the "must sow" box, it will sow on the last day if the rainfall criteria haven't been met.

The same sowing rule will wait for the crop to either mature, or die - and harvest/remove the crop at that time. That time will depend on that years environment.

**Comment by DLam1510** [comment]
Hi Peter,
Thanks for your help,
I have tried to run Maize model with different Sow on a fixed date. The results of Dayaftersowing (DAS) are strongly different. Here are the list of model results:
Sow on a fixed date: 01 Feb => DAS=186 days
Sow on a fixed date: 01 Apr => DAS=210 days
Sow on a fixed date: 01 Jun => DAS=197 days
Sow on a fixed date: 01 Sep => DAS=133 days
Sow on a fixed date: 01 Nov => DAS=128 days
Do you have any comment on the above DAS results? Whether BIOMASS and YIELD are also significant changed corresponding different sowing date?
Thanks in advance,
DLam

**Comment by peter-devoil** [comment]
DAS - the sum of all phenological stages - is a convoluted calculation of thermal time, it's not a simple calendar operation. And as biomass production is largely dependant on the duration of (some) phenological stages, it will vary a lot if the duration changes. Again, the general paper above describes phenology in simple terms, should you wish to explore more detail I suggest [https://doi.org/10.1016/j.agrformet.2018.01.005](https://doi.org/10.1016/j.agrformet.2018.01.005).
