### ISSUE TITLE
Using K as fertiliser (Or K module) in a simple wheat simulation?

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1890]
Hello,

I want to integrate amounts of Potassium fertiliser into my simple wheat simulation. I would to ask you if there is a module of Potassium in APSIM or can we use the "ini" component or any other solution to put the potassium in my simulation?
PS: i found a study where a module of K is used.

Thank you 
best regards

**Comment by sarahcleary** [comment]
@GregMcLean-UQ  - can you help?

**Comment by peter-devoil** [comment]
Try @hut104

**Comment by Achraf-UM6P** [comment]
Hello,
can somebody help me in this question, please?
Thank you

**Comment by sarahcleary** [comment]
@hut104?  @APSIMInitiative/reference-panel?

**Comment by sno036** [comment]
@Achraf-UM6P  - the only reference to APSIM and K that I know of in the past was only for an old version of SWIM (in APSIM) and it did not interact with the plants. To my knowledge there is no sensitivity of any plants in APSIM to K and I don't think there ever has been, Perhaps you could you supply the paper?

**Comment by peter-devoil** [comment]
Was [this](https://doi.org/10.1016/j.fcr.2015.03.022) it?

**Comment by Achraf-UM6P** [comment]
Yes. that's the reference @peter-devoil @sno036 
https://www.sciencedirect.com/science/article/abs/pii/S0378429015001136?via%3Dihub

**Comment by sno036** [comment]
Ah well - I am then educated! Best you contact Neil.

**Comment by Achraf-UM6P** [comment]
@hut104 ? can you help?

**Comment by Keith-Pembleton** [comment]
Looks like a little hidden gem :) 
@Chloe0317  and @JJguri and I will have an interest in this as well.  We have some P x K interaction data for lucerne and maize from a collaborator in Indiana. Have set up the P part of the simulations so could also do the K part.

**Comment by hut104** [comment]
It would appear that APSIM classic has tests to ensure that the comms between the soilK model (which was a C# script) and the wheat model (which was in the plant model from memory).  However, I cannot find any operational test in version control of the full soil K model working with a wheat model.

________________________________
