### ISSUE TITLE
SoilP model default values?

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1891]
Hello,

I would like to ask you the the default values of P module in a wheat simple simulation?
Root C/P ratio?
Rate loss available?
sorption coeffiction?

Thank you
best regards

**Comment by sarahcleary** [comment]
@peter-devoil - can you help?

**Comment by peter-devoil** [comment]
@Chloe0317 may have a better idea than these sample figures:

Root C/P ratio: 200
Rate loss available: 0.2
sorption coefficient: 0.7

**Comment by Chloe0317** [comment]
Thanks @peter-devoil, I agree, though for rate loss available I have generally used 0.3.
