### ISSUE TITLE
Assigning biomass from a manager using .Set() function

### ISSUE THREAD

**Issue by para2x** [APSIMInitiative/APSIMClassic#1895]
Hi 
I was wondering if we could assign biomass to some value from inside a manager using the .Set () function.

I do have a simulation with multiple paddoks that I like to have a manager to monitor and intervene in the paddok simulations. Here is a simple example of a manager script I prepared. What I would like to be able to do is to set the value of biomass or some other crop variable from a manager in a specific paddok. I was wondering if anyone knows how to do so ?

```
using System; 
using System.Collections.Generic;
using ModelFramework; 
using CSGeneral;


public class Script 
{ 
   [Link] public Simulation MySimulation;
   
   
   private readonly Random _random = new Random();  
  
   // Generates a random number within a range.      
   public double RandomNumber(int min, int max)  {  
      return _random.Next(min, max);  
   } 

   
   [EventHandler]
   public void OnPrepare()
   {
      // START OF DAY
      foreach (Paddock paddock in MySimulation.ChildPaddocks) {
         if (paddock.FullName == "paddock2"){
            
            double biomass2 = 0;
            double biomass = 0;
            MySimulation.Get(paddock.Name + ".Maize.Biomass", out biomass);
            biomass2 = RandomNumber(0,100) + biomass ;
            MySimulation.Set(paddock.Name + ".Maize.Biomass", biomass2);

         }
      }
   
 
   }
} 

```
In return when I run my apsim simulation with the above manager script, it prints this error in the summary file.

```
                      APSIM Warning Error
                      -------------------
     No module allows a set of the variable: biomass
     Component name:
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Here is also how my simulation is setup. 
![Capture](https://user-images.githubusercontent.com/7999941/87726221-35c5fe00-c784-11ea-861f-5fb346123369.PNG)

Thank you

**Comment by peter-devoil** [comment]
This is intended - independantly setting biomass / yield / lai etc would make the models internal states inconsistent.

If this is what you really want to do; there is a Remove_biomass event that can be sent, and I suspect it doesnt check positive/negative amounts. But I doubt the plant's phenology would be very happy - it's intended to partially wind back to a juvenile state when the crop is cut/grazed.

**Comment by para2x** [comment]
@peter-devoil  Thank you for your response. This is very helpful.  
Do you think it would be possible to guide me to a solution where I could compile a version of APSIM that I could relax this restriction ?

**Comment by peter-devoil** [comment]
All the source code is here in this repository. Instructions for building are [here](https://www.apsim.info/documentation/model-documentation/developer-documentation/building-apsim-from-source/). 

I caution you against such a modification - many people have contemplated it, and realised that an internally inconsistent model (eg phenology out of sync with growth) is a modellers nightmare. Keeping internal processes in sync with arbitrary biomass addition/removal is not simple - the [current implementation](https://github.com/APSIMInitiative/APSIMClassic/blob/6752ebf19cdbdca4e4d05538015ff1dc343715b1/Model/Plant/Plant.cpp#L588) - intended for grazing-  is crude at best..

**Comment by peter-devoil** [comment]
PS - if you're growing maize (for grain), I'm afraid to say that it doesnt have a remove biomass event, unless you're using one the experimental ones in the "Non-validated" toolbox.
