### ISSUE TITLE
Effects of extreme temperatures on crop production 

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/APSIMClassic#1898]
Dear Sir/Madam

Here I have a couple of questions regarding the effects of extreme high (heat stress) and low (frost/cold shock) temperature on crop production. 

(1) Wheat and Canola: Not sure if the effects of extreme temperatures on crop production have been internally captured by these two crop models. But I do know that external empirical functions on the effects of heat stress and frost risk on these two 
crop production are available in the Management toolbox. 
 
(2) Cotton, Barley and Oats: Just wondering if the effects of extreme high and/or low temperatures on these crop production    have been considered internally by the relevant crop models in the current apsim version7.10 and Nexgen or external empirical functions are available to use.  

Hope to get you feedback at your earliest convenience!

Best regards!

Qunying  
qunying.luo@hillridge.com.au

**Comment by sarahcleary** [comment]
@peter-devoil; @GregMcLean-UQ - can you help or tag someone that can?

**Comment by BrianCollinss** [comment]
@qluo02 have a look at this for wheat: https://www.sciencedirect.com/science/article/pii/S0168192319305052

**Comment by peter-devoil** [comment]
Hi @qluo02 - most of the crop models will avoid responding to temperature extremes, so many people have written manager scripts to estimate heat/frost impacts for common crops like above. They are usually specific to regions / experiments, so aren't implemented in the model by default.

WRT cotton - you'll have to look through (hearn '94 -  https://doi.org/10.1016/0308-521X(94)90223-3) to see what it does - it's a cohorting module unlike the cereals. Barley & oats are the same codebase as wheat, so the same management code would function, though you can be assured that the sensitivity thresholds would be different..

You'd better ask in the [nextgen forum](https://github.com/APSIMInitiative/ApsimX/issues) to see what PMF is doing. I suspect it will be the same - write some manager code like the above - but before proceeding, you should check to see if grain number can be set on the fly.

P

**Comment by qluo02** [comment]
> @qluo02 have a look at this for wheat: https://www.sciencedirect.com/science/article/pii/S0168192319305052

Thanks, Brian!

**Comment by qluo02** [comment]
> Hi @qluo02 - most of the crop models will avoid responding to temperature extremes, so many people have written manager scripts to estimate heat/frost impacts for common crops like above. They are usually specific to regions / experiments, so aren't implemented in the model by default.
> 
> WRT cotton - you'll have to look through (hearn '94 - https://doi.org/10.1016/0308-521X(94)90223-3) to see what it does - it's a cohorting module unlike the cereals. Barley & oats are the same codebase as wheat, so the same management code would function, though you can be assured that the sensitivity thresholds would be different..
> 
> You'd better ask in the [nextgen forum](https://github.com/APSIMInitiative/ApsimX/issues) to see what PMF is doing. I suspect it will be the same - write some manager code like the above - but before proceeding, you should check to see if grain number can be set on the fly.
> 
> P

Thanks, Peter for your feedback!

**Comment by DavidJohnston491** [comment]
Hi qluo02.
Cotton in APSIM classic has two high temperature responses. HUCUT in the parameter list (default 40 deg C) is the upper limit for the calculation of thermal time (Degree Days). If max temperature is > HUCUT, then it is limited to the HUCUT value. This has the effect of having a ceiling on the potential accumulation of thermal time per day. It does not directly affect growth.
The other heat effect is the limit of 35 deg C (mean daily temp) for boll growth.
Minimum temperatures are controlled by BaseT (default set at 12 deg C) for thermal time or heat unit calculations, and Frost_Kill_Immediate (default 2 deg C) which will terminate a young cotton crop, or force a mature one to rapidly proceed to mature/harvest ready.
This about sums up the extreme temperature effects on the APSIM Classic Cotton model. 
(Issue #1903 has some extra details on the boll development effects)
Regards
David

**Comment by qluo02** [comment]
Thanks david for your insights regarding the representation of effects of extreme Ts on cotton production in APSIM-Cotton classic!

cheers

qunying
