### ISSUE TITLE
SummerU, Summercona, WinterU and WinterCona values in APSIM

### ISSUE THREAD

**Issue by santoshkaini** [APSIMInitiative/APSIMClassic#1899]
Hi,
I am new to APSIM and planning to model winter wheat crop. 
I am preparing APsoil file in excel now. I am wondering if someone can suggest me a literature to estimate SummerU, Summercona, WinterU and WinterCona values!
Thank you in advance.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel  - can anyone assist?

**Comment by peter-devoil** [comment]
Have a look at [this GRDC report](https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2014/03/how-much-water-is-lost-from-northern-crop-systems-by-soil-evaporation) for a start.

This [fact sheet](https://github.com/APSIMInitiative/APSIMClassic/files/4963451/fact.sheet.v2.docx) that was developed for the same project may be useful.

**Comment by santoshkaini** [comment]
Thank you @ peter-devoil
