### ISSUE TITLE
Extraction of soil organic carbon output from model.

### ISSUE THREAD

**Issue by DLam1510** [APSIMInitiative/APSIMClassic#1900]
Hi Users,
1) Anyone can help to show how to  extract the output of Soil organic carbon in different layers (kg/ha) from APSIM model. Below are several variables from the model, but i did not find which one should be chosen:
Carbon-tot (kg/ha); OC (organic carbon %);Soilp_dlt-res-c-hum (Carbon form all residuse to humic)

2) Where can i find and how can i  set initial value of fresh organic matter (FOM) in model? In the option of Soil organic matter showing only OC, FBiom, FLnert, InertC, BiomC, and HUMC, but not FOM.

Thanks in advance,
DLam

**Comment by peter-devoil** [comment]
The first two variables are state variables - in different units - use whichever you have observations for.. The last is a rate variable (ie it's got 'dlt' in it's name), and refers to the amount of C from residues being added to the soiln module.

There isn't a way to set the initial value, only the fractions you describe. You'd have to calcualte the fractions from your values.

**Comment by DLam1510** [comment]
Dear Peter,
Thanks you.
Please explain me whether Carbon-tot (kg/ha) is total carbon (organic +inorganic) or only total organic carbon?  If i would like to extract only SOC (soil organic carbon (kg/ha)), then please show me which variable?

In addition, OC is organic carbon (%). How can i change it's unit to kg/ha?
Dlam

**Comment by peter-devoil** [comment]
Hi Dlam,

If you're stuck, there's a bit of reading to be had in the [soiln documentation](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soiln/). @sno036 may have a better description of this, but apsim has a concept of inert C (which might be the same as you're thinking of as inorganic?) being specified as a fraction of the humic pool.

carbon_tot is the sum of fresh OM, humic and biomass carbon.  It includes a fraction of inert material.

OC is carbon_tot; carbon _tot (kg/ha) = oc (%) * 0.01 * 1000000 / ( 100 / (BD * thickness) )

At initialisation, the amounts of hum carbon and biom carbon in each layer are calculated from inputs (oc, Finert, Fbiom).

total carbon = Fresh Organic Matter (FOM) carbon  + organic carbon    (nb. FOM carbon is initialised via Root Weight and C:N of Roots)

**Comment by sno036** [comment]
@peter-devoil  - good description. Nothing to add here from me. For clarity the model does not consider inorganic C (e.g. carbonates) the inert C is charcoal or very very slow turnover organic C.

**Comment by peter-devoil** [comment]
Dlam, [here's an old spreadsheet](https://github.com/APSIMInitiative/APSIMClassic/files/4986267/SoilOrganicMatter.Explore.soils.example.xlsx) from a (now retired) apsim user that demonstrates the relationships amongst soil n inputs - it might be useful to you.  Note that FOM is not part of the soil Carbon pools until it decomposes so is not in the initial OC. Also it clarifies where InertC and others fit into the picture.
