### ISSUE TITLE
SQLite in system.data namespace

### ISSUE THREAD

**Issue by para2x** [APSIMInitiative/APSIMClassic#1902]
Hi APSIM team, 
For some data management purposes, I've been trying to use SQLite inside .NET managers in APSIM, but the namespace seems like doesn't exists in `system.data` namespace. I was wondering if there is any solution to that that you have tried OR if you could let me know how can I compile a version of APSIM with this namespace. I was mainly wondering in which one of the C# solutions (APSIM? BundleApsim? or CSDotNetComponentInterface?) I need to add that as a reference so it would be exposed to the .NET managers ?

Thank you

**Comment by para2x** [comment]
As an update to this question, I have tried few reference assemblies for this purpose (added to my C# manager), but unfortunately mostly they need some other references in the `System.Data` that is not available like this one:

```
     The type 'System.Data.IDataReader' is defined in an assembly that is not referenced. 
```
I would appreciate any suggestions for this issue.

**Comment by peter-devoil** [comment]
There is a "Reference" component in the management toolbox that allows you to point to the dll of the assembly you're trying to load. Then the 'using ...' statement should find it. Last time I used it, it was tricky to get dependancies correct.

Is the problem related to us still using 4.5 in classic?

**Comment by para2x** [comment]
Yes it is classic with .NET 4.5. 
Yes I tried to use the "Reference" as I mentioned but as you said it's extremely difficult to get the dependencies right.  Is there any chance you could share as an example ? as there is very little documentation about that .

Also following up on my original question, is there any way to add a reference to the manager2 solution source code and compile them so it would be always available to manager2 C# (like how `ModelFramework` and  `CSGeneral` are available to C#manager ) ?
