### ISSUE TITLE
How does APSIM Classic-Cotton accounts for heat stress?

### ISSUE THREAD

**Issue by rikebec** [APSIMInitiative/APSIMClassic#1903]
Dear APSIM-Experts,

Similar to the issue raised earlier here by qluo02, I have a question on temperature stress for plant growth, especially for cotton (calculation of biomass production, LAI and Yield): How does APSIM Classic - Cotton accounts for heat stress in calculating biomass, LAI and yield, and where can I find this information?

Studying the Hearn (1994) paper, I found the following with respect to temperature:
- In the "biomass" production part (CARCAP), temperature (stress) seems to be included through the respiration part (R), through R_FAC or T_PLANT.
- In the leaf area formation (LAI), temperature (stress) is not considered until the first square event, and then, after the first square event, it is indirectly included through vapor pressure deficit.
- And finally yield accounts for temperature stress through F_TEMP, which is a temperature stress factor and reduces potential ball growth rate (eq. 13 in the Hearn paper). Here, it seems that at 35 deg C the maximum stress is reached, and I assume that all temperatures above 35 deg will lead to the same stress factor value (i.e. a max value of 0). This would mean that on all days, with mean temp > 35 deg C there is no increase in weight of seed cotton.
Is this right?

This is what I could find in the Hearn paper but is this put as such into the code or which possible modifications were made to these assumptions? Would it be possible to modify the maximum temperature threshold of 35 deg C.?

Water stress on the other hand seems to be the more dominant stress which is affecting plant development in the Cotton model at all phenological stages. If this is true, have users of the cotton model experienced that the model overestimates plant growth/yield due to too little heat stress impacts (especially in irrigated systems where water stress is limited)?

Thank you very much for your help and kind regards,
Rike

**Comment by sarahcleary** [comment]
@APSIMInitiative/other-crops - can anyone help?  or suggest someone that can?

**Comment by m8harrison** [comment]
Not sure how it accounts for heat stress but think the Hearn 1994 paper was based on earlier experimental work (Hearn and Da Roza, 1985). This may be useful https://reader.elsevier.com/reader/sd/pii/037842908590053X?token=9EAF543C349B02A162C9742A001FF0EAAB418A9C3B7D007638AF824D516F1B3EA4BB2F9F7F73D9F6DFED25CB4AA2DB08

**Comment by DavidJohnston491** [comment]
Hello Rike,
Your analysis appears correct, but a couple of points of clarification and caution are warranted.
The APSIM-Classic Cotton is based largely on Brian Hearn's original OZCOT model and code. As such, it is primarily a fruiting dynamics driven model, not a dry matter production and HI model. Biomass was added to the APSIM version of the model, but was not the main focus. Final yield of seed cotton has always been the primary focus.
To address your main questions directly: The 35 deg C maximum mean temperature for boll development is hard coded and has never been modified to allow external user adjustment. The code ramps the F_TEMP stress indicator from 0 to 1 over the daily mean temperature range of 15 to 20 deg C and from 1 to 0 over the range 30 to 35 deg C. Put as (x temp ; y factors) value pairs: x = (15,20,30,35) ; y = (0,1,1,0). For mean daily temperatures over 35 deg C, there is no increase in boll weights.
On the issue of the LAI not being impacted by heat stress until after first square, this is correct. The region where OZCOT was developed (Narrabri NSW Australia) cotton is planted/sown in spring. Cool conditions are the concern for young crops, not extreme heat. The issue of early extreme heat has not been addressed for model refinement.
Soil Moisture Index (SMI) is a stress factor the appears in almost all growth equations in OZCOT.  Modifications made to the rooting and soil water extraction routines for APSIM 7.8 did alter the balance of water stress in some growth scenarios. This has resulted in the model overestimating yield in some irrigated situations. Adjustment of the potential root expansion rate and rooting depth can assist in correcting these over estimates.
LAI development is an area the has known problems in tropical conditions with low VPD and can affect water use and growth rates. Dr Stephen Yeates of CSIRO is collecting data to try to correct the short comings of APSIM Classic Cotton in tropical conditions, with the refinements to be included in ASPIM-NG Cotton.

I hope these details assist your research. Let me know if I might be able to assist further.
Regards
David Johnston

**Comment by rikebec** [comment]
Dear Matthew, thank your for the link to the Hearn and Da Roza (1985) paper! I will have a look into this.

Dear David, thanks a lot for the detailed clarification and information on the APSIM-Classic Cotton. Your answer was very helpful and helps me to better understand my model results. Reasons for my results became clearer. Very nice!
Thank again!

Regards
Rike
