### ISSUE TITLE
I want to create on met file with several locations within it. Is it possible? 

### ISSUE THREAD

**Issue by mariosecchi** [APSIMInitiative/APSIMClassic#1904]
I have weather data to create a met file from more than 100 locations. Do I need to create one by one? 

Is some way to create only one met file  from a raw dataset that I have in R, using the packages from: 

Package ‘APSIM’
May 22, 2019
Type Package
Title General Utility Functions for the 'Agricultural Production
Systems Simulator'
Version 0.9.3
Date 2019-05-22
Author Justin Fainges
Maintainer Dean Holzworth <Dean.Holzworth@csiro.au>

Thanks!

**Comment by sarahcleary** [comment]
@hol353

**Comment by peter-devoil** [comment]
We used to have that ability a very long time ago when the input component was written in fortran. 

Not any longer, I'm afraid - you'll have to make them one by one. Or write a met component in the c# manager.

P
