### ISSUE TITLE
soil temperature simulation

### ISSUE THREAD

**Issue by guochaoqiong** [APSIMInitiative/APSIMClassic#1906]
Hello everyone! When I simulated soil temperature, the simulated value of soil temperature in each layer was always higher than the measured value. I adjusted all kinds of water parameters and did not decrease the simulated value. How can I solve this problem?

**Comment by peter-devoil** [comment]
Has this been answered in https://github.com/APSIMInitiative/APSIMClassic/issues/1913 ?

**Comment by sno036** [comment]
Yes
