### ISSUE TITLE
Swdef-photo stress parameter calculation is different for wheat and lucerne

### ISSUE THREAD

**Issue by 20091108wl** [APSIMInitiative/APSIMClassic#1909]
I applied classic version 7.10 of APIMS-Wheat and APSIM-lucerne to simulate drouhgt effect on crop growth, according to the code discription, swdef-photo stress factor = sw_supply/sw_demand. However, When I put swdef-photo, sw_supply and sw_demand in the output, I find swdef-photo=0 when soil water supply > water demand for APSIM lucerne while swdef-photo=1 for APSIM-wheat under the same condition.  Thhus the actural daily dry mantter from photosynthsesis for wheat is calculated as: DM_actual = DM_potential * swdef-photo, while for APSIM-lucerne, it's calculated as DM_actual = DM_potential * (1-swdef-photo). Is this a bug for the model version?

**Comment by peter-devoil** [comment]
a) make sure you're reporting at the same time of day (ie end of day)

b) be sure you're asking for the sw_xxx variables from the plant, not the soil - as many of them limit calcs to root depth

Can you post your simulation files pls?

**Comment by 20091108wl** [comment]
I don't think the problem is on which day we use. My problem is about the calculation for swdef-photo. I mean when sw_supply>sw_demand, swdef=1 for wheat, but when sw_supply>sw_demand, swdef=1 for lucerne. So i am confused how it's calcualted. i have post the simualtion files and output files, you may have a look at the output file when sw_supply>sw_demand, and the related swdef-photo value in the two output files.

**Comment by 20091108wl** [comment]
![(1)](https://user-images.githubusercontent.com/61308566/89764468-05754380-db27-11ea-9d18-dc77956a5cb1.png) 
![（2)](https://user-images.githubusercontent.com/61308566/89764473-08703400-db27-11ea-9b5d-f6fe2394068e.png) 
You may calculate the value when sw_supply < sw_demand, the calculated resulets equals to (1-swdef_photo)
