### ISSUE TITLE
crop model calibration (new cultivars and new locations)

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1910]
Hello everyone, 
To calibrate a set of cultivars of a crop used in a new locations, is it sufficient to use a set of yield data (300 fields) and some fields phenological stages data (60 fields) collected during 3 successive years?
And do we calibrate the crop modele by cultivar or by location? ie, do we calibrate the model for each cultivar (each cultivars can be used in different regions of the country) or for each zone ( several cultivars are used in each zone)?
Thank you
best regards

**Comment by sarchontoulis** [comment]
i would go by cultivar. If the calibration of the cultivar parameters is robust, then the model should be able to predict phenology in other locations. Getting into yields things are getting more complicated. Do you have good soil info per location (300 fields)?

**Comment by Achraf-UM6P** [comment]
Thank you so much.
The soil info were collected from laboratory analysis and also by using some database.
I know that the use of yields data and growth stages data (zadok scale) to calibrate APSIM model for new cultivars could be not sufficient, what do you think about this?
Thank you.
Best regards

**Comment by sarchontoulis** [comment]
In general I agree. However, this depends on the crop as well, cereal vs legume, summer vs winter.

Sent from my iPhone

On Aug 31, 2020, at 8:57 PM, Achraf-UM6P <notifications@github.com> wrote:

﻿

Thank you so much.
The soil info were collected from laboratory analysis and also by using some database.
I know that the use of yields data and growth stages data (zadok scale) to calibrate APSIM model for new cultivars could be not sufficient, what do you think about this?
Thank you.
Best regards
