### ISSUE TITLE
Upscalling from field to regional scale to simulate spatial crop production

### ISSUE THREAD

**Issue by DLam1510** [APSIMInitiative/APSIMClassic#1911]
Dear Users,

APSIM is used to simulate crop production (yield and biomass) at plot/field scale. Considering a larger area (e.g. regional scale), it is necessary to couple APSIM with Agro-hydrological model with GIS interface to interpreter spatial map of crop yield. Anyone can help to point out which distributed agro-hydrological models combined with GIS interface could be the best to couple with crop model such as APSIM/ WOFOST/DAISY model?
Thanks in advance,
DLam

**Comment by peter-devoil** [comment]
The [Qld reef monitoring](https://www.reefplan.qld.gov.au/tracking-progress/paddock-to-reef) people do this regularly.
