### ISSUE TITLE
Continuous Cotton results

### ISSUE THREAD

**Issue by LTozzini** [APSIMInitiative/APSIMClassic#1912]
The simulation throw values that are not fisicaly posible in the real life, what is happening?

**Comment by sarahcleary** [comment]
@hut104 - maybe you can assist or tag someone else?

**Comment by hut104** [comment]
Sorry, I'm not familiar with the Ozcot model in APSIM classic.
If the issues are with soil values, then others may be able to help.  If the problem is with cotton, perry poulton has retired, but perhaps david johnston could help.
________________________________

**Comment by sarahcleary** [comment]
@joh491- FYI

**Comment by DavidJohnston491** [comment]
@LTozzini  - are you able to provide me with some more details, or the simulation files, please. One specific question; Is the crop terminating at a reasonable time, or failing to trigger maturity?
Thank you.

**Comment by LTozzini** [comment]
Thank you all for your responses. Im not sure how to configurate the harvest in the simulation. When you run Continuous cotton without any changes in the simulation (predetermined climate and soil) it throw values like 104000 kg of dry mass per hectarea and no balls and no seeds. How can I determinate the crop terminating time. 
regards, 
Luciana

**Comment by DavidJohnston491** [comment]
@LTozzini - are you running the Continuous Irrigated Cotton example included with APSIM Classic?  Which version of APSIM are you running?
Can you include the '.out' file from the simulation run please. If possible include a zipped file of the climate and .apsim files.
Attached is the default output file from the APSIM ver 7.10.  Yield values for years 2008 to 2010 are very high but not theoretically impossible. Adjustments to rooting may be required to reduce growth to observed values.
The harvest date is the date in the first column of the attached file. There are a number of ways to control this date. Let's start by seeing what you are working with. 
[Continuous Irrigated Cotton - deficit rule.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5062343/Continuous.Irrigated.Cotton.-.deficit.rule.zip)

Thanks.
David

**Comment by LTozzini** [comment]
Yes, im running the Continuous Irrigated Cotton example included with APSIM. I have 7.10 APSIM version. is it ok? 
I share all the files attached to you. As you can see, the simulation does not give harvest results but it does show dry matter results of almost 104 tons per hectare that do not vary over time.
I dont understan what i am doing wrong here.
regards,
Luciana
[Continuous Dryland Cotton.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5062713/Continuous.Dryland.Cotton.zip)

**Comment by LTozzini** [comment]
Sorry I made a mistake, im running the continuous dryland Cotton example, not the irrigated one

**Comment by DavidJohnston491** [comment]
My initial review indicates that it is an internationalization issue affecting the units of measurement.
The attached screen shot shows your summary file on the left and my summary file on the right.
@peter-devoil - are you able to provide advice on this? 

Regards
David
![SummaryFile_Error1](https://user-images.githubusercontent.com/47841439/90073978-9160b880-dd3d-11ea-8bea-4a21afa68a0e.PNG)

**Comment by peter-devoil** [comment]
Try changing your [region settings](https://www.windowscentral.com/how-properly-change-system-default-language-windows-10) to australian.

**Comment by hut104** [comment]
We have been checking APSIM's operation under different regional settings.  Perhaps log this as an issue and state the regional settings you are currently using and we can check our software.

________________________________

**Comment by hol430** [comment]
We have been checking apsim *next gen*'s operation under different regional settings. Old apsim has a lot of issues with different regions. Cleaning it up would be a lot of work.

**Comment by LTozzini** [comment]
Thank you all for your help. After changing the  region settings to australian I was able to run the simulation and get results.
regards,
Luciana
