### ISSUE TITLE
some questions about soil temperature

### ISSUE THREAD

**Issue by guochaoqiong** [APSIMInitiative/APSIMClassic#1913]
I found some problems when simulating soil temperature, who can explain the difference: 1, when the model does not add "soiltemperature", the variable "st" under the silt components in the output file can simulate the soil temperature of each layer, but the simulated value is generally larger than the observed value. 2, when adding "soiltemperature" to the model, the variable "st" has no output value and cannot simulate the soil temperature. 3, when adding the component "soiltemperature2" to the model, variable "st" is also no output value, but some variables under the "outputfile—variable—soiltemperature2" can simulate soil temperature. So which variable should I use has a more reasonable output value?

**Comment by peter-devoil** [comment]
There are 3 models at play here; the old ceres temperature module that is used by the N module, soiltemperature  - an anachronism that should have been deleted, & soiltemperature2 - a much better soil temperature module that provides (as you describe) a different set of outputs of the same thing.

The latter doesnt replace the former as we have never examined the N modules stability with a different temperature model. It could be that while the temperature predictions are better, the N modules behaviour worsens as it already includes biases that favour the original module. 

We expect this experiment will occur in ApsimX in the near future; and @sno036 is looking for volunteers for the very same.

**Comment by guochaoqiong** [comment]
@peter-devoil  OK，thanks，i got it
