### ISSUE TITLE
Maximum number of crop modules exhausted when using millet

### ISSUE THREAD

**Issue by BrookAnderson** [APSIMInitiative/APSIMClassic#1914]
Simulating crops like millet, APSIM simulates a main stem crop + 5 tiller crops, making a total of 6 ‘crops’.
When simulating a long term crop rotation, APSIM only has 4 'slots' for other crops. When this is exceeded, a fatal error is thrown.

                      APSIM  Fatal  Error
                      -------------------
     Too many modules with green cover.
     Component name: paddock.Soil Water

In the soil water model in APSIM 7.10, there is the parameter:

      integer    max_crops             ! maximum number of crops in at once
      parameter (max_crops = 10)

Is is possible to change the maximum number of crops to allow for long term crop rotations that include tiller crops such as Millet?

**Comment by peter-devoil** [comment]
Hey @BrookAnderson - you can get a fix for this (r4208) on the [upgrades page](https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx).

**Comment by BrookAnderson** [comment]
Hi Peter,

Thanks so much, I got it last week and all is running smoothly again!

I really appreciate all your help.

Brook
