### ISSUE TITLE
APSIM error “Can’t find last row of file."

### ISSUE THREAD

**Issue by santoshkaini** [APSIMInitiative/APSIMClassic#1916]
Hello,
![1](https://user-images.githubusercontent.com/68579750/91800167-3ccba180-ec48-11ea-9e55-2058760404e1.png)
I am a novice user to APSIM crop modeling and trying to simulate "Continuous wheat" module in APSIM.
When I try to see the graph/plot, the following error occurs:
“Can’t find last row of file: E:\file path\Continuous Wheat.out”.
The output file is empty.
Could you please suggest me how to overcome this error?
Thank you in advance.

**Comment by BrianCollinss** [comment]
Could you please upload the APSIM file and met file?

**Comment by santoshkaini** [comment]
Hi Brian,
 I kindly inform you that I have attached APSIM files in ResearchGate message as I am having difficulty to upload files in Github. I tried to upload ZIP file but I am not able.
Could you please check it.
Thank you.

**Comment by peter-devoil** [comment]
1) check your [regionalisation settings](https://support.microsoft.com/en-us/office/change-the-windows-regional-settings-to-modify-the-appearance-of-some-data-types-edf41006-f6e2-4360-bc1b-30e9e8a54989) are similar to australia
2) Is there a message in the summary file showing any error?

**Comment by BrianCollinss** [comment]
![image](https://user-images.githubusercontent.com/39573622/91960049-c1074d00-ed4c-11ea-9260-e558b2d3d2e8.png)
[Downloads.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5161082/Downloads.zip)

I think it would be helpful if you have a look at a couple of example files and the sample managers in the toolbox. 

You had made a couple of mistakes:

- You did not force APSIM to plant if the sowing rules were not satisfied (Must Sow = yeas).
- You did not select a cultivar (for example, Axe or Hartog).

**Comment by santoshkaini** [comment]
Thank you, Brian.

**Comment by BrianCollinss** [comment]
No worries. If your problem has been addressed, you can close the issue.
