### ISSUE TITLE
Nitrogen stress still affects phenology

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1918]
@peter-devoil @hut104 
According to APSIM-wheat document:

> In the current released version, soil water, nitrogen and phosphorus stresses have no effect on phenological
> development (i.e. parameters fW_pheno = fP_pheno = 1 Equation 94, and fN_pheno has values typically above 1
> Equation 106)

APSIM tries to keep the value of **nFact.pheno** above 1 (by multiplying it by 100) to make N stress ineffective on phenology. However, when **stem N concentration** is below **minimum N concentration** and the division in Equation 106 is negative, **nFact.pheno** will be zero and phenology starts stalling. This happens under very low N conditions.

This can be changed by adding:
`result = 1.0;`
after the line:
`result = bound(result, 0.0, 1.0);
`
Unless a more elegant solution exists.

```
float NStress::critNFactor(vector< plantPart *> &parts, float multiplier)
//=======================================================================================
//   Calculate Nitrogen stress factor from a bunch of parts
/*  Purpose
*   The concentration of Nitrogen in plant parts is used to derive a Nitrogen stress index
*   for many processes. This stress index is calculated from today's relative nutitional
*   status between a critical and minimum Nitrogen concentration.
*/
   {
   vector< plantPart *>::iterator part;

   float dm = 0.0, N = 0.0;
   for (part = parts.begin(); part != parts.end(); part++)
      {
      dm += (*part)->Green.DM();
      N += (*part)->Green.N();
      }

   if (dm > 0.0)
      {
      float N_conc = (float)divide (N, dm, 0.0);

      // calculate critical N concentrations
      float N_crit = 0.0;
      for (part = parts.begin(); part != parts.end(); part++)
          N_crit += (*part)->nCrit();

      float N_conc_crit = (float)divide (N_crit, dm, 0.0);

      // calculate minimum N concentrations
      float N_min = 0.0;
      for (part = parts.begin(); part != parts.end(); part++)
         N_min += (*part)->nMin();

      float N_conc_min = (float)divide (N_min, dm, 0.0);

      //calculate shortfall in N concentrations
      float dividend =  N_conc - N_conc_min;
      float divisor =   N_conc_crit - N_conc_min;
      float result = (float)(multiplier * divide (dividend, divisor, 1.0));
      result = bound(result, 0.0, 1.0);
	  result = 1.0;
      return (result);
      }
   else
      return (1.0);
   }
```

**Comment by peter-devoil** [comment]
That would stop _any_ N stress? Surely it would better to 1) throw a fatal error if crit < min; 2) change N_fact_pheno into a stick function so you can describe its limits.

**Comment by BrianCollinss** [comment]
Thanks Peter. What do you mean by stick function?

**Comment by peter-devoil** [comment]
an interpolationFunction().

**Comment by docalexwu** [comment]
> However, when **Critical N concentration** is below **stem N concentration**

Brian, I think this is mean to say when **organ N concentration** is below **minimum organ N concentration**.
The suggested change would strictly stop N stress on phenology (and nothing else).

I checked crit is always greater than min for stem and leaf - this what's in the wheat.xml.

**Comment by BrianCollinss** [comment]
@docalexwu then how come the division becomes zero or negative (then bound to be between 0-1)?

**Comment by docalexwu** [comment]
If **organ N concentration** is below **minimum organ N concentration** you get negative dividend

float dividend =  N_conc - N_conc_min;

This can happen under really low N when biomass initially increases.

**Comment by peter-devoil** [comment]
The approach in that PR isn't a good idea, brian. Overall - remember that the plant module implements a lot of crops other than wheat; and the code inside should be generic for all crops; if there is a specialisation, it should be in the ini file and not the code. So you don't want code like "... if module name == wheat" or whatever. What happens if somebody renames their wheat module to "durum"?

Secondly, if the situation occurs where n_conc < min; then some routine has made an error earlier by allocating less N than it should. Better to fix that, and throw an error if the condition is found. Even so, the bound check would fix it. 

Third; critNFactor is called for other stresses (photo & grain).

**Comment by BrianCollinss** [comment]
Thanks @peter-devoil. You're right. I found out that **critNFactor** was used for other purposes so I came up with this new thing. 

I have never manipulated the ini file (I think if it is absent, APSIM will use, for example, Wheat.xml?) so I have no idea how to implement it. @docalexwu has found a rare problem under low-N conditions which causes the crop to stop developing. 

As it is very difficult and time-consuming to trace calculations in APSIM, we may decide to have a sub-version for our job instead of pushing it to GitHub. Cheers.

**Comment by peter-devoil** [comment]
Sorry - .ini files became .xml files a long time ago - so the right place for this is in Wheat.xml

Yes - it's difficult to trace these calculations - they're obfuscated unless you're intimate with the class heirarchy & event patterns.
