### ISSUE TITLE
Different met files for different paddoks

### ISSUE THREAD

**Issue by para2x** [APSIMInitiative/APSIMClassic#1921]
Hello APSIM team,

I'm trying to assign a unique met file to each paddok in a multi paddoks simulations to account for variability in driving forces. Something like this (met1 for paddok1 and etc):

I was wondering if that is possible ? Thank you

![image](https://user-images.githubusercontent.com/7999941/92036124-61ea0e00-ed35-11ea-84d0-6df7434fe5ee.png)

**Comment by peter-devoil** [comment]
You could *try* dropping each metfile into the associated paddock instead of the top level, but I would not like to guarantee your success.. Let us know how it goes.
P

**Comment by para2x** [comment]
It actually worked ! 
Thanks for the quick response !
