### ISSUE TITLE
APSIM classic and R

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1922]
Hello everyone,

Can i ask you some documents (user guide or books)  that introduce the use of APSIM classic in R?

Thank you
best regards

**Comment by peter-devoil** [comment]
I'm unaware of any guides/books specific to apsim - most users keep a handy collection of scripts, combined with libraries.

Is your interest in building simulations (via xml), or analysing output?

**Comment by Achraf-UM6P** [comment]
i m interested in building simulation via xml, and more specific, i need to use APSIM in R to calibrate cultivar parameters via a itterative optimisation using bayesian techniques?

**Comment by hol430** [comment]
You could try [this package](https://github.com/femiguez/apsimx), I'm pretty sure it includes support for old apsim, and for editing .apsim files.

**Comment by peter-devoil** [comment]
Seconded. I'd recommend staying with the xml2 package in R that it uses.

You may be troubled by file formats - apsim classic has .apsim files and .sim files - both are xml formatted. A .apsim file is a general outline of the simulation, a .sim file contains all the extra inputs (eg cultivar info) and is more constrained. 

.apsim files are easier to deal with, though a little slower to run.
