### ISSUE TITLE
i want to know how to get a one year rotation with a fallow followed by a winter wheat crop then a summer maize  crop in the first year,and in a long term simulation.

### ISSUE THREAD

**Issue by 13984489258** [APSIMInitiative/APSIMClassic#1923]

**Comment by 13984489258** [comment]
Winter wheat was planted in early October, the next year in early June to harvesting  , Summer maize  in early June and early October next year , so I can not use fallow, so how should I set up a simulation.

**Comment by peter-devoil** [comment]
This [training material](https://www.apsim.info/support/apsim-training-manuals/crop-rotations-in-apsim/) has a demonstration of the crop rotation component. 

Note that where it talks about "fallow" it really means "some period if time when no crop is in the ground".

**Comment by peter-devoil** [comment]
To clarify, if you're simulating an existing field experiment, then you can use the operations schedule to specify when the crop is sown & harvested. You can also specify the dates of fertiliser applications and tillage operations (note that by default, straw residues are sent directly to the surface OM pool at harvest, and gradually decompose - tillage operations will speed that decomposition up).

The dynamic planting rules in the training material are used when we wish to run a simulation over a some arbitrary period of time - replicating the "manager" of the farm. The dynamic rules will respond to the plant's physiological state (eg harvesting when mature), wheras the fixed rules of an operations schedule will not.
