### ISSUE TITLE
Phosphorus componenet in APSIM classic

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1924]
Hello,
I did a soil test in the lab with a complex sample extracted from a 60 cm soil layer and i found that the P available = 40 mg / kg (ppm).
In the simulation, in the phosphorus componenet, I have three layers 0-15 15-30 and 30-60, so I give the value of 40ppm to each layer but I find a value at the top which makes the sum of the 3 layers and it is written in red 120 ppm. so i didn't understand this value at the top and does it make sense to sum the 3 values.

thank you
best regards

**Comment by peter-devoil** [comment]
This looks like a mis-interpretation - possibly a bug. The original use case was to describe total kg/ha of N, and subsequently the layered units were modified to allow ppm N. Then the same GUI form was applied to P. 

Either way, the total you're looking at is only presented in the GUI as an informative guide - and not used by the model, so I think you're quite sensible to ignore it.
