### ISSUE TITLE
APSIM calibration

### ISSUE THREAD

**Issue by santoshkaini** [APSIMInitiative/APSIMClassic#1925]
I am a novice user to APSIM crop modelling and trying to simulate “Continuous wheat” module in APSIM. 
I am trying to calibrate APSIM with simulated/measured wheat yield. 
What is the common procedure for APSIM calibration?
Is there any tool/software available for APSIM calibration (like SWAT-CUP for SWAT)? 
Thank you in advance.

**Comment by sarahcleary** [comment]
[Apsim debug.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/5337565/Apsim.debug.pdf)

Hopefully this powerpoint will assist.  

If you still have questions, can you please provide some further information:

•	What is your target environment? There may be calibrated cultivars/soils for the target environment, so you may start from this. 
•	What kind of data do you have and what is the goal? We may provide an example publication 
•	There are some optimization tools, PEST software, the soybean phenology R optimizer, others, but the majority of APSIM calibrations are based on the attached presentation (manual calibration). Use of optimizers is not a standard approach in APSIM as is in SWAT.

**Comment by peter-devoil** [comment]
That's a great pdf to have around. When @jwhish gets back from holidays, we should do something more with it - perhaps a page or video in the training materials.

**Comment by santoshkaini** [comment]
The pdf file is very useful. A video describing it would be more helpful.

**Comment by peter-devoil** [comment]
Hi - we found an old archive (from 2014) with an informative video - https://www.youtube.com/watch?v=VJ3jqgUzKRs
