### ISSUE TITLE
Using and structure of observed data files

### ISSUE THREAD

**Issue by JNGH** [APSIMInitiative/APSIMClassic#1927]
I need to point some users to the documentation for format and using observed data files in APSIMUI graphs. I can't find it any longer on the APSIM site. Please tell me where it is located.

**Comment by peter-devoil** [comment]
I cant remember any documentation, though it may have been mentioned in one of the training modules, eg the [soil evaporation experiment](https://www.apsim.info/support/apsim-training-manuals/scenario-kingsthorpe-soil-water-evaporation-project/). I've always looked for "whatever worked last time" - so any of the validation plots would have a) the data, and b) working components that use it.

**Comment by sarahcleary** [comment]
is this what you are looking for?  https://www.apsim.info/support/apsim-training-manuals/add-soils-in-a-par-file-to-a-toolbox/ or this https://www.apsim.info/support/apsim-training-manuals/evaluating-a-cropping-system/

**Comment by JNGH** [comment]
Thanks Sarah and Pete. Pete's link is the closest for observed files and should do the job for novices.
