### ISSUE TITLE
Which parameter in wheat.xml file is sensitive for wheat plant height growth in APSIM?

### ISSUE THREAD

**Issue by santoshkaini** [APSIMInitiative/APSIMClassic#1931]
I am a novice user to APSIM crop modelling and trying to simulate “Continuous wheat” module in APSIM. 
I am trying to calibrate APSIM with simulated/measured wheat yield. 
**Simulated plant height is very low compared to measured height. Could you please tell me which parameter in wheat.xml file is sensitive for plant height growth?** 
Thank you in advance.

**Comment by peter-devoil** [comment]
Search it for "x_stem_wt" and "y_height" - a stick function relating height to stem weight.

As height is only used by the canopy module to determine shading of other modules, it's not a very interesting parameter.. For calibration, your key points are a) flowering time, b) peak LAI & biomass, and c) grain filling duration.

**Comment by santoshkaini** [comment]
Yes, plant height is sensitive to x_stem_wt. 
It works. 
Thank you, Peter.
