### ISSUE TITLE
running APSIM in batch mode

### ISSUE THREAD

**Issue by VGPChimonyo** [APSIMInitiative/APSIMClassic#1932]
Hi everyone, does anyone know how I can run APSIM in batch mode. Can anyone share the literature or manual? I have access to gridded weather and soil

**Comment by peter-devoil** [comment]
Hi,
You certainly can. After you've constructed simulation files, Apsim.exe is the "top level" command line application that will run simulations in parallel. 

Its usage is flexible:
`Apsim.exe abc.apsim`  - runs all simulations in the .apsim file  
`Apsim.exe abc.apsim def.apsim ... xyz.apsim` - or many files
`Apsim.exe @filename` - reads the same arguments as above from a file
`Apsim.exe abc.apsim Simulation=/xml/path/to/sim` - run a single simulation in the .apsim file  
`Apsim.exe abc.apsim Simulation=@filename` - reads paths to simulations from a file

The "create bundle" button in the gui will pack up batch files to run remotely on a cluster - you may be able to adapt these - or the [code that generates them](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/ApsimFile/RunCondorJob.cs) - to your situation.

P
