### ISSUE TITLE
Simple grazing model

### ISSUE THREAD

**Issue by 20091108wl** [APSIMInitiative/APSIMClassic#1934]
Do we have a description for  Simple grazing model? For example, what's the meaning of each abbreviations and how the calculation algrithoms were developed? Thanks

**Comment by peter-devoil** [comment]
It's a port of the grasp grazing module first described by Rickert in 1982 - see the animal submodule in [chapter 3 of this book](https://www.cabi.org/cabebooks/ebook/20003011930). It's very simple - just tell it a potential growth rate (xxx_lwg), and it limits growth by feed deficit.
