### ISSUE TITLE
Cannot run APSIM examples

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1938]
I'm trying to run Continuous Wheat with SWIM3 in the APSIM example, but the it says "Error: Access to the path' C:\Program Files (x86)\APSIM710-r4207\Examples\Continuous Wheat with SWIM3.apsim" is denied. Trying saving in a different location. The same errors are observed for all example apsim files. Does anyone know how to solve this problem?

**Comment by BrianCollinss** [comment]
Usually when you try to run examples, APSIM interface prompts you to save a copy of the file somewhere and then run it. Have you done that?

**Comment by KeLiu7** [comment]
> Usually when you try to run examples, APSIM interface prompts you to save a copy of the file somewhere and then run it. Have you done that?

Thanks. I'm using APSIM v7.10 not APSIM Next generation. Still need to save a copy?

**Comment by BrianCollinss** [comment]
Yes

**Comment by KeLiu7** [comment]
> Yes

Should I only copy examples files or the whole APSIM file?

> Yes

Thanks. I just copied the whole APSIM file to another place. I can run examples simulations now. But do you know why this happened? I remember I can run APSIM examples directly without copying it to another place a few weeks ago.

**Comment by BrianCollinss** [comment]
I am not sure what you mean by example files or apsim files. If you need to run Continuous Wheat.apsim, just copy that somewhere else, open it in the interface and run it.

**Comment by peter-devoil** [comment]
In the GUI, pressing the "New" button points you to the example simulations in the installation directory. When you save it, give it a new location that you can write to. The met (and other) files are still found in the installation. Try to keep your installation intact so that your work is not lost when upgrading.
