### ISSUE TITLE
Irrigation on event cannot be used in SWIM3 module

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1940]
Does anyone know why APSIM cannot run with "irrigation on event" if soil module is SWIM3?

I would like to set automatic irrigation at sowing so that crop emergence soon after they are sown but APSIM wheat tells an error like the below:

APSIM  Fatal  Error
                      -------------------
     Cannot find [Link] for type: Irrigation  in object: Script
     Component name: Irrigate on event"

**Comment by peter-devoil** [comment]
Do you have an irrigation module in the simulation? That message is from the infrastructure saying it can't find a module by name or type.

**Comment by KeLiu7** [comment]
> Do you have an irrigation module in the simulation? That message is from the infrastructure saying it can't find a module by name or type.

Yes. I do have the irrigation module in the simulation. It says "Irrigation has been specified for an already processed time period
     Component name: paddock.SWIM
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         
Irrigating with 15mm due to barley.sowing event.


 
![image](https://user-images.githubusercontent.com/72141690/97241110-0f0b6f00-182b-11eb-8205-81f0750196fa.png)

**Comment by peter-devoil** [comment]
These are different error messages - can you post the simulation that is giving you grief please?

**Comment by KeLiu7** [comment]
[Russia.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5442175/Russia.zip)

Thanks. You can run this first simulation.

**Comment by peter-devoil** [comment]
Ok, swim seems to want another parameter in the irrigation message being sent from the irrigation module. I've no idea why. Can you add a line to the irrigation manager script to irrigate at midnight:

![image](https://user-images.githubusercontent.com/1924386/97246914-42112b00-184a-11eb-817f-331ad4a038ef.png)


Secondly, if you want to use a different .ini file for soils, you should use the Plugin component (/standard/Structural/Plugins): turn off the system supplied Soil.xml, and add a your customised one.

[Irr.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5442415/Irr.zip)

**Comment by KeLiu7** [comment]
> These are different error messages - can you post the simulation that is giving you grief please?



> Ok, swim seems to want another parameter in the irrigation message being sent from the irrigation module. I've no idea why. Can you add a line to the irrigation manager script to irrigate at midnight:
> 
> ![image](https://user-images.githubusercontent.com/1924386/97246914-42112b00-184a-11eb-817f-331ad4a038ef.png)
> 
> Secondly, if you want to use a different .ini file for soils, you should use the Plugin component (/standard/Structural/Plugins): turn off the system supplied Soil.xml, and add a your customised one.
> 
> [Irr.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5442415/Irr.zip)

Thank you very much. I have added the line "data.time = "24:00";" into irrigation manager script and added the customised soil ini into the Plugins. My simulations now run well! 

I also noticed you have added another "irrigate at sowing" in the manager, should I also keep this or only keep Irrigate on event?

**Comment by peter-devoil** [comment]
The second manager was an experiment to see if the old style manager behaved differently. One sends structures, the other variants. They behave the same.

**Comment by KeLiu7** [comment]
Thank you very much. I will keep both of them.

**Comment by peter-devoil** [comment]
FYI; variants are what we used to pass structured data around in the 1st iteration of the CMP (Common Modelling Protocol). They are inefficient (each variant needs to be unpacked before usage), prone to breaking over type incompatibilies, so in the late noughties, we had another go - passing defined structures like you see in the manager2 script. The old manager1 script interpreter had some translators "under the hood" that sometimes misbehave, eg uninitialised strings. 

In this case I wondered if that translator had any quirks that aren't in manager2.
