### ISSUE TITLE
Is it possible to run APSIM simulation for the soil parameters accepted in Russia?

### ISSUE THREAD

**Issue by painchetotam** [APSIMInitiative/APSIMClassic#1941]
Greetings. I'm a student from Russia. I want to use APSIM-Wheat module to simulate wheat yield and try different climatic scenarios, but I've ran into one major issue. The measurements and parameters of soil, water and culture are not from our country's agrochemical system. So how can I convert given parameters to needed(except by recoding the source code by myself)?

**Comment by peter-devoil** [comment]
Yes, it's a common theme when users from a different disciplines come to use apsim - many users immediately build libraries of pedotransfer functions to translate existing data. Our best description is in the [soil matters handbook](https://www.apsim.info/wp-content/uploads/2019/10/Soil-matters.pdf), [this guide](https://www.apsim.info/wp-content/uploads/2019/10/Parameters-for-soil-water-Ver24.pdf) may be helpful too.

Note that SI units have been used throughout apsim.
