### ISSUE TITLE
 Entering Climate Data

### ISSUE THREAD

**Issue by Brunomcosmo** [APSIMInitiative/APSIMClassic#1945]
I would like to ask a question regarding the APSIM Classic. I tried to carry out some simulations for sugarcane. However, when entering the climatic data, I obtained the images below:

![image](https://user-images.githubusercontent.com/73708142/97722884-ee048180-1aa9-11eb-820d-890f0619f1b4.png)
![image (1)](https://user-images.githubusercontent.com/73708142/97722914-f361cc00-1aa9-11eb-8982-a4f601da9fae.png)
![image (2)](https://user-images.githubusercontent.com/73708142/97722931-f6f55300-1aa9-11eb-8e0e-9ebc6e8c8791.png)
![image (3)](https://user-images.githubusercontent.com/73708142/97722947-f957ad00-1aa9-11eb-8867-b74bfe73cf3b.png)

The values obtained in the images are much higher than the actual values entered (temperatures of 300ºC, for example). However, when performing a simulation, the responses generated were consistent with reality.

In this case, I would like to know if this occurrence is normal for the program, or could cause an error in the simulations. If it generates errors, how to proceed to correct the problem?
Thanks in advance.

**Comment by BrianCollinss** [comment]
It could stem from your system locale. Does your current setting use '.' as decimal or ','?

**Comment by Brunomcosmo** [comment]
The system uses "," (Portuguese - Brazil), however, the data was formatted for ".", but as I said the simulation results were consistent.

**Comment by BrianCollinss** [comment]
If you change the locale to English and the problem still exists, it means the interfaces cannot handle the locale issue, but model.exe can.
