### ISSUE TITLE
How does APSIM deal with thinner top soil layer regarding evap?

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/APSIMClassic#1946]
Hi there,

We are looking to use APSIM to simulate deep sowing opportunities by looking at soil water in different depths (i.e. different soil layers) particularly the top 15 cm. However, we noticed that if we use 5 cm layers from 0 to 20 (0-5, 5-10, 10-15, and 15-20 cm) opposed to 10 cm layers (0-10 and 10-20 cm) the soil water behaves drastically different. With thinner layers the top layer dries much quicker and we would like to know if this is backed up by data or would be a potential issue with the model itself and how it deals with evaporation in the top layer.

Cheers,

**Comment by peter-devoil** [comment]
Yes, soilwat only evaporates from the top layer and will do odd things with thin (  <10cm) layers. If you aren't getting enough resupply to the top layer, you could experiment with the diffusivity parameters, but you would most likely make a bad problem worse. The water balance used to have an implicit assumption that layer thickness reflected the soil characteristics; with the advent of NMM coring it was much easier to run the model on those same measurement layers. 

Swim (richards eqn) doesnt have this restriction.
