### ISSUE TITLE
how to  calibrate  sws ,the  simulated value is higher

### ISSUE THREAD

**Issue by 13984489258** [APSIMInitiative/APSIMClassic#1947]
Hi there,

We are looking to use APSIM to calibrate soil water in different depths    (i.e. 0-30.30-60.60-90 cm  soil layers) particularly the top 15 cm. However, the  simulated value is higher.and i adjust SWCON and MWCON. I change those values ,and the sws change a little ,and higher than the observed values ,What shou l do ?
![image](https://user-images.githubusercontent.com/66007195/97890859-02c26d00-1d69-11eb-964b-442d63bf723b.png)

Cheers,

**Comment by 13984489258** [comment]
Depth  SWCON  MWCON 
0-30 | 1.000 | 1.000
-- | -- | --
30-60 | 0.800 | 0.800
60-90 | 0.600 | 0.700
90-120 | 0.600 | 0.500
120-150 | 0.200 | 0.400
150-180 | 0.100 | 0.400
180-200 | 0.100 | 0.400

**Comment by peter-devoil** [comment]
swcon is the rate of drainage - the rate that water moves when water content is above dul. Setting a layer to 1.0 says that the layer will drain down to DUL within one day, which is probably a bit unreasonable. 

Check out https://www.apsim.info/wp-content/uploads/2019/10/Parameters-for-soil-water-Ver24.pdf for a detailed description of model parameters.

**Comment by 13984489258** [comment]
So you mean that i should set  the fraction of water above DUL that moves daily to the next soil layer as follows: 
Clays=0.3 ,because my soil is clay? Although i set the first layer to 1.0 ,the simulated values are higher.  And  how do i set MWCON .
![Uploading image.png…]()

**Comment by peter-devoil** [comment]
a) I wouldnt use mwcon unless you're trying to model a rice paddy,
b) "simulated values" - I'm not clear here - can you tell us more about the data?

**Comment by 13984489258** [comment]
I model a wheat and maize paddy ,you mean that i do not need the MWCON ,but i do not have the KS data , so think i should use MWCON,My data is as fallow 👍 

phase | &treatment | level | layer_code | layer | Observed | Simulated
-- | -- | -- | -- | -- | -- | --
jointing_ date | 1 | L | x | 30 | 0.201 | 0.251
jointing_ date | 1 | L | y | 60 | 0.283 | 0.279
jointing_ date | 1 | L | z | 90 | 0.372 | 0.313
jointing_ date | 2 | L | x | 30 | 0.153 | 0.206
jointing_ date | 2 | L | y | 60 | 0.286 | 0.231
jointing_ date | 2 | L | z | 90 | 0.361 | 0.271
jointing_ date | 3 | L | x | 30 | 0.144 | 0.206
jointing_ date | 3 | L | y | 60 | 0.231 | 0.231
jointing_ date | 3 | L | z | 90 | 0.342 | 0.271
jointing_ date | 4 | L | x | 30 | 0.143 | 0.218
jointing_ date | 4 | L | y | 60 | 0.261 | 0.244
jointing_ date | 4 | L | z | 90 | 0.382 | 0.285
jointing_ date | 5 | L | x | 30 | 0.159 | 0.218
jointing_ date | 5 | L | y | 60 | 0.246 | 0.244
jointing_ date | 5 | L | z | 90 | 0.360 | 0.285
flowering _date | 1 | L | x | 30 | 0.227 | 0.235
flowering _date | 1 | L | y | 60 | 0.291 | 0.287
flowering _date | 1 | L | z | 90 | 0.385 | 0.308
flowering _date | 2 | L | x | 30 | 0.151 | 0.213
flowering _date | 2 | L | y | 60 | 0.228 | 0.262
flowering _date | 2 | L | z | 90 | 0.352 | 0.285
flowering _date | 3 | L | x | 30 | 0.155 | 0.213
flowering _date | 3 | L | y | 60 | 0.224 | 0.262
flowering _date | 3 | L | z | 90 | 0.351 | 0.285
flowering _date | 4 | L | x | 30 | 0.155 | 0.213
flowering _date | 4 | L | y | 60 | 0.237 | 0.262
flowering _date | 4 | L | z | 90 | 0.332 | 0.285
flowering _date | 5 | L | x | 30 | 0.154 | 0.215
flowering _date | 5 | L | y | 60 | 0.220 | 0.264
flowering _date | 5 | L | z | 90 | 0.342 | 0.287
maturity_date | 1 | L | x | 30 | 0.155 | 0.238
maturity_date | 1 | L | y | 60 | 0.129 | 0.306
maturity_date | 1 | L | z | 90 | 0.149 | 0.326
maturity_date | 2 | L | x | 30 | 0.097 | 0.188
maturity_date | 2 | L | y | 60 | 0.151 | 0.244
maturity_date | 2 | L | z | 90 | 0.244 | 0.269
maturity_date | 3 | L | x | 30 | 0.116 | 0.188
maturity_date | 3 | L | y | 60 | 0.133 | 0.244
maturity_date | 3 | L | z | 90 | 0.155 | 0.269
maturity_date | 4 | L | x | 30 | 0.123 | 0.188
maturity_date | 4 | L | y | 60 | 0.308 | 0.244
maturity_date | 4 | L | z | 90 | 0.241 | 0.269
maturity_date | 5 | L | x | 30 | 0.224 | 0.198
maturity_date | 5 | L | y | 60 | 0.210 | 0.259
maturity_date | 5 | L | z | 90 | 0.249 | 0.283

**Comment by 13984489258** [comment]
![image](https://user-images.githubusercontent.com/66007195/97959496-6fca1700-1dea-11eb-9c19-ebca2a1a93fa.png)
and this is my water data

**Comment by sarahcleary** [comment]
@peter-devoil ??

**Comment by sarahcleary** [comment]
@13984489258 - is this question still outstanding?
