### ISSUE TITLE
APSIM Error

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1952]
When I run APSIM-Balrey, it says errors as below. Does anyone know how to solve this problem?    

                  APSIM  Fatal  Error
                      -------------------
     The module SurfaceOrganicMatter has asked for the value of the variable eos.
     It received no responses.
     Component name: paddock.SurfaceOrganicMatter
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by peter-devoil** [comment]
Do you have the soil in the paddock, or top level simulation node? Al soilish components are sensitive to placement.

**Comment by BrianCollinss** [comment]
Hi @KeLiu7 . Was the error in your simlation related to absense of the soil node? I am getting the same error, but only on Linux and I do have a soil node.
