### ISSUE TITLE
Cannot Reset water, nitrogen, surfaceOM and phosphorus on sowing

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1953]
[Test1.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5516317/Test1.zip)

I have attached Sims there. My simulations go wrong with such reset fuction at sowing. Does anyone know to solve this problem? Many thanks.

**Comment by BrianCollinss** [comment]
Would be helpful if you copy the error message you get.

**Comment by peter-devoil** [comment]
Have a look in your summary file for any suspicious messages. Have you specified the name of your soil module in the reset component?

**Comment by KeLiu7** [comment]
> Would be helpful if you copy here the error message you get.

 APSIM  Fatal  Error
                      -------------------
     The module " water" does not exist.
     Command: ' water' reset
     Component name: paddock.Reset water, nitrogen, surfaceOM and phosphorus on sowing
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by KeLiu7** [comment]
> Have a look in your summary file for any suspicious messages. Have you specified the name of your soil module in the reset component?

Yes. I put Soil there but still get error.

![image](https://user-images.githubusercontent.com/72141690/98763561-352d3380-2415-11eb-9d3b-07024f44c6ec.png)

**Comment by peter-devoil** [comment]
The same error appears in the summary file?

**Comment by KeLiu7** [comment]
> The same error appears in the summary file?

Yes.

![image](https://user-images.githubusercontent.com/72141690/98772558-f18cf680-2421-11eb-8c16-7535cb92d567.png)

**Comment by peter-devoil** [comment]
Ah. Swim isnt called water, which the manager code assumes. In the manager component, change the bit 

    if (resetWater = 'yes') then
          '[soilmodule] Water' reset
    endif
to

    if (resetWater = 'yes') then
          '[soilmodule] SWIM' reset
    endif

**Comment by KeLiu7** [comment]
> Ah. Swim isnt called water, which the manager code assumes. In the manager component, change the bit
> 
> ```
> if (resetWater = 'yes') then
>       '[soilmodule] Water' reset
> endif
> ```
> 
> to
> 
> ```
> if (resetWater = 'yes') then
>       '[soilmodule] SWIM' reset
> endif
> ```

Thanks but still not working there... 
![image](https://user-images.githubusercontent.com/72141690/98774977-146dd980-2427-11eb-93f4-0212f2966ef5.png)

**Comment by peter-devoil** [comment]
Oops. Just the word SWIM - no quotes or brackety bits... Sorry

    if (resetWater = 'yes') then
      SWIM reset
    endif

**Comment by KeLiu7** [comment]
> Oops. Just the word SWIM - no quotes or brackety bits... Sorry
> 
> ```
> if (resetWater = 'yes') then
>   SWIM reset
> endif
> ```

Cool! Thank you P!!!
