### ISSUE TITLE
How to output the ratio of two variables in APSIM-Barley?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1954]
For example, I would like to observe the water supply/demand ratio under long-term simulations, Water supply (sw_supply) and water demand (sw_demand) can be found in Barley component. 

Does anyone know how to output the value of water supply/demand ratio directly rather than output water supply and demand then calculate them? I have attached my SIMs there. Thank you very much.
 
[Test.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5528790/Test.zip)

**Comment by BrianCollinss** [comment]
You can add it to a manager script. You already have **FrostandHeat** manager script. If you look at the way variables are initiated (in **init** tab), and are later calculated (in **start_of_day** or **start_of_day** tab), you will know how to do it.

**Comment by KeLiu7** [comment]
> You can add it to a manager script. You already have **FrostandHeat** manager script. If you look at the way variables are initiated (in **init** tab), and are later calculated (in **start_of_day** or **start_of_day** tab), you will know how to do it.

Thanks. Already solved.

**Comment by KeLiu7** [comment]
> You can add it to a manager script. You already have **FrostandHeat** manager script. If you look at the way variables are initiated (in **init** tab), and are later calculated (in **start_of_day** or **start_of_day** tab), you will know how to do it.

But could you please tell me why do we need to define variable as 1 or 0 in the ini tab first? Why this case?  Thanks.

**Comment by BrianCollinss** [comment]
Variables need to be initiated first. It does not matter what value you give them. But zero is a safe choice. Also, some variables need to be reset (set 0) at the beginning of each day and then be re-calculated at the end of the day.

**Comment by KeLiu7** [comment]
Thanks, Brian.
