### ISSUE TITLE
reinitialize nitrogen and surfaceOM every year

### ISSUE THREAD

**Issue by ckluss** [APSIMInitiative/APSIMClassic#1955]
Hi,

we like to parameterise the soil nitrogen and SOM differently in **every year**. 
(so no reset on fixed date (from Management (common taks)) but **set new values** on fixed date)

The background: we have a crop rotation that contains maize and want to start with simulating only maize. So we have something like 10 years maize mono but with different initialised soil parameters in each year.

We are happy about every idea, so far we make 10 independent simulations, which is of course very complicated

Kind regards
Christof

**Comment by peter-devoil** [comment]
You can set NO3/NH4 in manager code. Something like:

```
'[Soil] Nitrogen' set no3 = 30 10 5 0 0 0 (kg/ha)
```
Would work in manager1. Manager2 would use the set method, with an array argument:
```
  double [] no3 = {30, 10, 5, 0, 0, 0};
  MyPaddock.Set("NO3", no3);
```

For surfaceOM, a reset followed by an "add_surfaceOM" event would allow you to vary the SOM each year. I don't think you can use manager1 for that.

**Comment by ckluss** [comment]
Thank you very much @peter-devoil, that sounds great. 

So I am realy new to this, C# is not the problem, but is there a beginner tutorial how to include a new script? The basics are here [Manager 2](https://www.apsim.info/documentation/model-documentation/infrastructure-and-management-documentation/manager-2/) and e.g. in **Continuous Wheat with DCaPST.apsim** there are many new allocations with MyPaddock.Set() ... so I have samples

But if there are more detailed examples that could save me training time, I would be very grateful.

Many thanks
Christof

**Comment by peter-devoil** [comment]
Most people start by choosing a "functionally close" manager script in the toolbox, and modifying it. 

Here's a work in progress for advanced manager scripts & apsim: [How to write manager scripts.pptx](https://github.com/APSIMInitiative/APSIMClassic/files/5570167/How.to.write.manager.scripts.pptx) - there are some online resources at the end.
