### ISSUE TITLE
How to do automatic urea application in APSIM?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1956]
Does anyone know how to do automatic fertiliser (e.g. Urea_n) application in APSIM?

I know there is a manager named "Fertilise incrop on critical NO3 level- top up" but how can revise it so then it can use urea_N as N source? Just select the fertiliser type as Urea_N as the figure below? If yes, how can I know the daily urea added when N amount is not enough? which variable can be used for checking?

Many thanks.

![image](https://user-images.githubusercontent.com/72141690/100248503-85a8a300-2f76-11eb-8771-81d80140d4a4.png)

**Comment by peter-devoil** [comment]
Yes. Selecting urea_N will apply urea_n. Make sure you set the "Module used to apply ..." bit too. You can report the "fertiliser" variable to see how much was applied; but there's no easy way to work out which type was added apart from reading the summary file.

If you look at the "start_of_day" tab, you'll see the calculations being made. Feel free to modify them for your purpose.

**Comment by KeLiu7** [comment]
> 's no easy way to work out which type was added apart from rea

Thank you, Peter😊

**Comment by KeLiu7** [comment]
> Yes. Selecting urea_N will apply urea_n. Make sure you set the "Module used to apply ..." bit too. You can report the "fertiliser" variable to see how much was applied; but there's no easy way to work out which type was added apart from reading the summary file.
> 
> If you look at the "start_of_day" tab, you'll see the calculations being made. Feel free to modify them for your purpose.

One more question-What's the difference in the N content between Urea_N and NO3_N?

**Comment by peter-devoil** [comment]
No3_n can be used by the plant on the same day it is applied, urea_n must go through the urea hydrolysis process before the plants can use it (which is not 100% efficient). Use no3_n unless there's a good reason.

**Comment by liluo0423** [comment]
> Yes. Selecting urea_N will apply urea_n. Make sure you set the "Module used to apply ..." bit too. You can report the "fertiliser" variable to see how much was applied; but there's no easy way to work out which type was added apart from reading the summary file.
> 
> If you look at the "start_of_day" tab, you'll see the calculations being made. Feel free to modify them for your purpose.

Hi Peter, I know this is being close, but just one follow up questions here, which module should i put in "Module used to apply ...", should be "fertiliser module" or "crop module" or "soil module". Thank you so much!
