### ISSUE TITLE
error running sorghum model in pSIMS

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/APSIMClassic#1957]
I am running a sorghum experiment in a UNIX environment using the [psims](https://github.com/RDCEP/psims) soft. It automatically creates different experiments based on variable scenarios defined by the user. Particularly, I am having an issue when the template file wants to read the genotype parameters (please see the error below). I am adding the apsim file, the met file, the summary file and the Sorghum.xml files. Also I am sharing the templates used for psims to create the simulation.

![image](https://user-images.githubusercontent.com/41041705/100312399-f515a580-2ffd-11eb-90de-fced8791815f.png)

What is the exact meaning of `Too many values to convert from vector to scalar` in apsim? @hol430 

[sorghum.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5600758/sorghum.zip)

**Comment by peter-devoil** [comment]
It means that a parameter (in a ini file perhaps?) is being specified as a vector (numbers separated by spaces) instead of a scalar that it was expecting. You might have to look at a .sim file to sort out which one is causing grief.

**Comment by jbrider** [comment]
That's a version issue - your sorghum.xml or ini component is from an older version of the exe.

**Comment by JJguri** [comment]
> That's a version issue - your sorghum.xml or ini component is from an older version of the exe.

Thanks @jbrider. You were rigth. I am running now with 7.9 an it solved the problem. Was a difference in the XML file.
