### ISSUE TITLE
rainfall interception_a,b,c and d in microclimate

### ISSUE THREAD

**Issue by TiantingGuo** [APSIMInitiative/APSIMClassic#1959]
how can I get the paramaters of interception_a,b,c and d in microclimate? Is there an original reference that describe the model Pint= APB +CLai +D？

**Comment by peter-devoil** [comment]
The reference for micromet is [on the website](https://www.apsim.info/wp-content/uploads/2019/09/Micromet.pdf). Equation 13 i swhat you're after.
