### ISSUE TITLE
Using APSIM as an exploratory tool to simulate crop diversification-based scenarios in France 

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1960]
Hi everyone,

I'm a Ph.D. student in agronomy and a new user of APSIM (for non-commercial uses).
I want to know what do you think about using APSIM for simulating new cropping systems based on crop diversification (in space and time) under an **oceanic climate** in the north of France? what is the risk that the model won't perform?
I'm asking this question because APSIM is not widely used in Europe and under such a climate. Few studies exist but still limited of course. 
Note that we count to use the model as an exploratory tool to generate indicators for ecosystem services, and assess our designed scenarios. It would be difficult or even impossible to find experimental data to calibrate/validate APSIM or any other cropping system model across all crops/managements that will be included in our scenarios.

Thank you all.

**Comment by peter-devoil** [comment]
Apsim is a resource constraint model, so if you describe the [light, nutrient & water] constraints of your environment, it will respond. That said, you still have to be sure that apsim knows what the potential production response should be, and those experiments (non-limiting N, water etc) are mostly done in subtropical environments, and for "new" cropping systems they're often hardly adequate, given that conventional systems have been studied for decades. Quite often, we have to resort to "sensibility" testing - with consequent lower precision when calibration data is unavailable. 

But we are aware of people modelling wheat & barley over in the UK (Debbie Sparkes at Nottingham), and in the east (Manschadi in the Aral Sea), who did run apsim with minor modifications.

Put very quickly, if you have an idea of your target crops maximum canopy size (LAI) you'll be more confident than most.

**Comment by BrianCollinss** [comment]
@abbouhenache In Europe, including France, you can use **eurostat** data on fresh grain yield at the NUTS level to (at least partly) validate your model at a regional/national scale. We did this in France using SiriusQuality wheat model, but only published part of the job in a poster, which might be helpful: https://www.researchgate.net/publication/334234123. We had access to phenology data across Europe, which we used to calibrate phenology. Then we tried to find the cultivars matching with the yield data at a regional scale.

**Comment by abbouhenache** [comment]
@peter-devoil & @BrianCollinss thank you for these valuable pieces of information and explanations. I'm aware of some recent uses of APSIM in Europe as in the case of the project "DIVERSify" https://www.researchgate.net/publication/342410700_Summary_report_on_mechanisms_underpinning_beneficial_plant_associations_based_on_APSIM_and_DAISY ... We have also tested APSIM on some local experimental data of wheat and maize in both monocrops and rotation, the results were promising.
But as we are gonna simulate new cropping systems for their ex-ante evaluation and as those scenarios will be based on crop diversification (rotations and association), the number of species and crop management that may be included would make difficult to realize a complete process of calibration/validation for all the crops and managements. So I'm wondering: 
1. How much is this relatively important for such a task (ex-ante assessment)?
2. Would a process of parametrization-calibration & validation of the model on a partial number of cultivars phenology and managements be enough to trust the results on complex scenarios?

Again, the task is not really to predict yield but to generate a set of outputs that will serve as indicators of ecosystemic services of interest in long-term simulations (N leaching, OM, P, erosion, soil pH, ...) so which version of APSIM would you recommend for this application (Classic or next gen)?

**Comment by peter-devoil** [comment]
You may be able to simplify your new systems into generic representations that implement the major changes between each system; eg "+/- X kg N contribution from legume stubble". This avoids the need for fully coupled dynamic models, which as you suspect, are hard.

WRT classic vs nextgen; your choices will depend on what components aren't present: in that wishlist you already suffer a lack of legume, P, erosion components. This may not be a severe impediment as you can estimate their relative performance through simpler methods like above. Yet you are also constrained with classic as it has not had validation experiments in your target environment.

Simple is always a good start.

**Comment by abbouhenache** [comment]
@peter-devoil great ideas! that could really solve some issues when implementing simulations into the model.

Last interrogation about the Phosphorus module in APSIM, what is its real capacity of capturing P **dynamics** at the field scale in long term simulations (about 10 years)?
The same wondering for the pH module?

Thank you again in advance.

**Comment by peter-devoil** [comment]
Indeed, the P module is not going to tell you much in less than a 10 year time frame - it was built to study small effects over relatively long periods. It was developed for field conditions - many of it's parameters relate to field derived measurements. I'll see if I can find some of those old papers (ie they're not pdfs!).

WRT Ph - it doesnt have any toxicity effect on the plant - only affecting N movement amongst pools.

**Comment by abbouhenache** [comment]
@peter-devoil Okay! I'm grateful for your enriching answers, thanks.

**Comment by peter-devoil** [comment]
I dug up that probert paper
[probert paper](https://github.com/APSIMInitiative/APSIMClassic/files/5655449/1611479.pdf)
 if you're interested

**Comment by abbouhenache** [comment]
@peter-devoil Thank you for the document ! I will certainly come back here to the community APSIM to search for help concerning APSIM later on ! :)

Regards
