### ISSUE TITLE
Still high nitrogen stress under high nitrogen input

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1961]
I set 250 kg ha urea_N in "fertiliser at sowing" manager, also used another manager- Fertilise incrop on critical NO3 level- top up, which was maintained above 100 kg ha−1 in the top three layers of the soil. But there is still much stress in my simulations, I have attached my simulations. Can anyone please check for me? Thanks.
[Test1.zip](https://github.com/APSIMInitiative/APSIMClassic/files/5626852/Test1.zip)

**Comment by BrianCollinss** [comment]
Is soil deep enough?

**Comment by KeLiu7** [comment]
Soil depth is 200 cm. Should be enough?




--
发自我的网易邮箱手机智能版



在 2020-12-02 12:46:53，"Brian Collins" <notifications@github.com> 写道：


Is soil deep enough?

**Comment by BrianCollinss** [comment]
I can see that **fertiliser at sowing** is 150 kg/ha. But **Fertilise on days after sowing** applies the fertiliser on **wheat1** module, which I can not find. Change that to **cotton** and see what happens.

![image](https://user-images.githubusercontent.com/39573622/100953964-5d650980-355f-11eb-9d3e-34d75576b10f.png)

**Comment by KeLiu7** [comment]
> I can see that **fertiliser at sowing** is 150 kg/ha. But **Fertilise on days after sowing** applies the fertiliser on **wheat1** module, which I can not find. Change that to **cotton** and see what happens.
> 
> ![image](https://user-images.githubusercontent.com/39573622/100953964-5d650980-355f-11eb-9d3e-34d75576b10f.png)

Thanks Brian. Do you mean change the **On which module should the even come from** to "cotton" and then copy the **Fertilise on days after sowing** into my simulations? If yes, I tried it but nitrogen stress is still there.
