### ISSUE TITLE
Monocorp long-term simulation with different cultivars and different sowing dates every year

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1966]
Dear users,

Let's suppose I want to simulate a long term wheat monocrop but with different -**fixed**- dates every year and I would like to change the cultivar from one year to another, How to implement the different yearly sowing dates and cultivars in APSIM? is there a toolbox that can be added for this task?

The same issue when simulation a long-term rotation with different sowing dates (and/or cultivars) when a crop comes back to the field every X year?

Thank you in advance.

**Comment by peter-devoil** [comment]
There are several ways to do this - ranging from the heavy graphical approach via the crop rotation manager (treat each cultivar as a separate crop with its own crop management component) to some simple manager code that makes a manager variable available to the sowing rule that represents that particular year's cultivar - perhaps calculated from a round robin list.

The second method indicates you'll have to get dirty hands with some manager code. Here's a work in progress for advanced manager scripts & apsim: [How to write manager scripts.pptx](https://github.com/APSIMInitiative/APSIMClassic/files/5570167/How.to.write.manager.scripts.pptx) - there are some online resources at the end too.
