### ISSUE TITLE
Why plant did not crease growth?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1967]
I have a fast-developing barley cultivar in my simulations. The sowing date is on 1-Feb and harvested at the end of July for most years. In my long-term simulations, this cultivar had a really abnormal long growth duration in some years. For example, sowing date is the same (1-Feb) but maturity date was next May. Does anyone know why this happened?

**Comment by BrianCollinss** [comment]
Check your cultivate phenology. Is it vernalisation sensitive? Is the sowing time suitable for such a cultivate?

**Comment by KeLiu7** [comment]
> Check your cultivate phenology. Is it vernalisation sensitive? Is the sowing time suitable for such a cultivar?

Thanks
