### ISSUE TITLE
How to output the last day of end_of_juvenile in APSIM-Wheat?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#1970]
Does anyone know how to use Tracker to oupt the last day of end_of_juvenile in APSIM-Wheat? Many thanks.

**Comment by peter-devoil** [comment]
That's a tough one. In short, no, but...

You could listen out for the floral_initiation event and know you had just missed it. The plant will send out that event when it realises the phase_tt target for EJ has been met, and has started the FI phase. That should be before the end of day update methods are called, so any state variables will be very similar to yesterday (except obvious ones like met that change at the start of a day).

**Comment by KeLiu7** [comment]
> That's a tough one. In short, no, but...
> 
> You could listen out for the floral_initiation event and know you had just missed it. The plant will send out that event when it realises the phase_tt target for EJ has been met, and has started the FI phase. That should be before the end of day update methods are called, so any state variables will be very similar to yesterday (except obvious ones like met that change at the start of a day).

Thanks P. Very good suggestions
