### ISSUE TITLE
Why APSIM module can not simulate  N2O and dint ?

### ISSUE THREAD

**Issue by 13984489258** [APSIMInitiative/APSIMClassic#1972]
![image](https://user-images.githubusercontent.com/66007195/103477564-10dd4a00-4dfb-11eb-85d0-58106202f8aa.png)

**Comment by peter-devoil** [comment]
Try perturbing your inputs to see if you can get a response. Is there a point in time when fluxes/flows change? (eg when hot/wet?)

**Comment by 13984489258** [comment]
> Try perturbing your inputs to see if you can get a response. Is there a point in time when fluxes/flows change? (eg when hot/wet?)

How to perturb my input ？？？ i do not know ,and  i add irrigation amount and irrigation times ,there is no N2O and dnit ? I do not know how to solve this problem?

**Comment by peter-devoil** [comment]
WRT inputs: think of the equations that apsim is using to calculate your variables of interest, and then modify the driving variables of that equation. Eg, if it's a function of water content, then increase the water content by irrigation or the climate control component. If you suspect the model isnt responding to your inputs, then set them to impossible values to see if the model crashes or goes silly.

As well, it could be that the numbers you're trying to display are less than 0.1, you can increase the number of decimal places with the "format" argument. 
![image](https://user-images.githubusercontent.com/1924386/103703421-42b90100-4ff3-11eb-9dee-ac16150010d4.png)

**Comment by 13984489258** [comment]
> WRT inputs: think of the equations that apsim is using to calculate your variables of interest, and then modify the driving variables of that equation. Eg, if it's a function of water content, then increase the water content by irrigation or the climate control component. If you suspect the model isnt responding to your inputs, then set them to impossible values to see if the model crashes or goes silly.
> 
> As well, it could be that the numbers you're trying to display are less than 0.1, you can increase the number of decimal places with the "format" argument.
> ![image](https://user-images.githubusercontent.com/1924386/103703421-42b90100-4ff3-11eb-9dee-ac16150010d4.png)

OK！！！thanks  a lot

**Comment by 13984489258** [comment]
> > WRT inputs: think of the equations that apsim is using to calculate your variables of interest, and then modify the driving variables of that equation. Eg, if it's a function of water content, then increase the water content by irrigation or the climate control component. If you suspect the model isnt responding to your inputs, then set them to impossible values to see if the model crashes or goes silly.
> > As well, it could be that the numbers you're trying to display are less than 0.1, you can increase the number of decimal places with the "format" argument.
> > ![image](https://user-images.githubusercontent.com/1924386/103703421-42b90100-4ff3-11eb-9dee-ac16150010d4.png)
> 
> OK！！！thanks a lot

How can I add a decimal point to my result？i find the output file .and i can find the format.what should i do?

**Comment by peter-devoil** [comment]
In the variables node underneath the outputfile component, you have a bunch of lines with single words, eg "n2o_atm". Add the format qualifier to that word, eg "n2o_atm format 6"

**Comment by 13984489258** [comment]
> In the variables node underneath the outputfile component, you have a bunch of lines with single words, eg "n2o_atm". Add the format qualifier to that word, eg "n2o_atm format 6"

ok !Thanks a lot ! i get it ! Another question about if apsim can simulateammonia volatilization losses???

**Comment by peter-devoil** [comment]
I suspect not.
