### ISSUE TITLE
Can APSIM handle CO2<350 ppm?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1975]
According to Mauna Loa data, atmospheric CO2 concentration was below 320 ppm in 1960. CSIRO Cape Grim data shows an atmospheric CO2 concentration of 330 ppm in 1976. 

- Can APSIM Classic accept and handle such low CO2 values? 
- And would that make sense?

![image](https://user-images.githubusercontent.com/39573622/104574075-5b837f80-56a1-11eb-8ab3-18148401fb05.png)

**Comment by peter-devoil** [comment]
I'd check Meinke's work to see if the 350ppm lower limit that is implemented was an oversight or mistake. I remember several people claiming it was a mistake.

**Comment by BrianCollinss** [comment]
The same threshold exists in NextGen. It seems that CO2 modifier should work for CO2 lower than 350, but it has not been tested.

**Comment by peter-devoil** [comment]
A quick look at the RUE modifier equation shows a scaling ratio relative to 350ppm, which will do very strange things when ambient CO2 is less than 350. So I'd suggest the lower limit is sensible.

**Comment by BrianCollinss** [comment]
Thanks mate. Case closed!
