### ISSUE TITLE
N leaching output variables in the 7.10 version

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1976]
Hi everyone,

I'm trying to find the variables indicating the N leached from soil which are supposed to be "leach_no3" and "flow_no3" but i can not find them in the soil output list.

I have read in a recent posted issue (https://github.com/APSIMInitiative/APSIMClassic/issues/1971) that no3 should be registered as a solute; other way the autodocs won't find them.

Can someone tell me please how to do that in the 7.10 version? is there any tutorials about that?

And please what "flow_no3" indicates exactly? what flow of no3 is meant here?

Thanks

**Comment by abbouhenache** [comment]
Dear developpers,

I got the output variables "no3_leached" and "no3_flow" by simply writing them manually in the outputs' list, can i trust the values obtained this way? and still need to know the signification of the flows indicated by "no3_flow" please!

thanks you in advance
Best regards

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any thoughts?

**Comment by sno036** [comment]
Hi @abbouhenache  - the APSIM Classic documentation is found at https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/.  

flow_nnnn | kg/ha | Amount of solute nnnn in saturated water movement from each layer to the layer below (where ‘nnnn’ is the name of the solute)(eg. flow_no3)

flux_no3 (also not in the list) is the equivalent for unsaturated flow. and both of these are by layer,

Also undocumented seems to be leach_no3 which is the amount leaving the soil profile downwards.

Have you checked that "no3_leached" and "no3_flow" are giving sensible values? They might be fine just undocumented.

**Comment by abbouhenache** [comment]
@sarahcleary and @sno036 thanks for your reactions,

I think you are right, these two variables are just undocumented. According to the simulations I did, the results seem to give sensible values :)

Best regards
