### ISSUE TITLE
nitrification rate and denitrification rate 

### ISSUE THREAD

**Issue by 13984489258** [APSIMInitiative/APSIMClassic#1977]
Dear Model developer:
I want to know which  parameters  indicates nitrification rate and the denitrification rate ? thanks a lot

**Comment by 13984489258** [comment]
@peter-devoil  how to do about this

**Comment by peter-devoil** [comment]
In [the documentation](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soiln/), it mentions  "...sensibleness of the simulations where significant amounts of denitrification occur has not been verified". So - whatever apsim is doing, you should be suspicious that it is wrong..

That said, the ini file defines those parameters here: https://github.com/APSIMInitiative/APSIMClassic/blob/242bf96730a040eaaefc5524380bc8b0c74f90e2/Model/Soil.xml#L437

Note you should use a plugin component in your .apsim file to use a modified ini file. You should never change the original installed file.
