### ISSUE TITLE
Water table

### ISSUE THREAD

**Issue by Kadogo1** [APSIMInitiative/APSIMClassic#1978]
When using SoilWat and outputting water table from the dropdown output variables, the variable is 'water_table'. After switching to SWIM, the 'water_table' column is filled with '?'. Then I manually wrote 'watertable' without the '-' in the output variables and this worked and the water table was printed out. Are there different output variable names when using SoilWAT and SWIM? This happens also with 'sws'.

**Comment by peter-devoil** [comment]
Yes, they are very different modules under the hood. Some of the differences are conceptual - the underlying science is different between the models - others are accidental / programming errors.

**Comment by Kadogo1** [comment]
It's true the modules are different. My concern was the "OUTPUT variable names" in the 'dropdown' menu. it's probably best to have the same "OUTPUT variable names" for a given output whether one is using SWIM or SoilWat. 
Currently "watertable" works with SWIM (although this is not in the dropdown menu and there is no way for the user to know to change this manually) and "water_table" in SoilWat.
