### ISSUE TITLE
grain_no * grain_size * 10 is never equal to yield!

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1982]
Should APSIM output **grain_size** with a higher precision?

**Comment by peter-devoil** [comment]
You can set the precision in output files with the "format" qualifier, eg

grain_size format 16

**Comment by BrianCollinss** [comment]
Thanks Peter. May I know what 16 is?

**Comment by peter-devoil** [comment]
16 decimal places
