### ISSUE TITLE
SoilP module not found in the intallation directory

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1984]
Hi everyone,

Can someone tell me where to find the SoilP.xml file? it's not found in the directory of installation with the other modules!
Why is not it installed? I did try with the versions 7.10 and 7.4, note that the SoiP.ddl file is there and that the simulations run well for phosphorus for some crops like maize.

The module found in the section "code" here https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/SoilP/SoilP.f90 is it the correspondent one?

Thank you in advance for the help

Regards

**Comment by peter-devoil** [comment]
It's a subsection of the Soil.xml megamodule now - for gui reasons, I suspect.

**Comment by abbouhenache** [comment]
@peter-devoil I found it, and made the modification i needed.

Thank you so much.
