### ISSUE TITLE
R packages to conducte a global sensitivity analysis

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#1985]
Dear users,

I would like to know methods and R packages to carried out a global senstivity analysis on soil fertility parameters (OC%, P and pH) to assess the effect of each parameter on APSIM-wheat simulation output.

Thank you very much,
Have a good day

**Comment by peter-devoil** [comment]
Hi,
A lot of people conduct simple sensitivity analysis with the [factorial component](https://www.apsim.info/support/apsim-training-manuals/construct-a-factorial-simulation-in-the-user-interface/).

Alternatively, you can write scripts in your favourite programming language to read/write the apsim XML files. Much of what you would need is [here](https://www.apsim.info/documentation/model-documentation/developer-documentation/a-simple-demonstration-of-connecting-apsim-to-optimisation-frameworks/).
