### ISSUE TITLE
Issue with SILOinput

### ISSUE THREAD

**Issue by AHR12345** [APSIMInitiative/APSIMClassic#1986]
Hello, 

I am having an issue with SILOinput, 

I have attached my simulation file, in which APSIM seems to be unable to communicate with SILO. 

I am receiving 'HTTP Open failure' 

I am attempting to retrieve data from Bundaberg Aero or 39128. 

Any advice on this issue would be greatly appreciated. 

Henry

[SLURP (converted from cane).zip](https://github.com/APSIMInitiative/APSIMClassic/files/5978750/SLURP.converted.from.cane.zip)

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any suggestions?

**Comment by peter-devoil** [comment]
Try this from another network. Many corporate networks block direct outgoing traffic - requiring the use of a proxy, which apsim doesn't know how to deal with. I often have to recommend that people use home resources (both networks and computers) to get "work" done.

**Comment by AHR12345** [comment]
Thanks Peter,

I will give this a shot on my home network.

Regards,

Henry
