### ISSUE TITLE
Issues associated with APSoil in APSIM V7.10

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/APSIMClassic#1987]
Dear Apsim Classic users 

Based on Dalgliesh et al (2016) I inserted sorghum soil parameters in the APSoil database for some profiles. I uploaded the modified APSOIl to the APSIM GUI through "Option". But the modified soil did not work. The error message is "Can't find soil water info for sorghum". I then examined the modified soil database and found there is a blank space after sorghum <SoilCrop name="sorghum ">. I deleted the blank space and saved the changes and re-uploded it to the apsim GUI, but it still did not work. The problem is that once the edited soil database was uploaded to the GUI, the soil text file become to  <SoilCrop name="sorghum "> again (not in the right format <SoilCrop name="sorghum">). 

The other problem is that I found two soil profiles (Dysart No1270, Baralaba No1265) have no info for Fbiom in the module of SoilOrganicMatter. Once again I inserted relevant info on FBiom in the APSoil database and saved the changes and uploaded it to the GUI and re-run the model, but it did not work. The problem is that even though I edited and saved the changes,  once the modified soil database is uploaded to the GUI, the inserted section in the database disappeared. The error message from running the model is " Object reference not set to an instance of an object", "Unable to read real value from string [Soil.SoilOrganicmatter.Fbiom]". 

Just wondering how to fix these two problems.  

looking forward to your support!

**Comment by peter-devoil** [comment]
I think "uploading" wont work - the soil toolbox in the GUI is read only, and won't allow you to make changes. I suspect the GUI is silently ignoring some of your attempts to fix it, and gets into a twist when some parts are accepted, but not others - hence the cryptic "object not set ..." message.

There is nothing to stop you from duplicating it (drag into another toolbox), and making corrections there.

Only last week, I too found many misspellings of the ASC field, and wrote an R script to rename them. I suspect Kirsten Verburg may be the person maintaining it. I'll ask.

**Comment by qluo02** [comment]
Thanks, Peter!
