### ISSUE TITLE
How does APSIM calculate Subsurface Drainage NO3 Concentration?

### ISSUE THREAD

**Issue by adam-weis** [APSIMInitiative/APSIMClassic#1988]
I'm using APSIM to investigate how different practices affect the nitrate concentration in tile drainage. I've found the tile module to be really useful, however I'm struggling to find documentation or explanation of how APSIM calculates the NO3 concentration in the tile drainage, reported as variable 'subsurface_drain_no3'. I understand how the actual drainage flow ('subsurface_drain') is calculated after reading the 2007 paper by Malone et al. about their formulation of the subsurface drainage model:

https://www.sciencedirect.com/science/article/pii/S0016706107001103

Anyone have any insights on this? Thanks!

**Comment by sarahcleary** [comment]
@adam-weis - are you still looking for an answer on this?

**Comment by peter-devoil** [comment]
@sarchontoulis or @hut104 might know how it works

**Comment by sarchontoulis** [comment]
The variable name "subsurface_drain_no3" refers to the amount of N03 in the tiles (kg NO3-N/ha). So by having the amount of water and the amount of N03, the concentration can be computed.

**Comment by adam-weis** [comment]
@sarchontoulis thank you for your reply! That makes sense, thank you. Do you know how the mass of NO3-N is calculated in the tiles? The Malone paper explains how the amount of water is calculated using the Hooghoudt equation, but I'm not sure about nitrate. I have found that the nitrate concentration in the tiles is similar, but not exact, to the concentration in the soil layer just above the tiles, but I don't know what dictates the mass of nitrate removed in tile water.

**Comment by hut104** [comment]
It's just mass flow. Soil concentration X flux volume.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adam-weis** [comment]
Thanks everyone, I appreciate the help!
