### ISSUE TITLE
APSIM 7.10 can't run cotton sim, doesn't have any error output

### ISSUE THREAD

**Issue by tdonovic** [APSIMInitiative/APSIMClassic#1989]
Hi there!
Feel as though I'm going a bit mad. Trying to run APSIM under mono in a linux container. Have tried many combinations of different revisions of APSIM, both built by the APSIM build system, and also built locally. When I run the executables under Windows, no problems, my cotton simulations run.

Thinking that my simulation was the issue, I tried using the sample cotton simulation, but got the same ouput:
```     ###     ######     #####   #   #     #
    #   #    #     #   #        #   ##   ##
   #     #   #     #   #        #   ##   ##
   #######   ######     #####   #   # # # #
   #     #   #              #   #   #  #  #
   #     #   #         #####    #   #  #  #


 The Agricultural Production Systems Simulator
             Copyright(c) APSRU

Version                = 7.10 r4215
Title                  = Continuous Irrigated Cotton - deficit rule
   Component                        "clock" = %apsim%/Model/Clock.so
   Component                          "met" = %apsim%/Model/Input.so
Paddock:
   Component                   "outputfile" = %apsim%/Model/Report.so
   Component                        "accum" = %apsim%/Model/Accum.so
   Component                   "fertiliser" = %apsim%/Model/Fertiliser.so
   Component                   "Irrigation" = %apsim%/Model/Irrigation.so
   Component                   "Soil Water" = %apsim%/Model/SoilWat.so
   Component         "SurfaceOrganicMatter" = %apsim%/Model/SurfaceOM.so
   Component                "Soil Nitrogen" = %apsim%/Model/SoilN.so
   Component              "Crop Management" = %apsim%/Model/Manager2.dll
   Component      "Cotton defoliation rule" = %apsim%/Model/Manager2.dll
   Component          "Fertilise at Sowing" = %apsim%/Model/Manager2.dll
   Component "Fertilise on days after sowing" = %apsim%/Model/Manager2.dll
   Component            "Irrigate on event" = %apsim%/Model/Manager2.dll
   Component         "Post Harvest Tillage" = %apsim%/Model/Manager2.dll
   Component                       "Cotton" = %apsim%/Model/Cotton.dll
```

With no further output. 
I invoke apsim with:
 ```root@52058492db45:/apsim/Temp/Model# mono Apsim.exe /opt/small/*.apsim
Written /opt/small/Continuous Dryland Cotton.sim
Written /opt/small/Continuous Irrigated Cotton - deficit rule.sim
[Pass] /opt/small/Continuous Dryland Cotton.sim:Continuous Dryland Cotton [0sec]
[Pass] /opt/small/Continuous Irrigated Cotton - deficit rule.sim:Continuous Irrigated Cotton - deficit rule [0sec]
[Pass] Delete /opt/small/Continuous Dryland Cotton.sim [0sec]
[Pass] Delete /opt/small/Continuous Irrigated Cotton - deficit rule.sim [0sec]
[Pass] Target: Apsim.exe [1sec]```

I have tried this with mono 6.12 and 4.8. I have also tried the solution as [described here](https://github.com/APSIMInitiative/APSIMClassic/issues/1755#issuecomment-619705163), which didn't make any difference. I have also done a stack trace, but didn't see any reference to cotton.
[out.log](https://github.com/APSIMInitiative/APSIMClassic/files/6019773/out.log)

I have also been able to successfully run other known good simulations.

Really stumped here, is there anything else you can suggest to debug? 
Thanks!

**Comment by peter-devoil** [comment]
The process Apsim.exe is just a marshalling process, the simulation worker is called ApsimModel.exe. The worker is the one you want to run strace on. As it's a C runtime, you may need to set an environment variable LD_LIBRARY_PATH=/Apsim/Temp/Model.

But before you go too far; did you manage to build a /Apsim/Temp/Model/Cotton.dll? It needs a password in /etc before it can be built.

**Comment by tdonovic** [comment]
Yep, we have a license and I can confirm that Cotton.dll exists
```
root@5cfd1f21990a:/apsim/Temp/Model# ls | grep Cotton
Cotton.dll
Cotton.xml
```
Also I have set the env var, and the output is just as blank:
```root@5cfd1f21990a:/apsim/Temp/Model# env | grep LD
LD_LIBRARY_PATH=/Apsim/Temp/Model```

The .apsim I am using is attached, if that helps at all? I can confirm that continuous irrigated cotton works on windows, I have made sure the .met is available at the correct path as well. 

[cc.apsim.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6020850/cc.apsim.zip)

**Comment by peter-devoil** [comment]
The strace output of "/Apsim/Temp/Model/ApsimModel.exe cc.apsim" would be good. It should show us Cotton.dll being loaded and whether there are ancilliary dlls failing to load. Once the dlls are loaded (after the init stage), we would use the "diagnostic log component" in the management toolbox to see which messages are giving grief. But in your case, the dlls aren't being loaded. 

At first glance, one would suspect this is a .NET installation error (especially as the sample .apsim file runs fine here..), but your simulation has several manager2 .NET dlls being loaded before the cotton dll is failing - so that's less likely.

**Comment by tdonovic** [comment]
To check I wasn't going mad, I ran both Apsim.exe and ApsimModel.exe against a known good .apsim. This sim produced output when I ran it with Apsim.exe, however when I run `strace mono ApsimModel.exe ...` I get a suspect:
```
write(2, "Cannot open assembly 'ApsimModel"..., 80Cannot open assembly 'ApsimModel.exe': File does not contain a valid CIL image.
) = 80
```

Full strace here:
[tmp.txt](https://github.com/APSIMInitiative/APSIMClassic/files/6025934/tmp.txt)

**Comment by peter-devoil** [comment]
Just "strace ApsimModel.exe ..." will get you there. It's a libc application, not .NET.

**Comment by tdonovic** [comment]
Without even strace, now I get some useful output:
```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'ManagedComponent.MvOZCOT.Cultivars:XDocCultivars' (0) due to: Could not load file or assembly 'System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
  at CMPComp.TComponentInstance..ctor (System.UInt32 compID, System.UInt32 parentCompID, CMPServices.MessageFromLogic messageCallback) [0x00000] in <86812c623db64b84a43b2406a9c4e013>:0
  at CMPComp.TGCComponent..ctor (System.UInt32 compID, System.UInt32 parentCompID, System.UInt64 messageCallback) [0x0001b] in <86812c623db64b84a43b2406a9c4e013>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'ManagedComponent.MvOZCOT.Cultivars:XDocCultivars' (0) due to: Could not load file or assembly 'System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
  at CMPComp.TComponentInstance..ctor (System.UInt32 compID, System.UInt32 parentCompID, CMPServices.MessageFromLogic messageCallback) [0x00000] in <86812c623db64b84a43b2406a9c4e013>:0
  at CMPComp.TGCComponent..ctor (System.UInt32 compID, System.UInt32 parentCompID, System.UInt64 messageCallback) [0x0001b] in <86812c623db64b84a43b2406a9c4e013>:0
```
And the strace: 
[log.log](https://github.com/APSIMInitiative/APSIMClassic/files/6025998/log.log)

Then, when I set the LD_LIBRARY_PATH as you suggested above:
```
root@af705ff6b959:/apsim/Temp/Model# export LD_LIBRARY_PATH=/Apsim/Temp/Model
root@af705ff6b959:/apsim/Temp/Model# env | grep LD
LD_LIBRARY_PATH=/Apsim/Temp/Model
root@af705ff6b959:/apsim/Temp/Model# ./ApsimModel.exe /opt/small/cc.apsim
./ApsimModel.exe: error while loading shared libraries: libApsimShared.so: cannot open shared object file: No such file or directory
```
I get the impression I shouldn't set that one then?

**Comment by peter-devoil** [comment]
1) export LD_LIBRARY_PATH=/**a**psim/Temp/Model (sorry)
2) you don't need that now that you've found the .net assembly that is missing. In [this issue](https://github.com/leezer3/OpenBVE/issues/369), they indicate it might be missing from mono-devel - did you install mono-devel or mono-complete?

**Comment by tdonovic** [comment]
Ah gotcha, should have noticed that one hehe. 
Now we are cooking with gas! I installed the lib that issue recomended now I am getting some really juicy output!
[log.log](https://github.com/APSIMInitiative/APSIMClassic/files/6026112/log.log)

I'm guessing I'm missing some library to write to std.out? https://github.com/mono/mono/issues/16991 seems to suggest I need a different version of mono to make it work... For reference this is with mono 6.10

**Comment by peter-devoil** [comment]
I'm using 6.12, and [added the symlink](https://github.com/APSIMInitiative/APSIMClassic/issues/1755#issuecomment-619705163) suggested by eric. My limited testing (I've only had this machine 2 weeks!) has been positive

```$ mono --version
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:26:45 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

**Comment by tdonovic** [comment]
Ok! With that, let me try with newer mono and the symlink and see how I go. Thanks for all the help, I really appreciate it!

**Comment by peter-devoil** [comment]
Try th symlink first - it seems to have been working for a while.

**Comment by tdonovic** [comment]
Amazing! It works! Thanks so much for your help. Absolutely made my day!!!

**Comment by tdonovic** [comment]
For reference for anyone else with a similar issue, I needed to update to mono 6.12 for it to work, it failed differently again under 6.10
