### ISSUE TITLE
model Hairy vetch (Vicia villosa Roth)

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/APSIMClassic#1991]
We would like to model biomass, yield, and phenology of Hairy vetch (Vicia villosa Roth) with APSIM, a common cover crop in Argentina. In the documentation only it is available as surface organic matter residue type. Is there some close plant module we should start with? @daianfrancia

**Comment by sarahcleary** [comment]
@JJguri - are you happy if this issue is closed?  or still requires action?

**Comment by JJguri** [comment]
I would like to hear some comments about it, at least to have in mind the closest crop we should use. Thanks

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel; @hut104 - any comments? suggestions?

**Comment by sarahcleary** [comment]
@JJguri - are you still looking for an answer to this question?

**Comment by JJguri** [comment]
> @JJguri - are you still looking for an answer to this question?

yes thanks

**Comment by sarahcleary** [comment]
@hut104 ; @APSIMInitiative/reference-panel  - can anyone help @JJguri?
