### ISSUE TITLE
photop_sens & vern_sens

### ISSUE THREAD

**Issue by Pedologist** [APSIMInitiative/APSIMClassic#1992]
Dear users, 
 
 I would be very grateful if you can explain to me How can I determine photoperiod ( photop_sens ) and vernalisation ( vern_sens ) for my own crop ?
 
 Thank you in advance.

**Comment by peter-devoil** [comment]
A lot of people do it in a spreadsheet - reflecting the limited data available. @jwhish may have a legume sample.

@mcleang wrote a program called devel that ran an optimiser.

Much literature is about, start with https://doi.org/10.1016/S0378-4290(97)00062-2

**Comment by Pedologist** [comment]
Thank you so much @peter-devoil
