### ISSUE TITLE
APSIM Model Calibration

### ISSUE THREAD

**Issue by Pedologist** [APSIMInitiative/APSIMClassic#1993]
Dear users, 

How can I calibrate the model ? which parameters that I need to calibrate them exactly ? How can I calibrate them ? it is manually or there are some conditions ??

**Comment by peter-devoil** [comment]
It depends on the question you're asking. A model isn't an end, but a tool to help _you_ get there.

There's some good references to soil related parameterisation [here](https://github.com/APSIMInitiative/APSIMClassic/issues/1886).

**Comment by Pedologist** [comment]
Ok perfect, thanks a lot @peter-devoil
