### ISSUE TITLE
potato fresh yield

### ISSUE THREAD

**Issue by charlie-ffff** [APSIMInitiative/APSIMClassic#1994]
hello!
When i using APSIM-potato to simulate potato yield,all i can found is dry matter yield, but I cant find the fresh yield of potato in the output, and in the variables, does it can produce fresh yield?

**Comment by peter-devoil** [comment]
With very rare exceptions, all weights in apsim are on a dry weight basis. Water content of plant organs isn't modelled.

**Comment by charlie-ffff** [comment]
> 
> 
> With very rare exceptions, all weights in apsim are on a dry weight basis. Water content of plant organs isn't modelled.

 I see. Thank you for your answer!
