### ISSUE TITLE
How to modify xml file using R

### ISSUE THREAD

**Issue by charlie-ffff** [APSIMInitiative/APSIMClassic#1995]
hello!
I want to change one parameter xml file using R, but I dont know how to write my modified data to xml, 

```
url_experiment = "G:/potato/p10/Potato.xml"
xml_experiment_list = xmlToList(url_experiment)
xml_experiment_list[[2]][[55]]$y_sla_max$text<-c("18000 40000    ")
write(xml_experiment_list,"G:/aaa.xml")
```
Error in cat(x, file = file, sep = c(rep.int(sep, ncolumns - 1), "\n"),  : 
  argument 1 (type 'list') cannot be handled by 'cat'

**Comment by byzheng** [comment]
I don't suggesto to convert xml into list to modify xml file in R. You can directly use XML or xml2 package to modify xml file. Alternatively, functions in RAPSIM package can help you to directly modify XML file using text search and replace. https://github.com/byzheng/rapsim/blob/master/R/xml.R

**Comment by charlie-ffff** [comment]
谢谢郑老师！！！

> 
> 
> I don't suggesto to convert xml into list to modify xml file in R. You can directly use XML or xml2 package to modify xml file. Alternatively, functions in RAPSIM package can help you to directly modify XML file using text search and replace. https://github.com/byzheng/rapsim/blob/master/R/xml.R

谢谢郑老师！！！

**Comment by peter-devoil** [comment]
Yes - working with lists of lists isn't helpful. xpath expressions are far more reliable.

**Comment by charlie-ffff** [comment]
> 
> 
> Yes - working with lists of lists isn't helpful. xpath expressions are far more reliable.

Thank you for your answer!
