### ISSUE TITLE
Issue with APSoil while checking the soil

### ISSUE THREAD

**Issue by painchetotam** [APSIMInitiative/APSIMClassic#1996]
Greetings. I've acquired the needed data for my simulation and tried to create custom soil file through the APSoil interface. On the first screen(Soil),I've clicked the "Check Soils" button and got this message with unhandled exception. Any suggestions of the reason why did this happen?
****************` Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApsimFile.Soil.Check(Boolean IgnoreStartingWaterN)
   at CSUserInterface.SoilPropertyUI.CheckButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3468.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ApsimUI
    Assembly Version: 1.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/ApsimUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3515.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3570.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ApsimFile
    Assembly Version: 3.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/ApsimFile.DLL
----------------------------------------
Controllers
    Assembly Version: 0.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/Controllers.DLL
----------------------------------------
CSGeneral
    Assembly Version: 3.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/CSGeneral.DLL
----------------------------------------
Actions
    Assembly Version: 0.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/Actions.DLL
----------------------------------------
Graph
    Assembly Version: 1.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/Graph.DLL
----------------------------------------
CSUserInterface
    Assembly Version: 1.0.6662.25799
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/CSUserInterface.DLL
----------------------------------------
CPIUserInterface
    Assembly Version: 1.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/CPIUserInterface.DLL
----------------------------------------
UIBits
    Assembly Version: 1.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/UIBits.DLL
----------------------------------------
UIUtility
    Assembly Version: 1.0.0.0
    Win32 Version: 7.10.4158.0
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/UIUtility.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3515.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
TeeChart.Client
    Assembly Version: 4.1.2011.7283
    Win32 Version: 4.1.2011.7283
    CodeBase: file:///C:/Program%20Files%20(x86)/APSIM710-r4158/Model/TeeChart.Client.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll**
----------------------------------------

**Comment by painchetotam** [comment]
Also this type of error apperared while writing my .soil file from XLS spreadsheet and importing it into APSoil. Any advise on the matter will be appreciated.

**Comment by peter-devoil** [comment]
Hard to tell. Try the usual suspects:
- mark all the empty rows/columns and delete the contents (sometimes there are non-printables in them)
- ensure the number of layers are matched between soil components, and that columns are filled completely (ie to match the depth column, or are empty)
- ensure the regionalisation settings are ok ("." is a decimal place etc)

**Comment by painchetotam** [comment]
Attaching my XLS soil file
Maybe that will help to understand the issue better
[Error.xlsx](https://github.com/APSIMInitiative/APSIMClassic/files/6061096/Error.xlsx)

**Comment by peter-devoil** [comment]
I'd check those numbers carefully. There appear to be lots of unit problems

Is your soil really 180mm thick?

All the water measurements must be between 0-1

SAT > DUL > LL15

LL > LL15

It might be better to enter them into the GUI and check the graph with each addition. There are lots of resources on the [soils page](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/).
