### ISSUE TITLE
Harvest rule 

### ISSUE THREAD

**Issue by charlie-ffff** [APSIMInitiative/APSIMClassic#1997]
I'm conducting a yield simulation with APSIM7.10, it should harvest when encounter first frost day(daily avarage temperature less than 0). 
Do I need to add some temperature variables in the following code? and how to write the script?
`if [crop].StageName = 'maturity' or [crop].plant_status = 'dead' then
              [crop]  harvest
              [crop]  end_crop
           endif`

**Comment by peter-devoil** [comment]
Something like 
```
if (([crop].StageName = 'maturity' or [crop].plant_status = 'dead') or 
    ([crop].StageCode > 6 AND mint < 0)) then 
  [crop] harvest 
  [crop] end_crop 
endif
```
...should do the trick. When you mix logical AND and OR, ensure you use brackets.

**Comment by charlie-ffff** [comment]
@peter-devoil  Thanks. I run APSIM with that however got following error:
` Unable to read double precision value from string :-
     maturity
     Component name: paddock.Harvesting rule
`

**Comment by peter-devoil** [comment]
The key to debugging apsim is to make small changes and test. In this case:

- remove the "AND mint < 0" addition and see if the problem's still there. It most likely will be.
- remove the "[crop].StageCode > 6 AND" and see... When it fails, read the manual (like I didnt) and discover that the variable is called "Stage"...

HTH
P

**Comment by charlie-ffff** [comment]
@peter-devoil  Thanks again! I made small changes like you said above, there still the some error, and I checked the yield variables there do exsist "Stage" variable, I have no idea now...
[potato.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6065842/potato.zip)

**Comment by peter-devoil** [comment]
The other thing to look out for is mis-matched parentheses - it doesnt give you a very good warning, in fact it gives you a misleading warning..

```
           if ([crop].StageName = 'maturity' or [crop].plant_status = 'dead' or 
	       ([crop].Stage > 6 AND mint <0)) then
              [crop]  harvest
```

**Comment by charlie-ffff** [comment]
@peter-devoil  It works. The problem is parentheses .... thanks a lot!
