### ISSUE TITLE
CO2 emissions output variable

### ISSUE THREAD

**Issue by abbouhenache** [APSIMInitiative/APSIMClassic#1998]
Hello,

Except "dlt_fom_c_atm", "dlt_hum_c_atm" and "dlt_biom_c_atm" that represent the lost quantities of C from C pools to atmosphere, is there an output variable that indicates the **total** CO2 emissions from SOM reactions? CO2 is calculated in the line 4268 of the code (if i'm right) and is far from being the simple sum of those 3 outputs
I'm seeing "dlt_c_atm" in the line 3356 of the code that looks like an output, but i'm getting nothing in writting it in outputs' list!

Help please

Thank you in advance

**Comment by peter-devoil** [comment]
I vaguely remember being told the N module was incomplete WRT CO2 emissions. @hut104 may have more detail.

**Comment by hut104** [comment]
It is many years since I've used APSIM Classic.
Try Catm adding up C losses to atmosphere from all soil and residue pools that decompose
dlt_res_c_atm
dlt_fom_c_atm
dlt_hum_c_atm
dlt_biom_c_atm

**Comment by abbouhenache** [comment]
@peter-devoil @hut104 I have tried but i'm getting nothing except "dlt_fom_c_atm", "dlt_hum_c_atm" and "dlt_biom_c_atm" unfortunatly!
CO2 produced seems to be calculated as a local variable (used for the equation of NO2 from denitrification) as follows (line 4268 of the [code](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/SoilN/SoilN.f90)): 
CO2 = (sum(g%dlt_fom_c_atm(:,layer)) + g%dlt_biom_c_atm(layer) + g%dlt_hum_c_atm(layer) + g%dlt_biochar_c_co2(layer))/(g%bd(layer)*g%dlayer(layer))*100
but it's not an output variable, and the problem is that there is no output variable indicating dlt_biochar_c_co2 or it would possible maybe to reproduce this equation on an excel file for example.

Many papers have dealt with CO2 emissions simulated by APSIM : https://doi.org/10.1016/j.geoderma.2011.07.003  https://doi.org/10.1080/00288233.2014.987876 ... quite sure there is a way 

Any other ideas?

**Comment by abbouhenache** [comment]
Hi everyone again,
Does someone have an idea?

**Comment by hut104** [comment]
It's as you and others say above.  Just sum those relevant outputs.  Ignore biochar - it is an extra scripted model by the authors of the paper.
Depending on your case, you may not need to add the residue CO2.

**Comment by abbouhenache** [comment]
@hut104 understood :) thank you very much

kind regards
