### ISSUE TITLE
co2 detected -> add x_co2 and y_trans_eff_cf_fact to ini file

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#1999]
When I modify CO2 in my simulations, I receive this error. Even when I add these two to the Sugar.xml (ini) file (both plant and ratoon), I still get the error.

```
      <x_co2>350  700   1000</x_co2>
      <y_transp_eff_cf_fact>1.0  1.37  1.69</y_transp_eff_cf_fact>

```

**Comment by peter-devoil** [comment]
Looks like it wants an rue factor too. No idea what it should be tho - Peter Thorburn might. 
https://github.com/APSIMInitiative/APSIMClassic/blob/1d3cc6128364b8a9f2fe9927954079a492272ca8/Model/Sugar/SugarMain.for#L2650

**Comment by BrianCollinss** [comment]
Yes. But surprisingly I still get the error for TEc missing factor, nut RUE. The code has a separate exception for RUE.

**Comment by peter-devoil** [comment]
That's odd. Try creating a sim file to ensure its being pulled in from whatever plugin/ini file you've specified. Failing that, we'd have to ask for an example simulation.

**Comment by sarahcleary** [comment]
@PeterThorburn

**Comment by BrianCollinss** [comment]
I exported to SIM and it does have those new parameters. I addedd them under both Plant and Ratoon. I hope that is where they should appear.
[Sugar.txt](https://github.com/APSIMInitiative/APSIMClassic/files/6087303/Sugar.txt)

**Comment by peter-devoil** [comment]
I wonder if it's in the correct section. Try moving it next to the "nh4_min_lb" parameter in the section above ("constants")?

[This](https://github.com/APSIMInitiative/APSIMClassic/blob/1d3cc6128364b8a9f2fe9927954079a492272ca8/Model/Sugar/SugarMain.for#L4210) is where it's being read, adjacent to a whole bunch of optional parameters. The last read parameter before that is nh4_min_lb. 

My word, there are a _lot_ of optional parameters in there.

**Comment by BrianCollinss** [comment]
Fixed! Like always, super helpful @peter-devoil. It's good if we could get some advice from @PeterThorburn about the values. Cheers.
