### ISSUE TITLE
Zero drain and non-zero N leaching

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2001]
How can we have no drainage but some leaching? I am using flow_no3 for N leaching from the botom of the profile (following one of the examples for Sugarcane).

![image](https://user-images.githubusercontent.com/39573622/110062654-657a5280-7db5-11eb-8f59-a7833734e358.png)

**Comment by peter-devoil** [comment]
Is that really irrigating 1400 mm over 2 weeks? Unless you've got a very fat soil, I'd expect some drainage after even the first day. How is totaldrain calculated?

**Comment by BrianCollinss** [comment]
My mistake! I am an idiot!!! Sorry.
