### ISSUE TITLE
Sugarcane skips some years in a sandy soil

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2002]
[Brian.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6088417/Brian.zip)

In this simulation, Sugarcane does not grow (as a Plant) in many of the years. The very same simulation works fine with a less sandy soil. Is there any requirement for Sugarcane to start growing that may not be met in a sandy soil? I can see that plants do not start growing, so it is not like they start and fail.

**Comment by peter-devoil** [comment]
Is the difference of soil sand/clay content, or waterholding capacity?

If it's waterholding capacity - then the wetter conditions are more favourable to growth? Maybe some stats of water content (min/avg/max) in the layer where the stalk is planted will explain. Usually the "germination" routine is a water content x thermal time accumulator (HydroTT)  so don't overlook temperature if the waters are identical.

**Comment by BrianCollinss** [comment]
The met files are the same. The only difference is depth and water holding capacity. I will look at sowing layer see how the SW varies.
