### ISSUE TITLE
Does anyone know how to ouput Water supply to demand ratio in APSIM-Wheat?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2003]
I just tried to use **sw_supply** and **sw_demand** variables to calculate the WaterSD but the result is not what I need.  Can anyone tell me which variables I should use? Thanks.

**Comment by peter-devoil** [comment]
A bit of manager code along the lines of
```
WaterSD = wheat.sw_supply / wheat.sw_demand
```
should do what you want. You might need to wrap it in a conditional (when the crop is alive/out), and also consider that the calculation occurs before the daily report has been made.

**Comment by KeLiu7** [comment]
> a conditional (when the cr

Thank Peter.  I have no idea how to make the calculation occurs before the daily report can be made.  I just tried with following codes and results are strange. The value should be between 0-1 but my results are too large. 

Could you please check it? Thanks.

_if wheat.sw_supply >0 and wheat.sw_demand >0 and wheat.zadok_stage>0 then
WaterSD = wheat.sw_supply / wheat.sw_demand
endif_

![image](https://user-images.githubusercontent.com/72141690/110260222-3dbe0100-7fe6-11eb-915b-7ee39654854d.png)

**Comment by peter-devoil** [comment]
When the plant is young, it requires very little water (ie biomass is small, demand is small), yet the supply is large (eg it's just rained, and roots are growing into wet soil) - so often the ratio is > 1. If that troubles you, just put a max() expression around it.
```
if wheat.zadok_stage>0 then 
   WaterSD = wheat.sw_supply / wheat.sw_demand
   if WaterSD > 1 then
      WaterSD = 1
   endif
endif
```

**Comment by peter-devoil** [comment]
When the plant is young, it requires very little water (ie biomass is small, demand is small), yet the supply is large (eg it's just rained, and roots are growing into wet soil) - so often the ratio is > 1. If that troubles you, just put a max() expression around it.

if wheat.zadok_stage>0 then 
   WaterSD = wheat.sw_supply / wheat.sw_demand
   if WaterSD > 1 then
      WaterSD = 1
   endif
endif

**Comment by KeLiu7** [comment]
> hat troubles you, just put a max() ex

Solved. Thanks!!
