### ISSUE TITLE
What happens when an array is added to a scalar

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2004]
We have this in one of the example APSIM files: totalNleach = totalNleach + flow_no3. However, flow_no3 seems to be an array. How does this work? And how can we get the last value in an array (e.g. flow out of the last layer of soil)?

**Comment by peter-devoil** [comment]
a) Probably a bug. The correct result would be to throw an error.
b) I'm not aware of a old style manager way to get the length of an array. Use manager2.

P

**Comment by BrianCollinss** [comment]
Thanks Peter. I am trying to calculate leaching in a C# manager. May I please know in what order managers are compiled?

![image](https://user-images.githubusercontent.com/39573622/110259513-c7c09680-7ff3-11eb-8197-86b5060b058a.png)

**Comment by peter-devoil** [comment]
C# should be telling you the shape of the variables being returned, so you can do something like
```
double [] flow_no3 = new double[20];
Paddock.Get("flow_no3", out flow_no3);
double leach = flow_no3[flow_no3.Length -1];
```
(apologies for incorrect specifics - today isn't a C# day for me)

They're compiled in loading order; but I think you're asking about order of execution - the order of modules that subscribe to the same event - which is specified in %Apsim%/Apsim.xml (there's a local copy made in %appdata%/settings/somewhere or other).

IIRC, manager2 isnt mentioned and thus falls to the end of the list - so a manager2's process event will always come after a crop (or manager1) process event.

P

**Comment by peter-devoil** [comment]
PS that calling order overrides the positioning in the simulation tree. If two 'peer' modules (ie have the same order) subscribe to the same event then the position in the tree determines the order they are called. But if they're different (eg crop & soil) then the position in the order list (from xml file) determines which is called first.
