### ISSUE TITLE
How to modify Soil when there is tillage?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2005]
In very older version of APSIM, we needed to write:

```
         surfaceom tillage type = trashinc()
         soilwat2 tillage type = trashinc()
```

How can we do the same now?

**Comment by peter-devoil** [comment]
All the tillage types are tabulated in the [surfaceom](https://github.com/APSIMInitiative/APSIMClassic/blob/1d3cc6128364b8a9f2fe9927954079a492272ca8/Model/SurfaceOM.xml#L723) and [soil](https://github.com/APSIMInitiative/APSIMClassic/blob/1d3cc6128364b8a9f2fe9927954079a492272ca8/Model/Soil.xml#L315) ini files. You can use a new ini file, of course..

You can just say 
```
act_mods tillage type = xyz
```
To send the message to all modules (provided they both understand what 'xyz' is).

**Comment by BrianCollinss** [comment]
But it does not accept Soil or SoilWater for the module.

**Comment by peter-devoil** [comment]
You need to use the "plugin" component to specifiy a new soil.xml

**Comment by BrianCollinss** [comment]
Adding a Plugin gives me this exception:

```
Error finding "Simulation=/simulations/Simulations" in apsim file C:\Users\jc837076\OneDrive - James Cook University\00_Projects\2021.03.01 INCENTIVE8\01_R\ApsimTemplates\Template INCENTIVE8 2021.03.01.apsim
System.Xml.XmlException: Root element is missing.
```

**Comment by peter-devoil** [comment]
I think it goes at the root of the tree, not in a simulation. It applies to all simulations

**Comment by BrianCollinss** [comment]
Still the same.

![image](https://user-images.githubusercontent.com/39573622/110554112-e3f43d00-8185-11eb-9607-7cfe074ccafc.png)

**Comment by peter-devoil** [comment]
Check any xml files you've added to the plugins for incorrect format?

**Comment by peter-devoil** [comment]
I took an example simulation (eg continuous wheat), added plugins, pressed go and it runs without error. What can be different for you?

The error you're getting indicates the ApsimToSim bit is failing

**Comment by BrianCollinss** [comment]
Oh, it must be under Simulation itself. Not the root. Thanks for the help Peter :) I'll play with it see if I get other errors.

**Comment by BrianCollinss** [comment]
OK. The problem was that I 'disabled' some of the modules and just kept Soil 'enabled'. It does not work that way.

Actually, my problem was with tillage and the fact that it does not work on Soil module. I see that in older versions a tillage operation could target OM module and soil water module. But I cannot do that in new one, not at least the same way.

```
     The module "soil" does not exist.
     Command: soil tillage type = disc()
     Component name: paddock.Tillage
```

**Comment by peter-devoil** [comment]
act_mods will send it to anybody listening, and save a lot of grief.

Should you wish to do it the hard way: The soil megamodule appends Water, Nitrogen to the name of the megamodule for each child. So, if your soil is called "Back Of Bourke", you want a message like
```
   'Back Of Bourke Water' tillage type = disc()
```
Use the bit at the top of the summary file (where it mentions dlls and names) to check the exact spelling

**Comment by BrianCollinss** [comment]
So you are saying I can literally replace (for example) [OMModule] with the word 'act_mods' and it applies 'tillage' operation on all the modules that can be tillaged?

**Comment by peter-devoil** [comment]
Yes. Try
```
act_mods tillage type = xyz
```
