### ISSUE TITLE
auto fertilization

### ISSUE THREAD

**Issue by charlie-ffff** [APSIMInitiative/APSIMClassic#2008]
Im conducting a seasonal experiment without N stress, so I want the N content in top 3 soil layer keep it above 150kg/hm.
I tried two ways, first, 
Using the _fertilise incrop on critical NO3 level top up_tools, however, it didnt work, cause I didnt saw the output variable **fertilizer** added.

![image](https://user-images.githubusercontent.com/79614073/110558856-2f0a5200-817e-11eb-896f-81ebe2c33dc2.png)

second,
using a script which could run without fatal error in APSIM7.9(still cannot auto fertilization), but couldnt run in APSIM7.10
`!!auto fertiliser!!  
NO3_available = no3(1) + no3(2) + no3(3)

HY_critical = 150
if (NO3_available <= HY_critical) then
 
fertiliser apply amount = 200(kg/ha), depth = 50 (mm), type = urea_N (kg/ha)

endif  `

**Comment by charlie-ffff** [comment]
how to set it to make the seasonal experiment without N stress

**Comment by peter-devoil** [comment]
That should work OK in 7.10 - can you post the error message pls?

**Comment by charlie-ffff** [comment]
@peter-devoil   Im sorry to disturb you again,
I used this code 
`!!auto fertiliser!!  
if (potato.plant_status = 'alive') then
	NO3_available = no3(1) + no3(2) + no3(3)
	HY_critical = 150
	N_deficit = HY_critical - NO3_available
	if (NO3_available <= HY_critical) then
		fertiliser apply amount = N_deficit (kg/ha), depth = 50 (mm), type = urea_N (kg/ha)
	endif  
endif`
and found some problems, 
First, it just fertilise from sowing to emergence, last for several days

![image](https://user-images.githubusercontent.com/79614073/110730457-7286be00-825b-11eb-813e-03bdd448041e.png)

Second, I cheked the soil NO3 content, it is incredible high, then I run apsim without using this module, it back to normal value
![image](https://user-images.githubusercontent.com/79614073/110730414-5edb5780-825b-11eb-9e64-242b54244407.png)

does there exists some problem in my auto fertilize script? 
here is my experiment file .

[auto fer .zip](https://github.com/APSIMInitiative/APSIMClassic/files/6120208/auto.fer.zip)

**Comment by peter-devoil** [comment]
I suspect the script is doing exactly as you tell it to. Note the behaviour of urea_N will be different to NO3_N - it takes a while (and a bit of water) to undergo hydrolysis. You may get clearer results if you change the fertiliser type.
