### ISSUE TITLE
Flow_NH4 and Flow_NO2 to calculate DIN (dissolved inorganic nitrogen)?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2010]
It seems APSIM SoilWat does not estimate NH4 leaching and NO2 emission (?). Is there any way we can estimate it in APSIM? Do I need to switch to SWIMM?

**Comment by peter-devoil** [comment]
Swim is always better, but few people have patience with its demands and quirky operation. Your question is "Is NH4/NO2 more important than a conservative, no surprises water balance"?

I think the module responsible for those two chemicals would be SoilN. You might want to see if @hut104 has changed / is about to change its behaviour in NextGen/Nutrient.

**Comment by BrianCollinss** [comment]
Do you recommend I switch to SWIMM? Would that need any extrat info/input(s) that I might not have handy?

**Comment by BrianCollinss** [comment]
I am learning a LOT working with cane :)) Is there any simpler way to calculate NH4/NO2 from SoilWat, PLEASE!??!

**Comment by peter-devoil** [comment]
Always good to be learning.. The chemistry here is out of my domain but I can say that SoilN is the module under question here, and it would function the same between swim and soilwat - all the water balance does is calculate a water flux/flow, the nutrient model moves (soluble) nutrients around.

**Comment by BrianCollinss** [comment]
Thanks Peter. Let's see if @hut104 can help me with this. Neil, hi, I always get zero for nh4 leaching. I need to calculate total DIN (dissolved inorganic N). What do you recommend? Why I get zero for nh4 no matter how much N and water I apply?

**Comment by hut104** [comment]
With soilwat, NH4 leaching is always zero as it assumes that all NH4 is adsorbed.  Are you dealing with a soil that requires NH4 leaching?  You can capture NH4 fluxes for clay soils via adsorption isotherms in SWIM. It is used for high NH4 input systems such as urine patches.

You probably don't need to worry about NH4 movement.

**Comment by BrianCollinss** [comment]
I don't think our soils fall into the that class as we work on Cane. I agree that the NH4 movement is negligible. I just wanted to make sure those zeroes are not related to a problem.
