### ISSUE TITLE
Yield = absolute dry weight?

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#2011]
As the title says, is yield output for crops the absolute dry weight (i.e., 0% water)? Specifically I'm looking at maize and soybean, which are typically 15% and 13% water content at market, respectively, so I'm curious if I need to add water back into APSIM yield estimates.

**Comment by peter-devoil** [comment]
Yes, with very rare exceptions, all weights in apsim are dry weights. If you look closely, you'll see water content is not modelled, thus any estimate of wet weight would not be based on chemistry / physics, but on empirical relationships (which aren't bad, but...).

**Comment by mnowatzke** [comment]
Thank you, @peter-devoil!

**Comment by byzheng** [comment]
There should be two variables in the report
yield for dry weight
yieldwet for weight for specific water content.

See here: https://github.com/APSIMInitiative/APSIMClassic/blob/c6f5c06f60ae0f6529c4e0094d59950259ef7acf/Model/Plant/Reproductive/GrainPart.cpp#L43
