### ISSUE TITLE
How to calculate a simple moving average for plant available water?

### ISSUE THREAD

**Issue by caityp** [APSIMInitiative/APSIMClassic#2015]
Hi APSIM crew,

I am studying dryland winter grain production in California, specifically, the risk that a crop will fail to establish under low-water conditions.

I would like to calculate a simple moving average of PAW in the top soil layer, so that for example:
If mean PAW over the past 5 days is less than 50% of total PAWC, then the crop dies. 
Even better if I can create a dummy variable to track the number of times that mean PAW drops below the threshold, and kill the crop when the number of times reaches a specified max. In other words, if PAW dips below the threshold 4 times then the crop is still alive, but it dips below the threshold a 5th time then it dies.
This would be in the early juvenile stages of crop development (less than 75 days after sowing) before sw deficit indices really begin to kick in.

I currently have my simulation set up so that a number of criteria must be met for the crop to stay alive. In the below code, you'll see that at specific days after sowing, I have the system checking that:
1) cumulative rain + irrigation over the past x days is less than a threshold amount; AND
2) sw_dep[1] - ll_dep[1] < 50% of total PAWC for a given depth 
If both conditions are met, then APSIM kills the crop. If only one or neither is met, the crop stays alive.

I would like to change the second condition to be based on a 5-day moving average of PAWC so that I can check water status daily rather than at rather arbitrary points in early development (e.g., 5, 15, 45, and 75 days after sowing).
So the new rule would be something like:

If rain + irrigation over the past 5 days < [amount] OR
if on 5 separate days the 5-day moving average of sw_dep[1] - ll_dep[1] < 50% of PAWC
THEN crop dies.

Any ideas or perhaps existing example scripts I could draw from? I am not an experienced C# coder and have been mostly editing existing manager rules to get this far.  THANKS!

Current approach is pasted below and example .apsim file is attached. Using APSIM Classic v7.10.
[westside_wheat_example.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6150993/westside_wheat_example.zip)

  
//////////////////
```
public class Script 
   {      
      [Link] public Simulation MySimulation;
      [Input] DateTime today;
      [Input] double rain;
      [Input] double irrigation;
      [Input] double DaysAftersowing;
      [Input] double[] ll_dep;
      [Input] double[] dul_dep;
      [Input] double[] sw_dep;
      [Param] private string crop;  // module name of this crop
      [Param] int pastDays; // number of days over which to check for rain/irrig
      [Param] float amount;      //amount of rain + irrigation required within the window
      [Param] float pct_sowing;   // proportion of PAWC required at sowing
      [Param] float pct_estab;   // proportion of PAWC required after sowing
      [Param] int maxlayer;
      [Output] double cumrain;
      [Output] double cumirrig;
      [Output] double totalPAWC;


   private List<double> trackerRain = new List<double>();
   private List<double> trackerIrrig = new List<double>();
 
   // check max layer at the start of the simulation
   [EventHandler] public void OnInitialised()
   {
      if (maxlayer > dul_dep.Length)
      {
         Console.WriteLine("Warning: max layer is greater than number of layers.");
         Console.WriteLine("Using full profile for soil water deficit calculations.");
         maxlayer = 0;
      }
   }
      
   
 // calculate total PAWC at beginning of each day 
   [EventHandler] public void OnPrepare()
   {
      double[] PAWC = new double[dul_dep.Length];
      for (int i = 0; i < (maxlayer > 0 ? maxlayer : dul_dep.Length); i++)
      {
         PAWC[i] = Math.Max(0.0, dul_dep[i] - ll_dep[i]);
      }
      totalPAWC = MathUtility.Sum(PAWC);

   }
      
   
   // sum rain and irrigation at the end of each day
   [EventHandler] public void OnPost()
   { 
      trackerRain.Add(rain);
      trackerIrrig.Add(irrigation);
      
      if(trackerRain.Count > pastDays){
         
         trackerRain.RemoveAt(0);
         trackerIrrig.RemoveAt(0);
      }
         
      cumrain = 0;
      cumirrig = 0;

      
      foreach(double d in trackerRain)
      {
         cumrain += d;
      }

      foreach(double d in trackerIrrig)
      {
         cumirrig += d;
      }
      
      
      // if sum of rain and irrigation by x days after sowing is less than y amt,
      // AND PAW in top layer is < y% of total PAWC in that layer, then kill the crop
      if ((cumrain + cumirrig < (amount) && ((sw_dep[1]-ll_dep[1]) < (pct_sowing * totalPAWC)) && DaysAftersowing == 5) ||
         (cumrain + cumirrig < (amount) && ((sw_dep[1]-ll_dep[1]) < (pct_estab * totalPAWC)) && DaysAftersowing == 15) ||
         (cumrain + cumirrig < (amount) && ((sw_dep[1]-ll_dep[1]) < (pct_estab * totalPAWC)) && DaysAftersowing == 45) ||
         (cumrain + cumirrig < (amount) && ((sw_dep[1]-ll_dep[1]) < (pct_estab * totalPAWC)) && DaysAftersowing == 75))
         {
            Console.WriteLine(today + " Killing Crop");
            KillCropType kdata = new KillCropType();
            kdata.KillFraction = 0.0F;
            string currentPaddock;
         
            MySimulation.Get("currentPaddock", out currentPaddock);
            Component cropModule;
            if (currentPaddock != "")
               cropModule = (Component) MySimulation.LinkByName(currentPaddock + "." + crop);
            else 
               cropModule = (Component) MySimulation.ChildPaddocks[0].LinkByName(crop);

            cropModule.Publish("killcrop", kdata);
            cropModule.Publish("end_crop");
         }
      }
   }

```

**Comment by peter-devoil** [comment]
Congratulations - you are nearly there - but... I suspect mixing the single layer calculation of SW with the summed profile isnt what you intend. For an equitable comparison between soils of differing layer structures, you need to compare like with like. "X%" of a soil describes X percent of its capacity, not the X proportion in one layer to a total capacity. In your case, the
```
 ...  ((sw_dep[1]-ll_dep[1]) < (pct_sowing * totalPAWC)) ...
``` 
term is going to give you grief.

I think your simplest path would be to duplicate the existing tracker logic for the esw calculation:
```
private List<double> trackerESW = new List<double>();
...
trackerESW.Add( Math.Min(0.0, Math.Max(1.0, (sw_dep[1]-ll_dep[1]) / (dul_dep[1] - ll_dep[1]))) ) ;
if(trackerESW.Count > pastDays){
         trackerESW.RemoveAt(0);
}
double ESWSum;
foreach(double d in trackerESW)   { ESWSum += d; }
double ESWAvgFrac = ESWSum / (double) trackerESW.Count;
```
Now you can use the fractional calculation in the if expression:
```
if ( (cumrain + cumirrig < amount) && (ESWAvgFrac < pct_sowing ) && (DaysAftersowing == 5)) ...
```      

If you want to implement a counter, you need some extra logic at sowing to reset the counter:
```
private int numSeen = 0;
[EventHandler] public void OnSowing()
{
   numSeen = 0;
}

...
  if ( ESWAvgFrac < pct_sowing ) { numSeen++; }
...
  if (numSeen > someArbitraryThreshold) {
            cropModule.Publish("end_crop"); // etc
  }

**Comment by caityp** [comment]
Pete, thanks for this help. I've taken a stab at implementing your suggestion of using a tracker method similarly to how I'm tracking rain and irrigation accumulation. 

You'll see that I'm actually using two "counters" to track the number of times that ESWavgfrac is either below or exceeds a threshold. There has to be at least 1 wet day (>75% PAWC) by 15 days after sowing, and no more than 5 dry days (<50% PAWC) by 60 d.a.s. or the crop is killed.

However, I think I'm missing something as my "moving average" output, ESWavgfrac in the code below, **stays at 0.0 for the whole simulation**. Maybe I missed a line to assign a new variable or something along those lines?

Here's what my code looks like now:

```
public class Script 
{      
   [Link] public Simulation MySimulation;
   [Input] DateTime today;
   [Input] double rain;
   [Input] double irrigation;
   [Input] double DaysAftersowing;
   [Input] double[] ll_dep;
   [Input] double[] dul_dep;
   [Input] double[] sw_dep;
   [Param] private string crop;  // module name of this crop
   [Param] int pastDays;   // number of days over which to average PAW 
   [Param] float amount;      //amount of rain + irrigation required within the window
   [Param] float pct_sowing;   // fraction of PAWC required at sowing
   [Param] float pct_estab;   // fraction of PAWC required after sowing
   [Param] int allowedDays;   // number of days that ESW can dip below threshold before crop dies
   [Output] double cumrain;
   [Output] double cumirrig;
   [Output] int numWetDays;
   [Output] int numDryDays;
   [Output] double ESWsum;
   [Output] double ESWavgfrac;
   

   // set up rain, irrigation, and ESW trackers
   private List<double> trackerRain = new List<double>();
   private List<double> trackerIrrig = new List<double>(); 
   private List<double> trackerESW = new List<double>();
  
   // on sowing, reset the ESW threshold counters
   [EventHandler] public void OnSowing()
   {
      numWetDays = 0;
      numDryDays = 0;
   }
      
     // calculate fraction avail soil water at the end of each day

    [EventHandler] public void OnPost()
   { 
      trackerESW.Add(Math.Min(0.0, Math.Max(1.0, (sw_dep[1] - ll_dep[1]) / (dul_dep[1] - ll_dep[1]))));
      
      if(trackerESW.Count > pastDays){
         trackerESW.RemoveAt(0);
         }
      
      ESWsum = 0;
      
      foreach(double d in trackerESW) {ESWsum += d;}
      ESWavgfrac = ESWsum / (double) trackerESW.Count;
      
      // add to counter if ESW falls above germination threshold or below establishment threshold
      
      if(ESWavgfrac >= pct_sowing) {numWetDays++;}
      if(ESWavgfrac < pct_estab) {numDryDays++;}
      
      
    // sum rain and irrigation at the end of each day
      trackerRain.Add(rain);
      trackerIrrig.Add(irrigation);
      
      if(trackerRain.Count > pastDays){
         
         trackerRain.RemoveAt(0);
         trackerIrrig.RemoveAt(0);
      }
         
      cumrain = 0;
      cumirrig = 0;

      
      foreach(double d in trackerRain)
      {
         cumrain += d;
      }

      foreach(double d in trackerIrrig)
      {
         cumirrig += d;
      }     

      
      // FOR CROP TO SURVIVE:
      // germination rule: PAW must hit max frac of PAWC at least once by x das
      // establishment rule: PAW can't dip below fraction of PAWC threshold more than x times
      // OR sum of rain and irrigation over past 5 days must be > x amt (i.e., recent rain will save the crop)
      
      if((cumrain + cumirrig < (amount) && (numWetDays < 1) && DaysAftersowing <= 15) ||  //germination rule
         (cumrain + cumirrig < (amount) && (numDryDays >= allowedDays) && (DaysAftersowing > 15 || DaysAftersowing <= 60)))  //establishment rule
      {
         Console.WriteLine(today + " Killing Crop"); etc. etc. }
}}
```

**Comment by peter-devoil** [comment]
Silly me. Try:
```
 trackerESW.Add(Math.Max(0.0, Math.Min(1.0, (sw_dep[1] - ll_dep[1]) / (dul_dep[1] - ll_dep[1]))));
```
(ie swap the max & min)

My apologies for leading you astray..

**Comment by caityp** [comment]
Thanks! Swapping the Max and Min expressions solved the issue of ESWfrac always turning up as 0 - I definitely missed that! However, I'm still running into a bit of a glitch with the calculation of ESW.

If I calculate the ESW expression (sw_dep[1] - ll15_dep[1]) / (dul_dep[1] - ll15_dep[1]) by hand, I get daily ESW fractions of 0.250, 0.247, 0.245, 0.243 etc. But when calculated within the ESW tracker I get fractions (before summing) of 0.252, 0.252, 0.252, 0.252 etc. 
The summation (ESWsum) and 5-day average (ESWavgfrac) functions appear to be working fine, but they are based on incorrect ESW fractions. 

Here's an example of my output file. The variable "ESWfrac" is simply the ESW expression in isolation so I can check that it is calculating correctly. 

![image](https://user-images.githubusercontent.com/34069107/112032739-51975600-8b02-11eb-9ac5-f46398df169e.png)

You'll see that ESWfrac is not capturing the big jump in soil water content observed around 10/10 and 11/10. Also, ESWfrac is always increasing, whereas it should be tracking the rising and falling of sw_dep over time. However, ESWsum and ESWavgfrac are correct in relation to ESWfrac.

Any idea what's going on here?

**Comment by peter-devoil** [comment]
Try adding a Console.WriteLine(...) to be sure the array is being handled correctly (ie length is constant)

**Comment by caityp** [comment]
The array handling might well have been the issue. Was able to get it to calculate correctly by calculating fraction of available soil water independently as a full array, giving it a maximum soil layer parameter so it would know what depth to calculate to. 
Saving the sum of that array output to a vector variable and using that variable in subsequent calculations gave me the right values.

   
```
    [EventHandler] public void OnPost()
   { 
      double[] fasw = new double[dul_dep.Length];
 
      for (int i = 0; i < (maxlayer > 0 ? maxlayer : dul_dep.Length); i++)

      {
          fasw[i] = Math.Max(0.0, Math.Min(1.0, (sw_dep[i] - ll15_dep[i]) / (dul_dep[i] - ll15_dep[i])));
      }  
      
      ESWfrac = MathUtility.Sum(fasw);
      
      trackerESW.Add(ESWfrac);
         
      if(trackerESW.Count > pastDays)
     {
         trackerESW.RemoveAt(0);
      }
      
      ESWsum = 0;
      
      
      foreach(double d in trackerESW) 
      {
            ESWsum += d;
      }
      
      ESWavgfrac = ESWsum / (double) trackerESW.Count;   
}
```

Thanks for helping me get there!!
