### ISSUE TITLE
How to feed a variable like "irr_amt" into irrigation apply amount = irr_amt

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2018]
I need to do this in Manager (not Manage2), but I get this error:

```
     Cannot parse float from string "irr_amt"
     Component name: paddock.Irrigation
```

**Comment by BrianCollinss** [comment]
Hi @hol430 . Wonder if you know how to deal with this situation?

**Comment by JodyBig** [comment]
Maybe I can help. Can you send me the Manager code?

**Comment by BrianCollinss** [comment]
Thanks @JodyBig , 

I have a lot of lines with:

`irrigation apply amount = irr_amt`

where irr_amt is calculated inside the code. But it seems **irrigation** does not accept numbers. It requires strings.

```
if ratoon_no = 0 then
		   if sugardas = 2  then
              		 irrigation apply amount = irr_amt
			  cumirr = cumirr + irr_amt
			  sinceirrig = 0
		   endif
endif
```

**Comment by JodyBig** [comment]
Can you share the code where you calculate irr_amt.
I don't seem to have the same problem. See example (from V7.10) below.

`          	! perform crop salvation if necessary
            if (sugar.DaysAfterSowing = 35) and (sugar.stage &lt; 2) then
              irrigation apply amount = 40, will_runoff = 1
              cropIrrig = cropIrrig + 40
              CropSalvation = CropSalvation + 1
            endif
              
            if (sugar.DaysAfterSowing &gt; (ratoonlen - dryoff) and ratoon_no &gt; 0) or (cropIrrig &gt;= irrig_alloc) then
              if automatic_irrigation = 'on' then
                irrigation.automatic_irrigation = 'off'
              endif
            else
              ! calc remaining allocaiton and reduce application rate if necessary
              alloc_remaining = irrig_alloc - cropIrrig
              if alloc_remaining &lt; irr_max then
                irr_amt = alloc_remaining
              else
                irr_amt = irr_max
              endif
                            
              ! countdown rain delay
              if delaycount &gt; 0 then
                delaycount = delaycount - 1
              endif
              
              !establishment irrigation
              if delaycount = 0 then
                if ratoon_no = 0 then
                  if sugar.DaysAfterSowing = 6 and sugar.fasw &lt; 0.7 then
                    irrigation apply amount = irr_amt, will_runoff = 1
                    cropIrrig = cropIrrig + irr_amt
                    delaycount = 14
                  elseif sugar.DaysAfterSowing &gt; 184 and sugar.fasw &lt; fasw_trig then
                    irrigation apply amount = irr_amt, will_runoff = 1
                    cropIrrig = cropIrrig + irr_amt
                    delaycount = 14
                  endif
                else
                  if sugar.DaysAfterSowing = 30 and sugar.fasw &lt; 0.4 then
                    irrigation apply amount = irr_amt, will_runoff = 1
                    cropIrrig = cropIrrig + irr_amt
                    delaycount = 14
                  elseif sugar.DaysAfterSowing &gt; 123 and sugar.fasw &lt; fasw_trig then
                   irrigation apply amount = irr_amt, will_runoff = 1
                   cropIrrig = cropIrrig + irr_amt
                   delaycount = 14
                  endif
                endif
              endif
            endif`

**Comment by BrianCollinss** [comment]
Thanks Jody. irr_amt comes from a C# manager:

```
   [Output] int irr_amt;
.
.
.
      else if (IrriRate == "W2") {
         irr_amt = 80;
         fullreset = 100; //mm
         fulldelay = 100; //days
         halfreset = 50; //mm
         halfdelay = 7; //days
         rainreset = 30; //mm
         raindelay = 5; //days
```

**Comment by JodyBig** [comment]
Oh.
Sorry but I can't really help with the C# manager (i.e. Manager2) side of things.
The obvious work-around: Maybe use the IrriRate to specify the irr_amt within the apsim manager(1) code.
Otherwise, hopefully a APSIM C# guru will contribute a better solution.

**Comment by BrianCollinss** [comment]
I am not sure if I tried that. But I will one more time anyway. Cheers.

**Comment by hol430** [comment]
> Hi @hol430 . Wonder if you know how to deal with this situation?

No idea sorry. You would need someone who knows old apsim.

**Comment by BrianCollinss** [comment]
It's really strange! I am doing exactly the same as your code, but I still get that error:

```
		   if sugardas = 2 or sugardas = 16 or sugardas = 30 or sugardas = 44 or sugardas = 58 or sugardas = 93 then
		      irr_app = irr_amt
		      irrigation apply amount = irr_app
			  cumirr = cumirr + irr_amt
			  sinceirrig = 0
		   else 
		      irr_app = 0		
		   endif
```

Another suprise is that it seems it works for one day, but not for the other:

```
16 July 2000(Day of year=198), paddock.IrrigEst: 
     Manager sending message :- irrigation apply  amount = 150.00000
12 August 2000(Day of year=225), paddock.Irrig: 
     Manager sending message :- irrigation apply  amount = irr_app
13 August 2000(Day of year=226): 
```

**Comment by byzheng** [comment]
copy your script into notepad++ to see any special characters, e.g. tab, end of line

**Comment by BrianCollinss** [comment]
Actually I do most of the changes in Notepad++ and then open with APSIM and run. I don't see any special character.

**Comment by jbrider** [comment]
The following line indicates it is being passed a string, not a number.
``` Manager sending message :- irrigation apply  amount = irr_app ```

Is irr_app being initialised before it is called in all situations?
Is irr_amt being initialised before it is called in all situations?
Is the code you provided the only place you are assigning a value to irr_app?

It's tcl so there is no type checking that the variable is a string or a numebr.

**Comment by BrianCollinss** [comment]
Thanks @jbrider. I think the issue is that **irr_amt** comes from a Manager2 script. That is the only difference between my code and Jody's. 

**irr_app** is also initiated. Actually I am not sure why it is needed. I am just using it to pass irr_amt to something else to perhaps fix the problem. So, it is not being assigned anywhere else.

**Comment by BrianCollinss** [comment]
[Template INCENTIVE8 2021.03.23.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6193490/Template.INCENTIVE8.2021.03.23.zip)

Here is my APSIM file. Everything is in Manager, SugarManager, IrrigEst and Irrig.

**Comment by jbrider** [comment]
I would try initialising irr_amt in Manager to something unusual (99999) to see if that makes a difference.

**Comment by BrianCollinss** [comment]
```
     The module Irrig has asked for the value of the variable irr_amt.
     It received multiple responses when only 1 was expected.
     It received values from the following modules:
        paddock.IrrigEst
        paddock.Manager
     
     Component name: paddock.Irrig
```

**Comment by jbrider** [comment]
whatever you did(?) forced an error which tells you that it's not clear where irr_amt is coming from.
I would assume that merging  IrrEst and Irrig together would remove the error.

**Comment by BrianCollinss** [comment]
It did. Cheers mate!
