### ISSUE TITLE
Suggestion on a generic crop model to be used in horticulture crop modelling 

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/APSIMClassic#2019]
Dear All

We are going to do some modelling work (water and N balance modelling) associated with horticultural cropping systems such as avocado, banana, chilies by using Apsim 7.10 . Given the specific crop modules are not available in the Apsim package at the moment, can we use slurp as a substitute? if no, what generic crop model can you suggest? 

Thanks in advance!

 qunying

**Comment by peter-devoil** [comment]
Slurp is nice if you don't want plant dynamics getting in the way of your water balance. With a bit of manager script, you can force it to look like a seasonal growth curve. There is a simple "tree" module in [nextgen](https://github.com/APSIMInitiative/ApsimX/issues/3801) that follows that path.

**Comment by qluo02** [comment]
Thanks, peter!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by qluo02** [comment]
@peter-devoil 

Hi Peter

Do you mean the simple "tree" module in nextgen is the slurp model?

 regards 

qunying

**Comment by peter-devoil** [comment]
Functionally, I don't think there was a lot of difference. Best to have a look for yourself, and ask @HamishBrownPFR for more details.
