### ISSUE TITLE
PlugIn does not load the target files, it seems

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2020]
I am using a Plugin to add a number of tillage options:

![image](https://user-images.githubusercontent.com/39573622/112233273-da8aca80-8c85-11eb-98e8-f6615f656190.png)

But I still get warnings regarding missing definitions of these operations:

![image](https://user-images.githubusercontent.com/39573622/112233304-ed9d9a80-8c85-11eb-9e9d-b8b572df393f.png)

Here are my Soil.xml and SurfaceOM.xml.
[ApsimTemplates.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6193402/ApsimTemplates.zip)

**Comment by BrianCollinss** [comment]
@jbrider You have seen my file I think. Do you have any solution for this as well?

**Comment by JodyBig** [comment]
Can you provide the command you are using?

**Comment by BrianCollinss** [comment]
I am running from inside the GUI

**Comment by jbrider** [comment]
You have told it to reload every plugin possible - is that how it is supposed to work?
I haven't used plugins before, and as there is an option to reload them at runtime I'm not sure what you're trying to achieve with them? 
Plugins should be dll's (someone might correct me on that) - have you got recompiled dll's for soil, surfaceOM and sugar, or just updated xml files?

**Comment by BrianCollinss** [comment]
Just XMLs. As I needed to add more tillage types, I needed to have my own XMLs so the default ones be intact.

**Comment by jbrider** [comment]
Sugar should work with an ini component... I can see you added one but didn't specify a file.
I would try similar with surfaceOM, and soil but I'm not 100% sure where to add one to soil.
I would also test updating the file to see if that even works - I noted a comment about updating another ini file that doesn't exist so maybe there is a 2nd place it needs to be updated?
I would test that it works on the source xml file first, then once you get that working you can test different places to add the ini component.

**Comment by BrianCollinss** [comment]
Yes. I ll do these. I too noticed that residue2 ini file but I cannot find it anywhere. It seems like an obsolete thing.

**Comment by JodyBig** [comment]
residue2.ini should be equivalent to SurfaceOM.xml.

**Comment by BrianCollinss** [comment]
I have those tillage in SurfaceOM as well. But APSIM cannot find them in either files.

**Comment by JodyBig** [comment]
Can you send me the apsim, met and xml files and I'll have a closer look.

**Comment by BrianCollinss** [comment]
[ApsimTemplates.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6201282/ApsimTemplates.zip)
 Ta

**Comment by JodyBig** [comment]
Hi Brian

I couldn't run your sims without hitting other errors (i.e. runoff error) but looking at the manager(1) code related to tillage I see this: 
act_mods tillage type = DDOP()

I'm not familiar with act_mods.

Could you replace it with two commands like the following and see if that fixes it.
'SurfaceOrganicMatter' tillage type = DDOP()
'Soil Water' tillage type = DDOP()

I also noted that you are using both PlugIns and ini nodes. Maybe choose one method and disable the other nodes.

**Comment by BrianCollinss** [comment]
According to Peter Devoil, it finds all the modules that can be touched by Tillage and performs the operation on them. If you see my other Issue, Tillage is never performed currently. I tried many things.

**Comment by JodyBig** [comment]
Hi Brian
I just created a simple example using the sugar template (attached) with tillage performed via gui and via operations, together with a plugin and it all looks like it works. ???

[20210325.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6201572/20210325.zip)

**Comment by BrianCollinss** [comment]
I get this:

```
     The module SurfaceOrganicMatter has asked for the value of the variable eos.
     It received no responses.
     Component name: paddock.SurfaceOrganicMatter
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by BrianCollinss** [comment]
Why can't we run each other's files?! Are you on 7.10?

**Comment by JodyBig** [comment]
Sorry. I forgot to mention that the plugin uses absolute paths instead of relative paths. Very frustrating.
Remove my plugin xml (at the bottom) and then re-add it.

**Comment by BrianCollinss** [comment]
Thanks. I am getting the same warnings:

```
                      APSIM Warning Error
                      -------------------
     Cannot find info for tillage:- disc
     Component name: paddock.Soil Water
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     Soil tilled using disc
                                             CN reduction =     0.00
                                             Acc rain     =     0.00
```

**Comment by JodyBig** [comment]
Very strange???
The only other thing I can think (I'm stretching here) is your folder path (in the plugin) is causing problems.
How to test: Revert to default xml or copy to a simplier folder path.

My version details.
Version 7.10; Build date: 29-Mar-2018; Build number: 4518

**Comment by BrianCollinss** [comment]
I am using the latest version: Apsim7.10-r4217
from https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx

**Comment by BrianCollinss** [comment]
OK. I re-downloaded the latest version and it is fine now!!! Let me see if I can find out what is happening.
