### ISSUE TITLE
How to optimize APSIM model parameters by using APSIM wheatphilosophy

### ISSUE THREAD

**Issue by dxl-cde** [APSIMInitiative/APSIMClassic#2022]
If I want to tune the model parameters, how should I use the files in this package? Do I need to rewrite the code? Thank you very much.

Is it the following method? Is it a method or a variety of methods? Do you need to add other code?

met <- system.file("extdata/weather.met", package = "APSIMWheatPhenology")
#' sim <- system.file("extdata/example.sim", package = "APSIMWheatPhenology")
#' # Flowering time using parameter in the sim file
#' df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'APSIM',
#'                      met = met, daily = FALSE)
#' head(df)
#'
#' # Models V1 or V2 can be used
#' df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'V1',
#'                      met = met, daily = FALSE)
#' head(df)
#'
#' # Weather can be passed as a weaana object
#' met_data <- weaana::readWeatherRecords(met)
#' df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'APSIM',
#'                      met = met_data, daily = FALSE)
#' head(df)
#'
#' # Multiple stages can be calculated
#' df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
#'                      model = 'APSIM',
#'                      met = met_data, daily = FALSE)
#' head(df)
#'
#' # Daily output can be exported
#' df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
#'                      model = 'APSIM',
#'                      met = met_data, daily = TRUE)
#' head(df)
#'
#' # Multiple simulations can be specified in a factor
#' # Any parameters related with plant can be used
#' factors <- expand.grid(list(vern_sens = seq(1, 5), photop_sens = seq(1, 5)))
#' df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
#'                      model = 'APSIM',
#'                      met = met_data, daily = FALSE,
#'                      factors = factors)
#' head(df)

This is the result of running the code above
 met <- system.file("extdata/weather.met", package = "APSIMWheatPhenology")
> sim <- system.file("extdata/example.sim", package = "APSIMWheatPhenology")
> # Flowering time using parameter in the sim file
> df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'APSIM',
+                      met = met, daily = FALSE)
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }                                           
> 
> # Models V1 or V2 can be used
> df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'V1',
+                      met = met, daily = FALSE)
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }                                           
> 
> # Weather can be passed as a weaana object
> met_data <- weaana::readWeatherRecords(met)
> df <- wheatPhenology(sim, stages = 6, stageNames = 'flow', model = 'APSIM',
+                      met = met_data, daily = FALSE)
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }                                           
> 
> # Multiple stages can be calculated
> df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
+                      model = 'APSIM',
+                      met = met_data, daily = FALSE)
Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat'
此外: Warning message:
In .local(object, ...) :
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }                                           
> 
> # Daily output can be exported
> df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
+                      model = 'APSIM',
+                      met = met_data, daily = TRUE)
Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat'
此外: Warning message:
In .local(object, ...) :
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 }                                           
> 
> # Multiple simulations can be specified in a factor
> # Any parameters related with plant can be used
> factors <- expand.grid(list(vern_sens = seq(1, 5), photop_sens = seq(1, 5)))
> df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
+                      model = 'APSIM',
+                      met = met_data, daily = FALSE,
+                      factors = factors)
Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat'
此外: Warning message:
In .local(object, ...) :
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  找不到对象'crown_temp_nwheat' > head(df)
                                              
1 function (x, df1, df2, ncp, log = FALSE)    
2 {                                           
3     if (missing(ncp))                       
4         .Call(C_df, x, df1, df2, log)       
5     else .Call(C_dnf, x, df1, df2, ncp, log)
6 } 
Thank you for your help！

**Comment by byzheng** [comment]
Do you use the latest version of apsimwheatphenology? I believe this function is exist in the package. All checking has passed.

Please ask question for APSIMWheatPhenology here: https://github.com/APSIMInitiative/APSIMWheatPhenology/issues

**Comment by dxl-cde** [comment]
> 您是否使用最新版本的apsimwheatphenology？我相信此功能已存在于包装中。所有检查均已通过。
> 
> 请在此处询问有关APSIMWheatPhenology的问题：[https](https://github.com/APSIMInitiative/APSIMWheatPhenology/issues) : [//github.com/APSIMInitiative/APSIMWheatPhenology/issues](https://github.com/APSIMInitiative/APSIMWheatPhenology/issues)
Thanks very much
