### ISSUE TITLE
Model parameter optimization

### ISSUE THREAD

**Issue by dxl-cde** [APSIMInitiative/APSIMClassic#2023]
How to use this package to optimize parameters. Thank you very much.Which file should I use? Is it in the file name called test? @jbrider @byzheng @peter-devoil @hol353 @mcleang

**Comment by byzheng** [comment]
please ask related question here: https://github.com/APSIMInitiative/APSIMWheatPhenology/issues


i am working on examples, but will tske some time. alternative you can use this package: https://github.com/SticsRPacks/CroptimizR


you will need to wrap your own function for observation as a normal optimization.

wheatphenology just improve the computing speed.

**Comment by dxl-cde** [comment]
Thank you very much !
