### ISSUE TITLE
Apsim parameter optimization

### ISSUE THREAD

**Issue by dxl-cde** [APSIMInitiative/APSIMClassic#2024]
This is my code:(From Apsimwheatphenology)
met <- system.file("extdata/weather.met", package = "APSIMWheatPhenology")
sim <- system.file("extdata/example.sim", package = "APSIMWheatPhenology")
factors <- expand.grid(list(vern_sens = seq(1, 5), photop_sens = seq(1, 5)))
 df <- wheatPhenology(sim, stages = c(5.74, 6), stageNames = c("head", 'flow'),
                     model = 'APSIM',
                     met = met_data, daily = FALSE,
                     factors = factors)
head(df)

run result:
Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  Object not found'crown_temp_nwheat'
In addition: Warning message:
In .local(object, ...) :
 Error in weaana::wcal(met, FUN = crown_temp_nwheat, var.args = c("maxt",  : 
  Object not found'crown_temp_nwheat' 
Thanks very much

**Comment by byzheng** [comment]
Do you use the latest version of apsimwheatphenology? I believe this function is exist in the package. All checking has passed.

Please ask question for APSIMWheatPhenology here: https://github.com/APSIMInitiative/APSIMWheatPhenology/issues

**Comment by dxl-cde** [comment]
> 您是否使用最新版本的apsimwheatphenology？我相信此功能已存在于包装中。所有检查均已通过。
> 
> 请在此处询问有关APSIMWheatPhenology的问题：[https](https://github.com/APSIMInitiative/APSIMWheatPhenology/issues) : [//github.com/APSIMInitiative/APSIMWheatPhenology/issues](https://github.com/APSIMInitiative/APSIMWheatPhenology/issues)

thanks very much
