### ISSUE TITLE
APSIM wheat-maize rotation

### ISSUE THREAD

**Issue by XijuanXu** [APSIMInitiative/APSIMClassic#2025]
Dear sir. When I ran the APSIM model, I encountered a very puzzling problem.Many times, the maize has flowering days and maturity days, but no grain yield. Thank you for your answer. Thank you again!

**Comment by sarahcleary** [comment]
@GregMcLean-UQ ; @jbrider - any suggestions?

**Comment by GregMcLean-UQ** [comment]
If you would like to contact me directly on g.mclean@uq.edu.au I will see if I can help.

**Comment by Emanuel12138** [comment]
I also encountered a similar problem, have you solved it?
