### ISSUE TITLE
N deposition in APSIM

### ISSUE THREAD

**Issue by 20091108wl** [APSIMInitiative/APSIMClassic#2026]
Dear all,
Can I ask how to add N deposition from atomosphere in APSIM?  I want to consiser the effect of increased N deposion since studies predicted that N deposition will increase obviously in the future.
I checked soil.xml, soilN.xml, however, I didn't find the path to add dry deposion  or  wet depositon(along with precipitation).
 Looking forward to your answer.

**Comment by peter-devoil** [comment]
There is a feature to add solutes ("rainfall_xxx_conc", described inthe [water balance documentation](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soilwat/) ) - but N isn't handled by the solute module, so I doubt that's going to work. You could try writing some manager logic to add fertiliser on rainfall days?

**Comment by 20091108wl** [comment]
Thanks for your suggestion. I’ll have a try.发自我的iPhone------------------ Original ------------------From: Peter de Voil  ***@***.***>Date: Thu,Apr 1,2021 7:36 AMTo: APSIMInitiative/APSIMClassic ***@***.***>Cc: 20091108wl ***@***.***>, Author ***@***.***>Subject: Re: [APSIMInitiative/APSIMClassic] N deposition in APSIM (#2026)
There is a feature to add solutes ("rainfall_xxx_conc", described inthe water balance documentation ) - but N isn't handled by the solute module, so I doubt that's going to work. You could try writing some manager logic to add fertiliser on rainfall days?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/APSIMInitiative/APSIMClassic/issues/2026#issuecomment-811532848",
"url": "https://github.com/APSIMInitiative/APSIMClassic/issues/2026#issuecomment-811532848",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
