### ISSUE TITLE
failed simulate 

### ISSUE THREAD

**Issue by charlie-ffff** [APSIMInitiative/APSIMClassic#2027]
I'm conducting a rainfed experiment, the simulation ended when crop stage only reached to 5, 

when I give it 15mm on the dates it ended last time, the simulation finished, 

howerver, yield was extremly low, like 0.2 g/m2, sw_stress_photo of both abovementioned simulation was 0. 

when I turn on the automatic irragation, simulation compeleted with a normal yield and sw_stress_photo also had values .

I know its water deficit causing failed simulation, but my field experiment was rainfed, only irrageted when it near death, so i wandering how to set the irragation rule?

**Comment by XijuanXu** [comment]
I have the same problem. Does irrigation also need to be carried out under maize rain-fed experiment? If I didn't irrigate, many years the crop had low yields or even died.

**Comment by peter-devoil** [comment]
Each simulation will be different - simulated crops will "fail" for a number of reasons. The questions you need to ask yourself is what parallel data can be identified that would confirm the experiment and your derivative calculations? 

Eg. do wet treatments do better than dry treatments?

Eg, can you identify that plant transpiration (Ep) from both simulations and observations is comparable, and further relate total biomass as a function of transpiration efficiency and Ep?
