### ISSUE TITLE
Reset APSIM simulation through C# Manager

### ISSUE THREAD

**Issue by para2x** [APSIMInitiative/APSIMClassic#2028]
Hi 

I was wondering if it is possible to reset a simulation using the C# manager ? Specifically if the internal design of the model and the clock component allows for restarting a simulation through the C# manager ?

Thank you

**Comment by peter-devoil** [comment]
Not at the moment; though I've often thought it wouldn't be too hard. You should only need an event handler for the clock module that resets the date.

There are a handful of routines that need checking to ensure the modules are re-initialised correctly - the rainfall / evap  accumulator in soilwat for example; though most soil modules already handle a reset which you could send out at the same time.

I doubt active crops are going to handle the time warp very well..

In some simulations, time taken to initialise is longer than simulation time (eg single season), and this feature could be very useful.

**Comment by para2x** [comment]
@peter-devoil Thanks for sharing your thoughts on this.
