### ISSUE TITLE
Does 'act_mods' have an equivalent in Manager2?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2029]
The following code is from the toolbox. Does this do what **act_mods** does in classic Manager?

```
         TillageType t = new TillageType();
         t.type = tillageImplement;
         Component paddockModule;
         if (currentPaddock != "")
            paddockModule = (Component) MySimulation.LinkByName(currentPaddock);
         else
            paddockModule = MySimulation.ChildPaddocks[0];
         paddockModule.Publish("tillage", t);
```

**Comment by peter-devoil** [comment]
Nearly. It will send the message to any listening modules _in the paddock_. IIRC, act_mods is all components in the simulation, ie top level (eg metfile), and any (adjacent) paddocks.

Event and variable scoping is a difficult issue we're still grappling with (in nextGen). In classic, published events propogate down the tree, but variables are gotten progressively up the tree.
