### ISSUE TITLE
How to implement 'hill_up' in Manager2?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2030]
How can I mimic this in Manager2?

`sugar hill_up topsfr = 0.6, canefr = 0.6`

**Comment by peter-devoil** [comment]
That old code uses an apsim variant postbox to pass in arguments to [the sugar module](https://github.com/APSIMInitiative/APSIMClassic/blob/69bd2a2d7d580552bdca8f8229e8ee4e1d8b0b0a/Model/Sugar/SugarMain.for#L5254). It's a real nuisance to make them in manager2. You could:

- rewrite the publish / subscribe code in sugar to handle structures, or

- make a very simple manager1 component that responds to one event (eg doHillUp), by sending sugar the hill_up event (with parameters). Then call your simple manager1 from manager2. Try not to laugh or cry while doing this.

**Comment by BrianCollinss** [comment]
Cheers Peter. I think I gonna have to stick with Manager1 and find a way to call a function there when Manager2 does something! Easier for rookies :D
