### ISSUE TITLE
Invoking 'add_surfaceom' from Manager2 with AddSurfaceOMType

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2032]
Is there any way we can invoke **add_surfaceom** from a Manager2 using **SurfaceOrganicMatterType**?

I wrote this and dont get an exception, but I am not sure:
```
            AddSurfaceOMType SomType = new AddSurfaceOMType();
            SomType.name = "millmud";
            SomType.type = "millmud";
            SomType.mass = (float)millmud_p;    
            SomType.cnr = 22;  
            MySimulation.Publish("add_surfaceom", SomType);
```

**Comment by BrianCollinss** [comment]
I tried this, but failed:

```
[Link] public SurfaceOrganicMatter MySurfOM;

   [EventHandler] public void OnPrepare()
   {
            SurfaceOrganicMatterType SomType = new SurfaceOrganicMatterType();
            SomType.name = "millmud";
            SomType.type = "millmud";
            SomType.mass = millmud_p;    
            SomType.cnr = 22;  
            MySurfOM.Publish("add_surfaceom", SomType);
    }
```

**Comment by peter-devoil** [comment]
You could see if the [report_additions](https://github.com/APSIMInitiative/APSIMClassic/blob/69bd2a2d7d580552bdca8f8229e8ee4e1d8b0b0a/Model/SurfaceOM/SurfaceOM.f90#L2241) flag says anything. You'd need a customised ini file (via Soil.xml plugin) to set it.

**Comment by BrianCollinss** [comment]
Thanks Peter. I can see I need to play with **SurfaceOMParameters**. But I cannot find out how. I tried creating an **SurfaceOMParameters** or **SurfaceOMParametersType** object, but it did not work.

**Comment by peter-devoil** [comment]
The 3 structures SurfaceOMGlobals, SurfaceOMParameters and SurfaceOMConstants are internal to the fortran code, and not directly accessible outside. You'll find all fortran modules use the same protocol of globals, parameters & constants being bundled together into an instance pointer - when switching context between two like modules (eg two instances of a sugar cane module, or a SOM module present in two paddocks) of a simulation, the system simply switches the instance pointers block, and calls the non-OO fortran code, which is unaware that it's got a new set of g/p/c pointers.

I was wrong about Soil.xml - surfaceom has [its own ini file](https://github.com/APSIMInitiative/APSIMClassic/blob/69bd2a2d7d580552bdca8f8229e8ee4e1d8b0b0a/Model/SurfaceOM.xml#L61). It should be enough for you to add the (optional) flag like
```
...
<fraction_faeces_added>0.70</fraction_faeces_added>
<report_additions>yes</report_additions>
<!-- Residue type information 
...
```
Sorry for the confusion

**Comment by BrianCollinss** [comment]
Thanks Peter. So I just add the flag to SurfaceOM.xml (ini). BTW, I checked the daily surfaceom-wt and it seems it gets all I add. Cheers.
