### ISSUE TITLE
largestLeafParams in Maize.xml 

### ISSUE THREAD

**Issue by para2x** [APSIMInitiative/APSIMClassic#2033]
Hi 

I want to first mention that I really appreciate the fact that APSIM team takes the time to answer users questions. 

Looking at the original  "Improved methods for predicting individual leaf area and leaf senescence in maize   (Zea mays) C.J. Birch, G.L. Hammer and K.G. Ricket. Aust. J Agric. Res., 1998, 49, 249-62" paper it looks like that in the Eq presented in Fig4 (below) the coefficient in there are 1000,-1.17 and **0.47**. 
![image](https://user-images.githubusercontent.com/7999941/114208468-20e95600-9923-11eb-8890-6f13104e812f.png)

However in the Maize.xml the default values are 1000, -1.17 and 0.047 (instead of 0.47) (https://github.com/APSIMInitiative/APSIMClassic/blob/69bd2a2d7d580552bdca8f8229e8ee4e1d8b0b0a/Model/Maize.xml#L151). 
I was first wondering if this is a typo or there is specific reason for changing this coefficient ? Secondly, I'm trying to optimize APSIM maize LAI estimates and I was wondering if you recommend optimizing any of these parameters ? 

Thank you again,

**Comment by jbrider** [comment]
@para2x It could be a typo - but I will need to double check to confirm what has happened there. 
You could use that parameter to optimize the LAI, but only if you are sure you have your phenology and total number of leaves correct first.

**Comment by JNGH** [comment]
Plug in some values for TLNO and it will be apparent the Fig 4 graph was created using 0.047.

**Comment by para2x** [comment]
Yes that makes sense ! Thanks for sharing your thoughts,
