### ISSUE TITLE
Increasing width of character strings in reports

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2034]
I need to have a column containing long string of characters. But currently the default width is too short. Is there something like **format** to change the width?

**Comment by BrianCollinss** [comment]
Hi @peter-devoil . Do you have a solution for this issue? Cheers.

**Comment by peter-devoil** [comment]
Try setting your string to a long initial value, write a line of dummy output, then continue as normal. The widths are determined when the 1st line of output is written.

Don't forget you can write to an output stream with the C# manager, or use csv formats.

P
