### ISSUE TITLE
Sugarcane root_depth starts at 1000?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2035]
Is there a reason for sugarcane root starting with **root_depth** set at 1000? Initial root depth in sugar.xml is 150 mm. But the model reports 1000 mm, which is constant for a while and then starts increasing upt o 2000.

**Comment by sarahcleary** [comment]
@JodyBig

**Comment by KirstenVer** [comment]
The problem arises because the initial rlv determines rooting depth upon emergence. The initial rlv values are specified in the sugar.xml file and are specified by layer. Depending on the layer structure chosen (in SoilWat or SWIM water balance modules), the default values can indeed result in quite deep starting root depth. Suggest to adjust the initial rlv in the xml to something that makes sense given your soil layer structure.

**Comment by BrianCollinss** [comment]
Thanks @KirstenVer . I changed the rlv values from: <rlv>0.04  0.02  0.01  .005  0.00  0.00 0.00</rlv> to much smaller values, but did not affect the initial root depth.

**Comment by KirstenVer** [comment]
@BrianCollinss, did you reduce the 3rd and 4th value or set to 0. If reduced, could you please also try setting to 0?

**Comment by BrianCollinss** [comment]
It did work this time. But zero keep the root from growing.

**Comment by KirstenVer** [comment]
That's consistent. Your first set up has some roots down to the 4th layer. The second set up has roots down to the 3rth layer. Layer structure probably finishing 3rd layer at 60 cm and 4th at 1m? As long as xf > 0 and soil water content not too low then the roots will extend deeper as the season goes.

**Comment by BrianCollinss** [comment]
In sugar.xml, initial root depth is 150. May I know why rlv overwrites that and how I can use 150 mm?

**Comment by KirstenVer** [comment]
I don't know why it overwrites that.  
You could only enter an rlv value for the first layer of your profile (which presumably is 0-15 or 0-20 cm?).
Would only do that for plant crops though.

**Comment by BrianCollinss** [comment]
Thanks @KirstenVer . I assume rlv sets the initial root density in each layer. Then, when it is >0, root depth is extended to that specific layer. I set it >0 for first layer and 0 for others so the root starts at 150 mm of depth. Cheers.
