### ISSUE TITLE
APSIM 7.10r0 met variables exceeding upper limit

### ISSUE THREAD

**Issue by painchetotam** [APSIMInitiative/APSIMClassic#2040]
Greetings. I've got a new issue which I need help with. Got a new .met file(made by myself with use of ERA5 datasets) and my .sum file says that RADN exceeds upper limit. How can I fix it? Calculations have been made correctly. There's a portion of this file:
                 APSIM Warning Error
                      -------------------
     pen =     46.10475
             exceeds upper limit of    15.00000
     Component name: paddock.eo
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     pen =     45.35569
             exceeds upper limit of    15.00000
     Component name: paddock.eo
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     Bound check warning while getting variable.
     Variable  : eo
     Condition : 0.00 <= 43.54 <= 20.00
     Component name: paddock.wheat
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     radn =     244.8800
             exceeds upper limit of    60.00000
     Component name: paddock.Soil Water
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by BrianCollinss** [comment]
Warnings don't stop simulations. Just check the unit of pen in your file. Apsim believes 45 is Toowoomba high a number for it.

**Comment by peter-devoil** [comment]
Yep. I'd be suspicious of a daily radiation exceeding clear sky radiation. Draw a histogram of your daily values to see where most are. Perhaps the units are incorrect.

**Comment by JJguri** [comment]
@peter-devoil I have the same issue with warning when the saturation was higher than a threshold. Is there a way to remove this warnings from the SUM file? I am running rotations and have a really long file so this warnings do not allow me to find important crop practices such as planting, fert, irrrigation, etc.
```
1 January 2006(Day of year=1): 
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
      saturation of     0.450000      in layer   3
              is above acceptable value of     0.433962
     You must adjust bulk density (bd) to below      1.45750
     OR saturation (sat) to below     0.433962
     Component name: paddock.0 Water
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by peter-devoil** [comment]
Not unless you rebuild the model and remove the message

It is telling you that your soil is physically impossible. That should be a good reason to fix either BD or SAT.

**Comment by JJguri** [comment]
rebuild the model would be to setup different thresholds for SAT right?  The issue here is that we are using an automatic way to create the soil based on SSURGO data. So there is uncertainty in the source of the soil data we cannot manage.

**Comment by peter-devoil** [comment]
No, just comment out the warning from the fortran module.
Surely if it's automatic then you can adjust it?
If not, just ignore the message.

**Comment by JJguri** [comment]
@peter-devoil where is the fortran module located? yes you are right if it automatic we should be able to adjust it.

**Comment by peter-devoil** [comment]
[Here's](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/SoilWat/SoilWat.for#L2574) the error message.
