### ISSUE TITLE
Need to harvest a crop for grain and then let it re-grow

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2041]
I need to have a harvest and then let the crop re-grow. I am trying to mimic multiple harvests of Mungbean where the first harvest is for grains, and the second is an opportunistic harvest (can be manure or grain). I am not sure if this is possible in non-ratooning plants.

**Comment by peter-devoil** [comment]
Check out how lucerne winds back phenology when harvested - that's the paradigm you want to follow.

**Comment by BrianCollinss** [comment]
Thanks Peter. I cannot find anything in the examoples. Do you mean I need to change the code of the plant in the same way as Lucerne's code works?

**Comment by peter-devoil** [comment]
Yes, your new ini file will need some details about how to wind back phenology after a harvest event - lucerne [does this](https://github.com/APSIMInitiative/APSIMClassic/blob/e6e2b389c5642e6d71bb0c26ceb33e1f3a729a0a/Model/Lucerne.xml#L174) so should be a good place to start.

**Comment by BrianCollinss** [comment]
I am trying to mimic the way Mungbean re-grows. I am not sure what the way to approach this is. Mungbean regrows from seeds that were left on the ground from previous harvest. Perhaps it is best to use another planting with different density.

**Comment by peter-devoil** [comment]
That sounds like a better idea.

**Comment by BrianCollinss** [comment]
Cheers. Always great to have your help.

**Comment by peter-devoil** [comment]
FYI - I've hear people modelling ratooned sorghum by making a cultivar that emerges the day after sowing, and using that cultivar as the ratoon crop.

**Comment by KeLiu7** [comment]
> Cheers. Always great to have your h

> FYI - I've hear people modelling ratooned sorghum by making a cultivar that emerges the day after sowing, and using that cultivar as the ratoon crop.

Hi Peter, do you know who has experience in modeling ratoon crops? I'm very interested in modeling ratoon rice (re-growth of rice crop from the stubbles after the harvest of the main crop) in APSIM Oryza. Do you know if there is an example or who can help? 

Ratoon rice is very popular in Asia nowadays and I already got many inquiries from there. If we can do this, I think our APSIM community might attract many new users there.

**Comment by KeLiu7** [comment]
> I am trying to mimic the way Mungbean re-grows. I am not sure what the way to approach this is. Mungbean regrows from seeds that were left on the ground from previous harvest. Perhaps it is best to use another planting with different density.

Hi Brian, have you figured out how to model ratton crops in APSIM?

**Comment by peter-devoil** [comment]
I have some code in nextgen that can help, if you like...
