### ISSUE TITLE
end_crop vs kill_crop?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2042]
May I know what the difference is. Can any of them be used to let a crop re-grow after harvest?

**Comment by peter-devoil** [comment]
kill_crop has an argument that lets you thin the stand - it changes the planting density (kill_fr). The plant will grow again, unless the density is zero. [Details](https://github.com/APSIMInitiative/APSIMClassic/blob/e6e2b389c5642e6d71bb0c26ceb33e1f3a729a0a/Model/Plant/Population.cpp#L283).

end_crop calls destructors etc.
