### ISSUE TITLE
The yield and biomass of simulated maize were too low 

### ISSUE THREAD

**Issue by shaoyuGao** [APSIMInitiative/APSIMClassic#2043]
The yield and biomass of simulated maize were too low compared with those measured in field experiments.The experiment took place in Gansu, China.The yield we measured averaged 16000kg/ha.The biomass we measured averaged 35000kg/ha.But the potential simulated yield is only 10000kg/ha，the potential simulated biomass is only 23000kg/ha,How should I fix this problem and what parameters should I change.
   There is a big difference in temperature between day and night in Gansu.It have Long sunshine duration
    Forgive me for my poor English

**Comment by jbrider** [comment]
Which version of Apsim are you using?

Have you got good soil data regarding depth, starting water, amount of
nitrogen?
Was it irrigated? Do you have a good idea how much water was added?
Was it rain fed?
Is your met data recorded near the field?

You need to ensure your environment is accurate before you start looking at
changing parameters.

Is the cultivar used in the experiment present in the APSIM model?
Have you got your phenology correct - ie: Total number of leaves; is flag
leaf correct?, is flowering time correct?

**Comment by shaoyuGao** [comment]
Thank you very much for your reply
I use APSIM7.10.
I used the exact initial soil moisture、 initial soil nitrogen content、BD、AirDry、LL15 and so on.  ButI don't know how to determine  (Max. reduction in curve number due to cover)、（Cover for max curve number reduction）、FBiom、FLnert.
I set up automatic irrigation
My met data recorded near the field.
The cultivar used in the experiment is not in the model.so I set up new cultivar.
We used drip irrigation with film covering in our experiment.How should I select this pattern in the model?
How can the growth period division in the APSIM-MAIZE be accurately observed in the field experiment?

**Comment by jbrider** [comment]
When you created the new cultivar - what parameters did you add that make it different from the default?
I'm not sure how to setup the drip irrigation either - but if you set it to auto then I assume it is non-stressed and therefore not the most important setting to worry about to set it up.
FInert is very important - the easiest way would be to use values from a similar type soil that has been calibrated for maize within Apsim.
The total number of leaves on the plant will determine the growth period - was that number recorded?

**Comment by shaoyuGao** [comment]
I am sorry for the late reply.I created the new variety but did not add additional variety parameters.I adjusted some of the parameters in the default variety to make the simulation more accurate.
The parameters I debug include  tt_emerg_to_endjuv、tt_flag_to_flower 、tt_flower_to_start_grain 、tt_flower_to_maturity 、potKernelWt、RUE.
Can drip irrigation be easily set by irrigation efficiency？The field experiment was mulch-drip irrigation.How to set the laminating treatment.
end_of_juvenile is V6? end_grain_fill is R4?
I just started learning APISM model, where can I go for more help.

**Comment by para2x** [comment]
I actually have a similar issue with APSIM 7.10 too. I'm running simulations at 10 sites across U.S midwest and I have optimized cultivar params using LAI measured. Cultivar parameters extend or shorten the LAI development and results in a good match with Obs data but not much change/improvement happens in yield. The obs yield is around 14000 kg/ha but the simulated yield maxed at 12000 across all the sites. I also checked for the water and nitrogen stress and there is none. 

![image](https://user-images.githubusercontent.com/7999941/117542854-ffda5a80-afdf-11eb-8bb3-a363d2095543.png)


Here is an example of one of my plots where "ref" is one of APSIM cultivars developed for midwest as a reference, "Obs " is the observed yield and the others are different optimization methods. Would be great to your thoughts

**Comment by jbrider** [comment]
Yield is highly reliant on the temperature and water stress at the time of flowering. You have changed parameters to fit the LAI curves but have you looked at the effect that has had on your phenology. How well does your flowering with observed data?  
One of the first variables to look at when fitting a new cultivar is the total leaf number which is determined from the thermal time to floral initiation and appearance rate - which can be validated against observed values from the field.

**Comment by jbrider** [comment]
@shaoyuGao [Apsim Training Manuals](https://www.apsim.info/support/apsim-training-manuals/)
The training manuals are a good place to start.
There is also a [Youtube Channel](https://www.youtube.com/channel/UCawR0E_PzYJcv15oTk-ssjQ) where new content is uploaded.

**Comment by para2x** [comment]
> You have changed parameters to fit the LAI curves but have you looked at the effect that has had on your phenology. 

Given the fact that the temporal structural (bell shape) pattern in observed LAI is highly driven by phenology and the parameters I optimize include both leaf appearance rates and phenology parameters, and also given that I get really good fit for LAI, I think I shouldn't be really off in phenology either (But I don't have observed phenology to check). But still in some cases yield is almost 20-30% NRMSE off. 

So I'm writing a discussion on this and do you think it's a fair statement to say that there is a very little connection between LAI and yield in APSIM maize ?

**Comment by jbrider** [comment]
@para2x There is a paper titled: Modelling the nitrogen dynamics of maize crops – Enhancing the APSIM maize model (S. Soufizadeh, E. Munaro, G. McLean, A. Massignam, E.J. van Oosterom, S.C. Chapman, C. Messina, M. Cooper, G.L. Hammer)
The paper describes how the model is implemented in APSIM Classic. 
It contains a section on the calculation of Yield using grain number and grain size.
