### ISSUE TITLE
Inputing 'tracker' variables into Manager2

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2044]
I have a tracker with:

`sum of rain on last 7 start_of_day as rain7`

When I try:

`[Input] public double rain7; `

in my Manager2, I get this error: 
`     paddock.FallowManager Driver:6 doSetDriver(): paddock.FallowManager: Type of value passed for driving variable 6 (rain7) is incompatible.`

**Comment by peter-devoil** [comment]
"Last 7" may be leading you astray. Check that the tracker is actually sending something - it may not be responding until it sees the event to sample on.

**Comment by BrianCollinss** [comment]
**rain7** has got values in daily report.

**Comment by BrianCollinss** [comment]
Even when I try **MyPaddock.Get("rain7", out rain7);** I get the same error. Does it mean tracker outputs have a specific type?

**Comment by peter-devoil** [comment]
Whatever it is, it cant find a convertor to turn it into a double, which is unusual.

**Comment by BrianCollinss** [comment]
I really don't know why, but when I define rain7d as a double array, it works!

**Comment by peter-devoil** [comment]
But the variable shows up in the daily report as a scalar?

**Comment by BrianCollinss** [comment]
Yeah, right? Now I use a intermediary variable to catch only [0].

**Comment by peter-devoil** [comment]
Sounds like a bug then. Could it be a 1-length array?

[Here's](https://github.com/APSIMInitiative/APSIMClassic/blob/e6e2b389c5642e6d71bb0c26ceb33e1f3a729a0a/Model/CMPServices/basecomp.cs#L1078) the line that's getting cranky.

**Comment by BrianCollinss** [comment]
I checked. It is indeed a 1-length array!
