### ISSUE TITLE
SWIM3, APSIM 7.10 - "Possible error with low total RLV for maize"

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#2045]
About half of my simulations using SWIM give no output for subsurface_drain and subsurface_drain_no3. Checking the sum file I get this repeated error: "Possible error with low total RLV for maize." Anyone know what this RLV is?

**Comment by BrianCollinss** [comment]
You can find it in the maize.xml in Models folder. It determines root density in each soil layer.

**Comment by mnowatzke** [comment]
Thanks! That makes sense given my APSIM file setup, but doesn't make sense for no SWIM drainage output...
