### ISSUE TITLE
Trying to understand a few output parameter.s

### ISSUE THREAD

**Issue by yttehs123** [APSIMInitiative/APSIMClassic#2050]
I would like to get clear on a few output variables in APSIM.

Is GPLA the leaf area for a single plant or the whole plantation?
 if it is for a single plant I am getting absurd results for a single maize crop, the leaf area I am getting reaches up to around 470m2. If it is for the entire plantation then I  would like to know how many crops were planted in the simulation. So far I can only find the row spacing for planting but not the amount of crops that were planted in order to get an individual plant leaf area.

Is the stage number a phenological stage number or the zadok stage number.

**Comment by peter-devoil** [comment]
Yes, stage number is 1:12 for the various physiological stages. zadoks are 1:100 (wheat only). 

I think you've found a bug in that may interest @jbrider - it's [reporting spla](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Maize/Leaf.cpp#L37) where it should be reporting tpla. 

Both are  [calculated](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Maize/Leaf.cpp#L239) as [s,t]lai / density * 10000 - "m2/m2" / "plants/m2" * 10,000 - which I think is in mm2.

**Comment by yttehs123** [comment]
> Yes, stage number is 1:12 for the various physiological stages. zadoks are 1:100 (wheat only).
> 
> I think you've found a bug in that may interest @jbrider - it's [reporting spla](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Maize/Leaf.cpp#L37) where it should be reporting tpla.
> 
> Both are [calculated](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Maize/Leaf.cpp#L239) as [s,t]lai / density * 10000 - "m2/m2" / "plants/m2" * 10,000 - which I think is in mm2.

Here's an example, the density is 4/m^2. Lai = 1.143, TPLA = 2857
Based on the formula you have mentioned above, the values seem to be correct. But seem to be to extensive. I'm guessing the "*10,000" is not converted into m2 values.  If so, is the 10000 in mm2? That would mean after conversion;

1.143/4 *0.01 = 0.0028575 m^2. which seems like too low a value for a single plant.

**Comment by peter-devoil** [comment]
Yes, it looks to be incorrect. The conversion from mm2 to m2 should be 1e6, not 1e4.

**Comment by yttehs123** [comment]
> Yes, it looks to be incorrect. The conversion from mm2 to m2 should be 1e6, not 1e4.

Yes, I multiplied 10000 with 1e6 which got me 0.01.  So currently I am not sure how to obtain plant leaf area for an individual plant.

**Comment by peter-devoil** [comment]
In your example, 1.143/4 * 1e6 = 285750 mm2/plant

**Comment by yttehs123** [comment]
Oh my bad, thanks for your help, Is there a defined way to convert the phenological stage to zadok  stage?

**Comment by peter-devoil** [comment]
There are two stick functions [here](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Plant/Phenology/Zadok.cpp#L61) that you can use for interpolation pre and post floral initiation. But aren't Z stages a wheat specific concept?
