### ISSUE TITLE
Changing genotypic parameters during the simulations

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2051]
Is it possible to change plant parameters during the simulation? I can see that 'Set' does not do it. And if it is possible, how is it done for parameters that take multiple values, e.g. oxdef_photo_rtfr?

**Comment by peter-devoil** [comment]
Usually not - search the code for an expose() that is writable to be sure. The cultivar parameters are read from xml into a tree at initialisation, which is searched at sowing time when the cultivar is known.
