### ISSUE TITLE
Limiting maximum root depth without modifying soil XF?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2052]
Is there any way to limit root growth without needing to change soil XF?

**Comment by peter-devoil** [comment]
set LL to DUL - the effect will be the same. Not all crop modules allow this tho.

**Comment by BrianCollinss** [comment]
I was wondering if there is way to avoid playng with soil parameters. I can see that XF is not even exposed so cannot be modified via a manager script(?).

**Comment by peter-devoil** [comment]
No - if it's not exposed, the system has no way to get at it. 

Not every module is the same - plant (ie wheat & legumes) [allows this](https://github.com/APSIMInitiative/APSIMClassic/blob/21b18a27546c95a5494be6a1c8e1710c6638941c/Model/Plant/Root/Soil.cpp#L41).

**Comment by BrianCollinss** [comment]
How would you change maximum rooting depth?

**Comment by peter-devoil** [comment]
XF
