### ISSUE TITLE
APSIM's configuration in a new computer_some components/functions are disabled 

### ISSUE THREAD

**Issue by UKAU21** [APSIMInitiative/APSIMClassic#2053]
Hello,

APSIM setup does not show some components in a new computer. 

I recently started using APSIM classic (V7.9 and V7.10) in a new computer.  

Descriptioin of the computer
Windows 10 Education
Processor: Intel(R) Core (TM)i5-10210U CPU @ 1.60GHz 2.11 GHz
RAM: 16.0GB ( 15.8 GB usable)
System type: 64-bit Operating System, 64-baseed processor

The computer gets updated regularly form a university's server.

Description of the issue and possible reason:

- I had a simulaiton set up in a 4 years old computer with same windows. 
- I copied this simulaiton setup in a new computer. Here it does not run and throws an error related to computation of biom_c in the Nitrogen component of soil file. 
- Then I tried to built the same simulation tree from one of the examples in the new computer. And I noticed a few things:
-      It’s not possible to add two sowing dates even by coding it. I moved ahead with one sowing date "sowing on a fixed date" as the default. 
-      When I tried to add tillage component which requires “SurfaceOrganicMatter” module in which the tilling will be applied to, -      I found here is the main issue. In the new computer, it does not show SurfaceOranicMatter module in any of the toolboxes 
or folders. So no option to add this in the simulation setup. 
-    I opened all example setups in the new computer and there as well, SurfaceOranicMatter is not visible in any of them. But they run fine. 
- I checked the setup and examples again in my older computer. SurfaceOranicMatter Model is visible in simulation setup. And the simulations work fine. I could find SurfaceOranicMatter Module in the examples e. g. "Continiuous Wheat"  and they run fine as well. 

When I restart the new omputer it shows that the window is configuring APSIM. 

I tried uninstalling and re-installing two version of APSIM (V7.9 and V7.10) but no success. 

I am not sure what is the problem and how to fix this.

I will appreciate for any help or suggestions to fix this. I hope some of you have addressed this or something similar before. 

Thank you in advance!

Uttam

**Comment by peter-devoil** [comment]
Ugh. Sounds like a real mess. My suggestion would be to start again from scratch as what you have now is obviously broken. 

Start with a fresh install, run the relevant examples (that exercise your crop) to be sure that it's got no surprises. Regionalisation settings (eg date/time, decimal points) often break apsim at this stage. Only then add your soils/changes. Usually, the file upgrade process that translates older format (eg 7.9) .apsim files to newer is seamless, but it has been known to go wrong..
