### ISSUE TITLE
Probability exceedence chart error(APSIM 7.10-r0)

### ISSUE THREAD

**Issue by painchetotam** [APSIMInitiative/APSIMClassic#2055]
Greetings.
I'm still trying to make my sim work
For climate change scenarios probability chart is needed(according to the exercise)
I have met data for 30 years and when trying to access the PE chart it says "cannot perform = operation on system.double and system.string"
How to fix it? 
Any advice will be appreciated

**Comment by BrianCollinss** [comment]
Are you using English as your laptop language?
