### ISSUE TITLE
Lentil - APSIM

### ISSUE THREAD

**Issue by tefera21** [APSIMInitiative/APSIMClassic#2058]
Could someone help me to describe the stages of lentil development (**mainly at end_of_juvenile & floral_initiation**) in terms of  number of nodes? This is just to determine thermal time accumulation at each stage as in APSIM plant module. Thanks

**Comment by sarahcleary** [comment]
@APSIMInitiative/legumes - can anyone help?

**Comment by peter-devoil** [comment]
I suspect that apsim does not directly couple canopies & phenology. The [zadok calculation](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/Plant/Phenology/Zadok.cpp) in the wheat model (ie same code base as lentil) hides this by amalgamating the two processes, but they are distinct processes within the model.

Also remember that we don't really model indeterminate flowering - flowering in the legume model is the point of "50% of flowers", and not a period of time.

@jwhish and fernanda.dreccer at csiro.au may have more insight.

**Comment by tefera21** [comment]
Thanks Peter, that's very useful.
