### ISSUE TITLE
Extract soil data from ISRIC in R

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2060]
Does anyone who has experience with extracting soil data source provided APSIM NG (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V) in R?  If yes, could you please share your codes with me? Many thanks!!

**Comment by BrianCollinss** [comment]
HI @KeLiu7, I would post this in https://github.com/APSIMInitiative/ApsimX/issues if you are interested to know about APSIM NG.

**Comment by KeLiu7** [comment]
> HI @KeLiu7, I would post this in https://github.com/APSIMInitiative/ApsimX/issues if you are interested to know about APSIM NG.

Thanks Brain, already done.

**Comment by peter-devoil** [comment]
There is some python code in [PSIMs](https://github.com/RDCEP/psims/blob/release-2.0/pysims/translators/apsim79/jsons2apsim.py) that may provide inspiration - they follow a template approach to modifying files. Most of the time, it's a matter of writing bespoke xml manipulation code in your language of choice - and it's difficult to generalise this manipulation - usually it's wedded tightly to the problem.

**Comment by KeLiu7** [comment]
> There is some python code in [PSIMs](https://github.com/RDCEP/psims/blob/release-2.0/pysims/translators/apsim79/jsons2apsim.py) that may provide inspiration - they follow a template approach to modifying files. Most of the time, it's a matter of writing bespoke xml manipulation code in your language of choice - and it's difficult to generalise this manipulation - usually it's wedded tightly to the problem.

Thanks Peter!
