### ISSUE TITLE
leach_no3 output = NO3 or NO3-N?

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#2064]
As the title indicates, documentation seems to be missing as to which NO3 is being reported in the leach_no3 output: NO3 or NO3-N. Anyone know? I tried inferring from the output numbers but they can be very high or low depending on the soil. Running in APSIM 7.10.

Thanks

**Comment by para2x** [comment]
I do actually have the same question. 

Looking at the code in soiln module, it appears to me that the model spits out NO3 and not NO3-N but I was wondering if you could also confirm this ?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel

**Comment by sno036** [comment]
All the units of these are "kg N /ha".

**Comment by mnowatzke** [comment]
@sno036 To clarify, you interpret that then as NO3?

**Comment by femiguez** [comment]
@mnowatzke @para2x my interpretation is the opposite. The output from APSIM is simply Nitrogen (N). When comparing with measured values make sure those are N-NO3 then.

**Comment by mnowatzke** [comment]
Thanks @femiguez. That makes sense.
