### ISSUE TITLE
Sugarcane does not emegre despite being unstressed

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2067]
In many cases, when I apply (for example) 30 mm of water at sowing, crop does not emerge. But it does with 50 mm. Surprisingly, it does not emerge even with two successive days of 30-mm irrigation.

**EDIT:** I found the reason. Not sure what the workaround should be. See https://github.com/APSIMInitiative/APSIMClassic/issues/2067#issuecomment-879598782

**Comment by JodyBig** [comment]
Hi Brian, How did you identify that there was no stress? Is it a plant or ratoon? How is irrigation being applied?
Can you share the warning message in your summary file?

**Comment by BrianCollinss** [comment]
Hi Jody. I dont get any warning. Just:

```
27 May 2014(Day of year=147), paddock.sugar: 
      crop failure because of lack of
              germination within 40. days of sowing
         crop_kill. Standing above-ground dm =     0.0 (kg/ha)
```

I check soil moisture and all the swdef_XXX stress factors. Plus, it does not seem to be related to water deficiency, in which case there should have not been any difference between 50 mm of water on one day or 30 mm of water on two successive days when soil profile is close to DUL. I have this with both Plants and Ratoons.

**Comment by JodyBig** [comment]
Usually I get this error due to water.
Applying irrigation at sowing might not resolve this. Applying irrigation closer to 40das should resolve this.
I use a rule like below to ensure germination and to record, what I refer to as, a 'crop salvation'.
Let me know if this works.
if (sugar.DaysAfterSowing = 35) and (sugar.stage &lt; 2) then
              irrigation apply amount = 41 !odd number to enable identification in summary file
              CropSalvation = CropSalvation + 1
            endif

**Comment by BrianCollinss** [comment]
You are right Jody. I have some rules for 'auto-irrigation' that calculate soil water availability and apply water if it is less than a threshold. I chose a high threshold for pre-emergence to make sure there will be enough water for germination/emergence. It works. I just wondered why this lack of germination might be happening.

**Comment by JodyBig** [comment]
Thinking out loud...
Could it be related to irrigation being applied to one layer but uptake occurring over multiple layers? This might explain the 50 vs 30+30 issue.

**Comment by BrianCollinss** [comment]
Hmmm ... but there is no (much) crop uptake at sowing and evaporation should not make such a big difference between two very similar scenarios.

**Comment by BrianCollinss** [comment]
[Simulations Daily.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6813099/Simulations.Daily.zip)

An example output for further investigation. Look for column 'irrigation'.

**Comment by BrianCollinss** [comment]
@peter-devoil may I please know how APSIM triggeres emergence? Is there any upper threshold for moisture along with the lower threshold?

**Comment by BrianCollinss** [comment]
OK I thin I found out why this happens. Germination is the issue here, not emergence. It seems APSIM requires a minimum amount of moisture (0.05 mm/mm by default) in the seedling layer for germination. In a soil profile like this one, even at DUL there won't be enough moisture for germination. Therefore, the seedling layer needs to be close to saturation so germination can occure! Is this a realistic set up, i.e. can seeds germinate under saturated conditions, I am not sure. 

https://github.com/APSIMInitiative/APSIMClassic/blob/27396788a2c0fcc2750b72700d7fccf35fc7c7ea/Model/CropTemplate/crp_phen.f90#L370-L373

![image](https://user-images.githubusercontent.com/39573622/125565473-f9562ecd-82c7-4dbc-89dd-79e35a78ab97.png)

**Comment by peter-devoil** [comment]
1. That's an odd soil. Is it very sandy, if so, could you expect reduced emergence in sand? 
2. Why is AD right over on the LHS and not ~95% of LL15? It usually doesnt matter much, but it will try and evaporate water down to AD in the surface layer, which leaves your plants very dry.

**Comment by BrianCollinss** [comment]
Are you talking about the formula? What's AD?

**Comment by peter-devoil** [comment]
AD = air_dry. The soil evaporation algorithm will evaporate until it hits AD. So this soil will go lower than LL15 (ie pesw < 0) very quickly.

**Comment by BrianCollinss** [comment]
You're right. It's a suspicious profile from APSoil which we're thinking we should replace with something else. Any comment on germination under saturated conditions?

**Comment by peter-devoil** [comment]
You could simply apply a correction to set AD(1) = 0.95 x LL15(1), AD(2:n) = LL15(2:n).

No idea about sat. Better ask a physiologist. But make sure you have a sensible soil first.

**Comment by JNGH** [comment]
Have you tried planting into the 2nd layer?
