### ISSUE TITLE
How to specify the crop management practices during a simulation?

### ISSUE THREAD

**Issue by boranzhao** [APSIMInitiative/APSIMClassic#2068]
Dear APSIM experts,

I wonder whether it is possible to specify the crop management practices (e.g, fertilization, irrigation, etc.) during a simulation, instead of before the start of a simulation. 

I want this feature because I am interested in applying some artificial intelligence techniques (e.g., reinforcement learning) to learn a management policy, e.g., a neural network, which will output the management practices according to the crop state, weather and soil conditions in real time.  A similar idea is pursued in[ this paper](https://arxiv.org/abs/2104.04326),  while the crop simulation environment is detailed [here](https://pcse.readthedocs.io/en/stable/index.html).

Thank you.

Best Regards
Pan

**Comment by BrianCollinss** [comment]
Until you get a response from one of APSIM founding fathers: I don't think it's possible as apsim reads all the inputs first. The only option I see is to run APSIM (in parallel) via an optimisation routine which writes individual simulations and run them (in parallel).

**Comment by hol353** [comment]
It's not currently possible. You would have to write a manager2 script that calls another process (e.g. a .exe) during a simulation run to get management for the day. That other process could be an R or python script. This would be very slow to run.

More sophisticated would be to use an inter-process mechanism like sockets to do the connection between APSIM and Python/R - same idea as above but will run quicker and is more flexible. This would require some low level programming though - not trivial.

**Comment by her123** [comment]
Depending on the complexity, adaptive management can be written in a Manager2 script. Manager2 scripts should also be able to include other class libraries if it needs to be coded in another library.

**Comment by boranzhao** [comment]
> Until you get a response from one of APSIM founding fathers: I don't think it's possible as apsim reads all the inputs first. The only option I see is to run APSIM (in parallel) via an optimisation routine which writes individual simulations and runs them (in parallel).
> 
> Happy to contribute if you have an idea for research or publication.

Thank you very much for your kind response. I know that by default, APSIM reads all the inputs first. But according to the response from @hol353 and @her123, it seems that it is possible.

**Comment by boranzhao** [comment]
> It's not currently possible. You would have to write a manager2 script that calls another process (e.g. a .exe) during a simulation run to get management for the day. That other process could be an R or python script. This would be very slow to run.
> 
> More sophisticated would be to use an inter-process mechanism like sockets to do the connection between APSIM and Python/R - same idea as above but will run quicker and is more flexible. This would require some low level programming though - not trivial.

Thanks for the response, Dean. I have some follow-up questions. Do both of the two ways you mentioned allow bi-directional communication between APSIM and the other process (e.g., written in python) during the simulation?  By bi-directional, I meant that APSIM receives the management decision from the other process and also sends the current crop and soil state to it. 

For the second way, do you think we can build the connection by ourselves? Our group is in the mechanical engineering department. We could write codes for computer science courses and machine learning projects but we may not have extensive software development experiences. Are you able to provide some support in case we want to pursue this way?  Thank you very much.

**Comment by boranzhao** [comment]
> Depending on the complexity, adaptive management can be written in a Manager2 script. Manager2 scripts should also be able to include other class libraries if it needs to be coded in another library.

Thanks for the response.  What I want to achieve here is to build a connection between APSIM and AI agent so that they can communicate with each other during the simulation. More specifically, APSIM receives the management decision from the AI agent and also sends the current crop and soil state to it.  Can you evaluate the complexity involved in this?  Also, I do not know whether this needs "other class libraries" you mentioned.

**Comment by hol353** [comment]
> Do both of the two ways you mentioned allow bi-directional communication between APSIM and the other process (e.g., written in python) during the simulation? By bi-directional, I meant that APSIM receives the management decision from the other process and also sends the current crop and soil state to it.

If APSIM runs another process then some sort of file will need to be written by APSIM, read by the other process which then writes another file to send information back to APSIM - cumbersome. Instead, if you use sockets then yes it is 2-way communications - possibly harder to implement but much more flexible.

> For the second way, do you think we can build the connection by ourselves? Our group is in the mechanical engineering department. We could write codes for computer science courses and machine learning projects but we may not have extensive software development experiences. Are you able to provide some support in case we want to pursue this way?  

It will require a software developer who is familiar with socket connections. On the APSIM side the code will need to be written in C# and some understanding of APSIM will be required. On the Python side, code will need to be written to open a socket connection, wait for APSIM to call it and respond by sending a 'set of instructions' down the socket 'pipe'. It will be a bit tricky to get right. I have very little time to help support this unfortunately. Perhaps someone else from the APSIM community reading this can help out?

**Comment by boranzhao** [comment]
@hol353 Thanks a lot for the further clarification.  It would be great if someone can help with the socket solution. Our group is very interested in real-time and intelligent decision-making for crop management, and we really want to use APSIM as the crop simulator.  Then, developing a solution to enable communication between APSIM and other modules during the simulation seems an inevitable step to facilitate this.

**Comment by BrianCollinss** [comment]
I think another simple approach, which I once took, is to run APSIM day by day. Simulation starts on day 1 and ends on day 10, for example. Other modules read outputs and do whatever they are supposed to do. Apsim input files (eg. management) are modified. Apsim is then run again from day 1 to 11 with modified management. And so on.

**Comment by boranzhao** [comment]
> I think another simple approach, which I once took, is to run APSIM day by day. Simulation starts on day 1 and ends on day 10, for example. Other modules read outputs and do whatever they are supposed to do. Apsim input files (eg. management) are modified. Apsim is then run again from day 1 to 11 with modified management. And so on.

Thanks for this promising solution. Can you further tell how much this day-by-day approach will increase the simulation time? We needs to do a lot of simulations, under different weather, soil and management conditions.

**Comment by BrianCollinss** [comment]
By a lot :) Number of simulations will be 'growing season duration'-folded though most simulations include only a part of the season.

**Comment by boranzhao** [comment]
@BrianCollinss  I see. Good to know this information. We will evaluate whether this works for our projects since we need to do a lot of simulations. Thanks very much for the suggestion.

**Comment by boranzhao** [comment]
@hol353 I have another question. I know that R is often used to control APSIM for massive simulations. The AI decision maker in our project may be implemented in a Python module.  In this case, should we use R to control both APMSIm and the python module? Or we can do everything (including controlling APSIM) in Python? Thank you.

**Comment by hol353** [comment]
It is always best to try and simplify the design of any system. In this case that means doing everything in a single language. Python can be used for everything so there is no need for R.

**Comment by boranzhao** [comment]
@hol353  Thanks for your quick response. We know how to use R to run APSIM, but we are not familiar with python. Could you please direct me to some materials explaining the use of Python for APSIM, if available? Thank you

**Comment by hol353** [comment]
If you're more comfortable using R then just use R. I don't have any documentation on using Python with APSIM.
