### ISSUE TITLE
Canola luxury N uptake

### ISSUE THREAD

**Issue by IrisVogeler** [APSIMInitiative/APSIMClassic#2069]
I am trying to simulate luxury N uptake by Canola, and have increased the maximum N concentrations in the various organs.  However, this is not responsive.

**Comment by sarahcleary** [comment]
@jwhish and/or @JulianneLilley  - are you able to help?

**Comment by sarahcleary** [comment]
@IrisVogeler  - are you still requiring assistance?

**Comment by IrisVogeler** [comment]
Yes problem not resolved yet

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sarahcleary** [comment]
@jwhish and/or @JulianneLilley - are you able to help?
@APSIMInitiative/reference-panel ?

**Comment by JulianneLilley** [comment]
Hi Iris,
Yes, send me the simulations and I will have a look.

Cheers
Julianne

Dr. Julianne Lilley
Group Leader – Mixed Farming Innovations
CSIRO Agriculture & Food

E ***@***.******@***.***> T 02 6246 5536 M 0438 510 169
A GPO Box 1700, Canberra, ACT 2601, Australia
www.csiro.au<http://www.csiro.au/> | people.csiro.au/L/J/Julianne-Lilley<https://people.csiro.au/L/J/Julianne-Lilley>


PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, CSIRO does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.
Please consider the environment before printing this email.

**Comment by IrisVogeler** [comment]
Hi Julianne,

Thank you for your effort to look into this.  I think I have found the issue now.  Do you know if canola by default only takes up NO3 and not NH4?
If I ally NO3 fertiliser I will get concentrations above crit N, but not if I apply NH4.  I am using canola as a catch crop sown in autumn, so mineralisation will be low.

Best regards,
Iris
