### ISSUE TITLE
Adding a new run-off module?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2071]
Interested in adding a new emperical run-off module to APSIM code or our APSIM simulations. 

- Is 'runoff' a settable variable? If it is, it makes it easier to implement a new module as all can be done in a Manager2. In that case, how can 'runoff' be read and modified in a Manager? It seems it is not possible to have a variable as Input and Output at the same time (though Param and Output can be used together).

- If 'runoff' is not settable, where is the start point of the current runoff module? Any recommendation on how to implement a new module?

**Comment by peter-devoil** [comment]
There used to be a facility for setting observed runoff during calibration exercises - [looks like it's still here](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/SoilWat/SoilWat.for#L576). I doubt if anybody's used it for years, but give it a go. You'll need a custom ini file that defines the optional variable "observed_runoff" - a string. Soilwat will ask for that variable every day. Then you can write your manager script to implement that variable.

I strongly advise having a talk with the DNR people that wrote the soilwat. I suspect they've tried a whole bunch of different algorithms in the past, and can suggest a good reading list.

**Comment by BrianCollinss** [comment]
Thanks Peter. Just to clarify, does the Manager need to keep rewriting **observed_runoff** day by day?

**Comment by peter-devoil** [comment]
No, observed_runoff goes in your Soil.xml: `<observed_runoff>any_old_name</observed_runoff>`

Then your manager2 has a variable (could be a get/set variable)

```
[Output, Description="calculated runoff", Units="mm"]
public double any_old_name = 42;
```

At some time, soilwat will ask the system for "any_old_name", and get the number 42 back.

**Comment by BrianCollinss** [comment]
Aha!!! So I only need **observed_runoff** in the Soil.xml and then everything else must be set via the Manager. Smart! I will try it. Thanks heaps.

**Comment by peter-devoil** [comment]
Yes - the original concept was to create a [patchinput](https://www.apsim.info/documentation/model-documentation/infrastructure-and-management-documentation/patchinput/) format data file with a column of runoff data, then tell soilwat to read whatever's in that column

**Comment by BrianCollinss** [comment]
Yeah, it is working!

![image](https://user-images.githubusercontent.com/39573622/124687632-a1b2f080-df18-11eb-8932-830f070c2901.png)

**Comment by BrianCollinss** [comment]
Would the PatchInput module work with SoilWat/all modules?

**Comment by peter-devoil** [comment]
Yes, it's in the Meteorological folder of the standard toolbox.
