### ISSUE TITLE
Skip Row: Single

### ISSUE THREAD

**Issue by BlackEarthAgronomy** [APSIMInitiative/APSIMClassic#2072]
I'm running probability exceedence charts for Sorghum but when adjusting to single skip row there is no change in the yield spread in the chart.

**Comment by jbrider** [comment]
@BlackEarthAgronomy What location (met) and what type of soil are you using?

**Comment by BlackEarthAgronomy** [comment]
Brookstead (my own created Met file)
Heavy black soil (Mywybilla)

**Comment by jbrider** [comment]
You might have to upload a zip file of your apsim file and met file to check what is happening.
There may not be great differences, but you should be able to tell that they are different.

**Comment by BlackEarthAgronomy** [comment]
@jbrider 
[Sorghum Skip Issue.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6839873/Sorghum.Skip.Issue.zip)

**Comment by jbrider** [comment]
[Sorghum.Fix.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6844327/Sorghum.Fix.zip)
@BlackEarthAgronomy I've made a fix to the script around the skiprow configuration.
Sorghum wasn't using the same parameter configuration as the code in the manager script.

**Comment by sarahcleary** [comment]
@BlackEarthAgronomy - if you have any questions with respect to licensing APSIM, please contact apsim@csiro.au. 
More information can be found here: https://www.apsim.info/download-apsim/ and https://www.apsim.info/download-apsim/commercial-use/
