### ISSUE TITLE
harvesting rule & reporting frequency

### ISSUE THREAD

**Issue by xuyang7912** [APSIMInitiative/APSIMClassic#2073]
When I simulated cotton production using the model, I found that my yield was affected by the REPORTING frequency. When I simulate yield changes over the last 30 years, the results vary greatly between reporting frequency set to end_day or harvesting output yields. My settings are the default Cotton Defoliation and Harvesting rule and I would like to know why I have this problem of large yield variation.

**Comment by xuyang7912** [comment]
If I want to output 30 years of yield directly, and this result is the same as I output each year separately, how should I set it up?

**Comment by BrianCollinss** [comment]
If you just need to print out the seasonal outputs, set the frequency 'harvesting', which will make APSIM geenrate an output file when harvest is being simulated.

**Comment by xuyang7912** [comment]
When I set the setting frequency to "harvesting", I find that the yield of direct output for one year and direct output for 30 years vary by a lot, why is that?@BrianCollinss

**Comment by BrianCollinss** [comment]
What do you mean by direct output?Do you reset soil moisture and N concentration at sowing?

**Comment by xuyang7912** [comment]
I have 30 years of weather data and when I output only one year or when I output 30 years, the yield of the first year is the same and the results of the remaining 29 years show a big difference.@BrianCollinss

**Comment by BrianCollinss** [comment]
Maybe I'm missing something. Do you expect that yield in year 2 be the same as year 1 or year 3?

**Comment by xuyang7912** [comment]
First the clock is set to 1961-1990, which will output a 30 year file with one yield value per year. However, when I set the clock to 1962 or 1963, there is a difference between the yield value calculated for a single year and the yield value calculated directly for 30 years.

**Comment by BrianCollinss** [comment]
Do you not reset soil moisture at sowing or on a specific day of year?

**Comment by xuyang7912** [comment]
All the same except for the clock setting

**Comment by BrianCollinss** [comment]
Could you share your apsim file?

**Comment by xuyang7912** [comment]
Can you share your email address? I will email the file to you.

**Comment by BrianCollinss** [comment]
***@***.***

**Comment by xuyang7912** [comment]
xuyang7912@gmail.com 
I did not see your email, can you send me an email and I will reply to you with the file.
