### ISSUE TITLE
DBNull

### ISSUE THREAD

**Issue by joannasimms** [APSIMInitiative/APSIMClassic#2074]
I have just downloaded APSIM and was following the tutorials, however, when I load any of the example files I get the error "Object cannot be cast from DBNull to other types" when I click on the met icon.

**Comment by sarahcleary** [comment]
@hol430 - are you able to help?

**Comment by hol353** [comment]
APSIM 7.10 usually requires the computer to be on Australian locale. Are you on Australian locale? If not, as a test, try changing your computers region to Australia and regional format to English (Australia).

**Comment by joannasimms** [comment]
Hi, I found the problem, for some reason C could not be found by APSIM 7.10, so I had to change some of the windows environmental variables to get them to work together. Now it works without being in the Australian locale. Thanks for the help!
