### ISSUE TITLE
Rice parameters for APSIM simulation over West Africa

### ISSUE THREAD

**Issue by Meminvegni** [APSIMInitiative/APSIMClassic#2077]
Dear APSIM communities,

Please I'm calibratin APSIM using rice crop, and I would like a documents or any information which can help me when calibrating APSIM for rice simulation

Thanks with best regards

**Comment by hol430** [comment]
Hi @Meminvegni, this repository is for apsim next generation, which doesn't have a rice model. Questions about the old version of apsim (apsim classic) should be directed to [this repository](https://github.com/APSIMInitiative/APSIMClassic). I've just transferred this question to the apsim classic repository.

To answer the question, the rice model's documentation may be found [here](https://www.apsim.info/documentation/model-documentation/crop-module-documentation/riceoryza2000/).
