### ISSUE TITLE
maize grain yield zero

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/APSIMClassic#2079]
I am running maize in Michigan US. I am getting reasonable results for biomass but not grain yield at all, it is zero. I have checked N and water stresses and changed the cultivars but it still persist. Also checked the MET file and everything seems to be ok. Could someone help me with this? sim and met file attached.
[mcswiney.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6927839/mcswiney.zip)
[mcswiney.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6927841/mcswiney.zip)

**Comment by jbrider** [comment]
@JJguri You are sowing at 100 plants/m2. Have you got an extra 0 there?

**Comment by JJguri** [comment]
good catch! sorry just closing the issue.
