### ISSUE TITLE
Issue with .sim when has swim3

### ISSUE THREAD

**Issue by AfshinGhahramani** [APSIMInitiative/APSIMClassic#2081]
Hi all,
I have APSIM files (7.10) with swim soil water and is running fine, but cannot run when converting .apsim to .sim. the only error in sum file is:
     Fatal  Error
File "" does not exist
.sim files run when soil water module is SoilWat

Any clue for me, please?
Regards
Afshin

**Comment by peter-devoil** [comment]
Can you run the example simulation without failure? If not, you have an installation error.
If you can run it, then it's a process of progressively modifying the example with your additions to see which bit is breaking

**Comment by sarahcleary** [comment]
@ AfshinGhahramani  - did you solve your problem?

**Comment by AfshinGhahramani** [comment]
Hi Sara,
Yes all good. It was so simple, just a naming convention.

Regards
Afshin

**Comment by sarahcleary** [comment]
excellent, will close the issue
