### ISSUE TITLE
Testing fertilisation scenrios using Manager2 script

### ISSUE THREAD

**Issue by Achraf-UM6P** [APSIMInitiative/APSIMClassic#2083]
Hello,
I would like to ask you this question, to know is there a possibility of using a Manager2 script to create a set of fertilization scenarios (Application of N and P fertilizers during crop season) and choose  the most optimal scenarios for crop growth outputs (eg Biomass, Root biomass, yield ...). And if possible, can you give me a similar example of this script?

Thank you
Best regards

**Comment by peter-devoil** [comment]
There's a good manager1 example in the [factorials page](https://www.apsim.info/support/apsim-training-manuals/construct-a-factorial-simulation-in-the-user-interface/). Manager2 isn't much different
