### ISSUE TITLE
Invalid template option

### ISSUE THREAD

**Issue by caityp** [APSIMInitiative/APSIMClassic#2084]
I recently changed the file path for a few source documents in my simulation. I'm not sure if that's related to this fatal error I'm getting:

fatal error: invalid template option in doPlantNStress
Component name: paddock.wheat

As far as I can tell, all .ini docs and file paths for other dependent files (e.g., met) have been updated. Any advice on where to trace this error to?

Running APSIM classic v 7.10.

**Comment by caityp** [comment]
[westside_201718_calib_CP.zip](https://github.com/APSIMInitiative/APSIMClassic/files/6964596/westside_201718_calib_CP.zip)
This is the .apsim file in question. Looking at the simulation titled Westside_20002020_fixedsow_PRISM, although that's not the only simulation in the tree where this issue is occurring.

**Comment by peter-devoil** [comment]
Without the ini file "WheatCA2.xml" there's not much we can say. The usual process for diagnosing this sort of fault is to start from scratch with a virgin Wheat.xml file, test it to ensure that your simulation runs, then gradually add your changes in while testing each one. When the simulation stops working, you'll know which change is breaking it. 

Modifying .ini files is not for the faint hearted. Much can go wrong, as the apsim developers make little or no allowance for misconfiguration or incoherence between plant processes. If you're lucky, you'll get a warning message and be able to [search the source code](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/Plant/PlantStress.cpp#L342) for the same text.

**Comment by caityp** [comment]
Thanks! For some reason the modified .ini file works when running the simulation on the machine where the file was originally developed. When I try to run from a different machine, things fall apart (which is why I suspect a file path issue of some sort). I can sidestep this issue for now by just running on the original machine, but will give a close look to the .ini file when I try again.
