### ISSUE TITLE
N balance outputs

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/APSIMClassic#2085]
I am trying to quantify N inputs and outputs in wheat simulations. I am reporting the following variables:
```
dd/mm/yyyy as date
lai
yield
biomass
biomass_n
n_uptake
n_conc_crit
no3ppm() as no3
nh4ppm() as nh4
n_stress_expan
n_stress_photo
leach_no3
fertiliser
dnit() as dnit
dlt_n_min()
dlt_n_min_res()
```
Could I assume that `leach_no3` (kg/ha) is all N leached, `dnit` (kg/ha), is all N denitrified, and (`dlt_n_min()` + `dlt_n_min_res()`) is all N mineralised?

I also realised that the name of some variables changes accordingly with the crop, for example `n_conc_crit`, `n_stress_expan` and `n_stress_photo` are available for wheat but not for maize. Is there a way to get the same output variables for maize or other crops, e.g. sorghum?

**Comment by peter-devoil** [comment]
Maize & sorghum in 7.10 use SLN, and dont have a concept of n_conc_crit. The process is the same (a target n concentration) but the units are different. You can still calculate N concentrations though
