### ISSUE TITLE
Weather File Not Working 

### ISSUE THREAD

**Issue by tuliscot** [APSIMInitiative/APSIMClassic#2088]
Hallo  APSIMers,

[bako.txt](https://github.com/APSIMInitiative/APSIMClassic/files/7070500/bako.txt)
For some reason my weather file is not working. I am a bit rusty with APSIM (7.10 r4215) i have to admit but i am really struggling to see where i am getting it wrong. I have attached the current met file.

##########ERROR|_MESSAGE########
               APSIM  Fatal  Error
                      -------------------
     Cannot find date columns in file:
     The file must have one of the following combinations:
        a date column
        a year and day column
        a year, month and dom column. This error occurred while trying to read from input file C:\Users\xxxx\OneDrive - xxxx\Personal\Personal research\xxxx\xxxx\xxxx\Weather Data3\bako.met
     Component name: met

**Comment by zur003** [comment]
Your file has tabs rather than spaces as value separators. If you're exporting the data from Excel, export as a space-delimited (*.prn) file rather than a tab-delimited (*.txt) file.

**Comment by tuliscot** [comment]
weather filesnow working. Thanks
