### ISSUE TITLE
outputfile

### ISSUE THREAD

**Issue by zhuqianqian0907** [APSIMInitiative/APSIMClassic#2091]
Specified cast not valid,How to fix it up? 
<img width="951" alt="微信图片_20210907151625" src="https://user-images.githubusercontent.com/90237327/132301351-303b9f1d-84f5-4ff1-ad78-7d0aaf417cc8.png">
>

**Comment by zhuqianqian0907** [comment]
First of all, thank you for your answer. I want to say that since I am a beginner, I'm going to open agpasturePaddock, and under GrowthRate under ApsimFileReader I'm going to click Browse "agpasturePaddock pad.out" and then I'm going to click "plot" and it's going to pop up "specified cast is Not valid ", I really don't know why

**Comment by zhuqianqian0907** [comment]
> Could you please show a shot of what you have set inside GrowthRate graph?
First of all, thank you for your answer. I want to say that since I am a beginner, I'm going to open the example“ agpasturePaddock”, and under “GrowthRate” under the“ FileReader” I'm going to click Browse "agpasturePaddock pad.out" and then I'm going to click on "plot" and will pop up"Specified" Cast is not valid ", I really don't know why.


> Could you please show a shot of what you have set inside GrowthRate graph?

**Comment by sarahcleary** [comment]
@sno036; @her123 - can you help?

**Comment by sno036** [comment]
@zhuqianqian0907  - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.

Can you look through the output file and see if there are any non-numeric outputs below the header apart from date?
Do you get a plot if you just click on “GrowthRate” or any of the other plots?
Have you recently installed Classic for the first time? If so then reboot the computer is another suggestion.

**Comment by zur003** [comment]
Just guessing, but this might be a problem with internationalisation settings, such as date format or decimal symbol. Do you know what the settings currently are on your computer for date and number formats?

**Comment by zhuqianqian0907** [comment]
> @zhuqianqian0907 - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.
> 
> Can you look through the output file and see if there are any non-numeric outputs below the header apart from date?
> Do you get a plot if you just click on “GrowthRate” or any of the other plots?
> Have you recently installed Classic for the first time? If so then reboot the computer is another suggestion.

**Comment by zhuqianqian0907** [comment]
> @zhuqianqian0907 - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.
> 
> Can you look through the output file and see if there are any non-numeric outputs below the header apart from date?
> Do you get a plot if you just click on “GrowthRate” or any of the other plots?
> Have you recently installed Classic for the first time? If so then reboot the computer is another suggestion.

**Comment by zhuqianqian0907** [comment]
> @zhuqianqian0907 - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.
> 
> Can you look through the output file and see if there are any non-numeric outputs below the header apart from date?
> Do you get a plot if you just click on “GrowthRate” or any of the other plots?
> Have you recently installed Classic for the first time? If so then reboot the computer is another suggestion.

> I am using an old version APSIM710-r4216.
>When I examine the Output file, I can see non-numeric outputs below the header apart from dates, such as "01/ jan/1980 ", "01/Feb/1980" and so on under "dd/mmm/yyyy"
> I don not get a plot if I just click on “GrowthRate” or any of the other plots.
>I have not installed Classic for the first time recently,I have installed Classic many times, it should not be a software problem, and I have restarted my computer, but it has no effect.

**Comment by zhuqianqian0907** [comment]
> @zhuqianqian0907 - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.
> 
<img width="954" alt="微信图片_20210913104340" src="https://user-images.githubusercontent.com/90237327/133016235-4d9cac20-5889-4f03-9866-95c94a5147f2.png">
<img width="951" alt="微信图片_20210913104347" src="https://user-images.githubusercontent.com/90237327/133016237-a23748e4-c683-498e-aed6-4055c528e4f2.png">

> I am using an old version APSIM710-r4216.
>When I examine the Output file, I can see non-numeric outputs below the header apart from dates, such as "01/ jan/1980 ", "01/Feb/1980" and so on under "dd/mmm/yyyy"
> I don not get a plot if I just click on “GrowthRate” or any of the other plots.
>I have not installed Classic for the first time recently,I have installed Classic many times, it should not be a software problem, and I have restarted my computer, but it has no effect.

**Comment by sno036** [comment]
Can you zip up your simulation file, weather file, summary and output file please and attach it to a comment here. (Also there is no need to close the issue each time you comment, it just creates a lot of email messages)

**Comment by zhuqianqian0907** [comment]
> @zhuqianqian0907 - I am using an old version (r4191 - and I don't want to update from this right now) and I cannot replicate this error.
> 
> Can you look through the output file and see if there are any non-numeric outputs below the header apart from date?
> Do you get a plot if you just click on “GrowthRate” or any of the other plots?
> Have you recently installed Classic for the first time? If so then reboot the computer is another suggestion.

> I am using an old version APSIM710-r4216.
>When I examine the Output file, I can see non-numeric outputs below the header apart from dates, such as "01/ jan/1980 ", "01/Feb/1980" and so on under "dd/mmm/yyyy"
> I don not get a plot if I just click on “GrowthRate” or any of the other plots.
>I have not installed Classic for the first time recently,I have installed Classic many times, it should not be a software problem, and I have restarted my computer, but it has no effect.
<img width="954" alt="微信图片_20210913104340" src="https://user-images.githubusercontent.com/90237327/133016610-be539408-7e60-4f93-9175-df1de6d9f856.png">
<img width="951" alt="微信图片_20210913104347" src="https://user-images.githubusercontent.com/90237327/133016611-f82a31c8-ca52-44ef-9bcf-7a30889d8801.png">

**Comment by zhuqianqian0907** [comment]
> @sno036; @her123 - can you help?

Thank you very much for your help.Problem solved. It really is the date format.

**Comment by zhuqianqian0907** [comment]
> Just guessing, but this might be a problem with internationalisation settings, such as date format or decimal symbol. Do you know what the settings currently are on your computer for date and number formats?

Thank you very much for your help.Problem solved. It really is the date format.

**Comment by zhuqianqian0907** [comment]
> Can you zip up your simulation file, weather file, summary and output file please and attach it to a comment here. (Also there is no need to close the issue each time you comment, it just creates a lot of email messages)

Thank you very much for your help.Problem solved, It really is the date format.At the same time, I would like to express my apology to you. As a new hand, I may not be proficient in operation, so I have brought you some troubles in emails.

**Comment by sno036** [comment]
No problem (most of use have been there!). Goof to know that it is sorted.

**Comment by zur003** [comment]
Just a bit curious - what date format were you using that caused the problem? It would be good if we could make this a bit more robust, so that others don't experience the same problem.
