### ISSUE TITLE
Leaf area development in the APSIM pigeonpea model

### ISSUE THREAD

**Issue by yashvirchauhan** [APSIMInitiative/APSIMClassic#2092]
I am trying to verify the performance of the APSIM pigeonpea model (Classic) for South Burnett and Emerald environments. The model was underpredicting canopy development and hence yield and total dry matter, as it simulated very few leaves on the main stem. Tried to make changes to the node appearance rate  <y_node_app_rate> 32  32    32    32</y_node_app_rate> to see if that will fix the problem. When the node appearance rate was reduced from 32 to 5 (i.e., <y_node_app_rate> 5  5   5    5</y_node_app_rate>), the leaf area index it simulated was within the expected range. This increase was the opposite of what was expected after reducing the node appearance rate. Is there a bug in the code? Can someone familiar with the code check this? Appreciate help.

**Comment by sarahcleary** [comment]
@yashvirchauhan - transferred this question to the APSIM Classic repository.

**Comment by peter-devoil** [comment]
Yash, can I bother you for some sample files please? The tests in the repository are all .con/par files.
