### ISSUE TITLE
How to adjust the yield of maize in APSIM7.10

### ISSUE THREAD

**Issue by Chuanwei-zhang-ucas** [APSIMInitiative/APSIMClassic#2098]
In previous version of 7.7, we can control the yield by grian-gth-rate and grain-filling-rate, but what the parameters are now in version of 7.10

**Comment by peter-devoil** [comment]
Which crop are we talking about?

**Comment by Chuanwei-zhang-ucas** [comment]
It is maize.

**Comment by peter-devoil** [comment]
Hi chuanwei,

The maize model was rewritten in 7.10 and as you say, those parameters are gone. The grain number is set by PGRxx and GNxx; and max size by potKernelWt. The rate of filling is determined by supply.

There's a [paper](https://academic.oup.com/insilicoplants/article/1/1/diz003/5511759) describing the new algorithms.
