### ISSUE TITLE
Potential issues in Sugarcane module

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2110]
- By default, lodging is supposed to reduce number of green leaves by 15% (`<lodge_redn_green_leaf>0.85</lodge_redn_green_leaf>`). This effect is aplied temporarily, i.e. on one day, and then the **maximum** number of green leaves is reset to its default (13), i.e. this reduction is only applied when number of leaves that die on current day is calculated.
https://github.com/APSIMInitiative/APSIMClassic/blob/00be2223115c54b3a30b8956ef5288f4e752cf10/Model/Sugar/Sugar.for#L5446-L5450

- As for lodging effect on RUE, the default impact is 8%, but it will be ineffective if other stress factors are larger. Is lodging impact not independent of other sources of stress? 
https://github.com/APSIMInitiative/APSIMClassic/blob/00be2223115c54b3a30b8956ef5288f4e752cf10/Model/Sugar/Sugar.for#L432-L435

- Should the effect of lodging on RUE not be permanent? Currently it's applied only on the day lodging is triggered then RUE is reset to its default value.

- If lodging is triggered multiple times, should RUE not be reduced progressively?

- The larger the stress, the larger the sucrose fraction. At least in some simulations, if this is reversed, the simulation of sucrose content significantly improves.
https://github.com/APSIMInitiative/APSIMClassic/blob/00be2223115c54b3a30b8956ef5288f4e752cf10/Model/Sugar.xml#L529-L530

**Comment by JodyBig** [comment]
My only comment is based on my in field experience. Effects of lodging can be temporary with the canopy recovering. Which raises the issue of severity of lodging.

**Comment by BrianCollinss** [comment]
@JodyBig Thanks Jody. Do you think this temporary effect is sufficiently simulated if RUE is nly affected on one day? Should there be a better rule for recovery?
