### ISSUE TITLE
leaf number in APSIM-maize 7.10

### ISSUE THREAD

**Issue by shaoyuGao** [APSIMInitiative/APSIMClassic#2111]
Hi, I have three questions 
1.The number of maize leaves I observed is 20,but simulated 14 ,so i adjusted leaf_init_rate and leaf_app_rate ,but when the number of leaf is right,phenology vary greatly.It seems like they can't both be true.
2.there are three leaf_app_rate and  two leaf_no_rate_change,How should I understand them
3.I entered the actual full irrigation amount,but The results are very different from turning on automatic irrigation.I set the water treatment,so I need to solve it

**Comment by peter-devoil** [comment]
@jbrider knows about leaf development.

WRT irrigation - the irrigation component's automatic setting uses a threshold (fasw) to irrigate to DUL. Changing this threshold will change the interval between irigation events - lots of little ones vs a few big ones. If you have a starting water content and a schedule, you're better off using the observation and looking for other sources of error (eg LL / LL15).

**Comment by jbrider** [comment]
@shaoyuGao as per your previous issue: https://github.com/APSIMInitiative/APSIMClassic/issues/2043
I recommended this paper that goes into some detail how the maize model works: [Modelling the nitrogen dynamics of maize crops – Enhancing the APSIM maize model](https://www.sciencedirect.com/science/article/pii/S1161030117301880)

If you have a look through the many existing cultivars in the maize.xml file you will not find any existing cultivars that change  leaf appearance or leaf initiation.  Unless you have measured a significantly different leaf appearance rate, I would suggest using the existing appearance rate and alter tt_emerg_to_endjuv (Thermal time from Emergence to EndJuvenile) which will have a direct effect on controlling the final leaf number - and on phenology.  

The final leaf number is calculated as Thermal Time from Emergence to FloralInit divided by Leaf Initiation rate plus the number of leaf primodia in the seed (usually 6).  

If you have a look in the maize.xml you will see a cultivar named 19leaf - this will probably be a better place to start than changing leaf appearance.

**Comment by shaoyuGao** [comment]
Thank you for your help and In apsim the transpiration efficiency is how to calculte
