### ISSUE TITLE
Fertilizer Application

### ISSUE THREAD

**Issue by kgbrusola** [APSIMInitiative/APSIMClassic#2118]
Hi everyone! I am new in using APSIM. I would like to incorporate the amount of fertilizer being applied in my study area. I have found the options of the available fertilizers in the model and I could not find the fertilizer that is applied in the field. I have the NPK values such as Triple 14/Complete (14-14-14) and muriate of potash (0-0-60). How can I incorporate these details in the model? Thank you.

**Comment by BrianCollinss** [comment]
Not sure about phosphoruse. But you can have N fertilisers. You just need to know the N content of the fertiliser you are interested in (e.g. Urea has 46% of elemental nitrogen so you would need to apply that number on the total amount of fertiliser applied).

**Comment by kgbrusola** [comment]
Hi! Thank you for your response. I have found the list of fertilizers available in APSIM. Is there a way to modify them? For example, I want to change the N value to 14%. Thanks.

**Comment by BrianCollinss** [comment]
If you know the type of fertiliser you need to aplply, I think you can just appliy 14% of total N weight and that will do it.

**Comment by kgbrusola** [comment]
Sorry for the confusion, where exactly should I put it? I only found tasks like Fertilise on fixed date, Fertilise on days after sowing, etc. and there is only a dropdown on the fertiliser type. Thank you.

**Comment by BrianCollinss** [comment]
If you look at what is inside the scripts (e.g. start_of_day or end_of_day), you will see a command like

fertiliser apply amount = 253 (kg/ha), depth = 100 (mm), type = urea_n ()

In this example, 253 kg/ha N is added to the depth of 100 mm of soil. This [link](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/fertiliser/) might help.

@peter-devoil I am not quite sure how APSIM differentiates between NO3, NH4 and UREA? What is Urea BTW? How is ti processed by soil N module?

**Comment by kgbrusola** [comment]
Hi @BrianCollinss!

I have this computation for the fertilizer. Is it correct to add the amount in kg as urea_n for N and broadcast_p for P? I am not sure how to deal with K. Thanks!

![image](https://user-images.githubusercontent.com/42596091/144530697-da7abd67-9ef3-4356-bc80-5d30760661cc.png)

**Comment by BrianCollinss** [comment]
Thats what you need to do. No K in APSIM.

**Comment by kgbrusola** [comment]
Is it necessary to have the "Phosphorus" task under soil before I add the Fertilise with Phosphorus at sowing? Thank you.

![image](https://user-images.githubusercontent.com/42596091/144536672-5c6fdee2-b8d7-4921-a387-c9c4959b0986.png)
