### ISSUE TITLE
Using Apsim UI for soybean modeling with climate control and meeting fatal error

### ISSUE THREAD

**Issue by byaooo** [APSIMInitiative/APSIMClassic#2119]
Hi, I am using Apsim 7.10-r4158 to simulate soybean under different CO2 level, but it comes to a fatal error “CO2 isn’t at default level, and plant has no CO2 x(TE, nConc) parameterisations. Component name : paddock.soybean.”
And I try to add <CO2 effects on Transpiration Efficiency> part to soybean.xml, but it does not work.
What can I do to simulate the growth of soybean under different CO2 concentrations using Apsim? Thanks for help.

**Comment by peter-devoil** [comment]
For this error message, the parameters it's looking for are x_co2_te_modifier, y_co2_te_modifier, x_co2_nconc_modifier and y_co2_nconc_modifier.  You need these in your modified soybean xml file, and you also need an ini file component to tell the soybean componenent to read the modified file.

We'll need a few more details about "it does not work" to help further.

P

**Comment by byaooo** [comment]
> For this error message, the parameters it's looking for are x_co2_te_modifier, y_co2_te_modifier, x_co2_nconc_modifier and y_co2_nconc_modifier. You need these in your modified soybean xml file, and you also need an ini file component to tell the soybean componenent to read the modified file.
> 
> We'll need a few more details about "it does not work" to help further.
> 
> P

Thank you, it works!!
