### ISSUE TITLE
PAR intercepted by the crop

### ISSUE THREAD

**Issue by tefera21** [APSIMInitiative/APSIMClassic#2124]
The APSIM-wheat module document calculates PAR intercepted by the crop from total solar radiation (instead of using PAR, or half of the total solar radiation) as in eq. below:

I = I0(1 − exp(−k × LAI)), where I0 = total solar radiation (https://www.apsim.info/wp-content/uploads/2019/09/WheatDocumentation.pdf) 

Let me say I have fraction of intercepted solar radiation driven from Ceptometer and I want to calculate radiation use efficiency to be used in APSIM. Am I still expected to use total solar radiation to calculate intercepted PAR (fractional interception x the total daily PAR)?  If yes, why not PAR?

**Comment by peter-devoil** [comment]
Any suggestions, @kchenu or @byzheng?

**Comment by byzheng** [comment]
I believe we should still use total radiation instead of PAR as RUE (1.24 in default) is calculated based on the total radiation when daily photosynthesis is calculated.

Other processes in APSIM might also use total radiation.

**Comment by tefera21** [comment]
> I believe we should still use total radiation instead of PAR as RUE (1.24 in default) is calculated based on the total radiation when daily photosynthesis is calculated.
> 
> Other processes in APSIM might also use total radiation.

Thanks byzheng. But is there any reason why we use total solar radiation in APSIM when plants use PAR for photosynthesis?

**Comment by byzheng** [comment]
Have no idea about it. You have to change source codes to use PAR for photosynthesis.

B

**Comment by kchenu** [comment]
PAR and total solar radiation are very highly correlated. It would not change the results.

**Comment by tefera21** [comment]
> Have no idea about it. You have to change source codes to use PAR for photosynthesis.

Could it be possible to access the source code? the reason might explained there. Thanks

**Comment by tefera21** [comment]
> PAR and total solar radiation are very highly correlated. It would not change the results.
 I think, having two different values (i.e. 1.24 g/MJ driven from solar radiation and 2.48 g/MJ from PAR) in wheat could have effect on simulated biomass and yield.

**Comment by byzheng** [comment]
> > PAR and total solar radiation are very highly correlated. It would not change the results.
> > I think, having two different values (i.e. 1.24 g/MJ driven from solar radiation and 2.48 g/MJ from PAR) in wheat could have effect on simulated biomass and yield.

Yes agree with RUE, but just not sure whether other processes in APSIM to use total radiation.

**Comment by peter-devoil** [comment]
The source is here, there are some [old instructions](https://www.apsim.info/documentation/model-documentation/developer-documentation/building-apsim-from-source/) for building it that might still work
