### ISSUE TITLE
How to make crop phenology advanced in APSIM?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2130]
In APSIM, grain filling durations could be affected by soil water stress (scripts as below)
      
<x_sw_avail_ratio_start_grain_fill description="water availability">0.2   0.50   1.0</x_sw_avail_ratio_start_grain_fill>
      <y_swdef_pheno_start_grain_fill description="stress index for grainfilling phenology">1.0   1.0    1.0</y_swdef_pheno_start_grain_fill>

I'm wondering if we can add a column, for example, daily ozone concentration (ppb), in the met file then write the similar scripts to affect grain-filling stage?

e.g. 	        <x_o3_start_grain_fill description="o3 ">18 30 55 </x_o3_start_grain_fill>
      <y_o3_pheno_start_grain_fill description="o3 for grainfilling phenology">1 0.8 0.2</y_o3_pheno_start_grain_fill>

I have tried but this does not affect grain filling durations at all. Can anyone help? Many thanks!!

![image](https://user-images.githubusercontent.com/72141690/154965033-05aaf2c4-129c-43bc-b4d7-1f8ebe50e2d5.png)

**Comment by peter-devoil** [comment]
Hey Ke, 

This is a difficult thing to do in classic - much easier in nextgen. In classic you need to add some code to the plant model to a) read the table at initialisation, b) get o3 every day, c) calculate the stress factor, and d) perform the reduction. 

Interestingly, if you search [the code](https://github.com/APSIMInitiative/APSIMClassic/blob/8c824210c1d80fd1a51243dd52d1e6e4bd1708f4/Model/Plant/PlantStress.cpp#L559) you'll find that the parameter you mention isn't used anywhere - it was written but no crop implementations never got around to using it. That's one of the perils of writing a library..

But the [wheat implementation of this procedure](https://github.com/APSIMInitiative/APSIMClassic/blob/8c824210c1d80fd1a51243dd52d1e6e4bd1708f4/Model/Plant/Phenology/CWFixedPhase.cpp#L13) shows how it's put together..

This assumes that you can build classic - which involves setting up visual studio & sundry fortran compilers. Its a headache..

**Comment by KeLiu7** [comment]
Ah, thanks Pete.. I agree its a headache thing... I will have another try and let you know the progress
