### ISSUE TITLE
Simulated results are different under the same settings in APSIM Wheat

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2133]
Dear all,

I just found an interesting thing in APSIM-Wheat. For example, if we run simulation for the year of 2010 then we replace 2010 into 2032 in the met file and run again.  We will get different emergence date (e.g. 30 May in 2010 and 29 May in 2032). Sowing date is 19-May in both simulations and other settings are identical. 

Does anyone know why this happened? I think we should get the same results?

**Comment by peter-devoil** [comment]
Can you see if your conditions are the same? ie the rainfall trigger is identical pre-sowing, and the temperature environment post sowing?

**Comment by KeLiu7** [comment]
> Can you see if your conditions are the same? ie the rainfall trigger is identical pre-sowing, and the temperature environment post sowing?

Yes. Peter. Everything is the same. I think APSIM extracts day of year to run the model rather than date? 2010 is a common year but 2032 is a leap year. When simply replacing 2010 into 2032, the day of year is not matched (as Feb has 29 days in 2032 but 28 in 2010). Might because of this?

**Comment by peter-devoil** [comment]
Perhaps you could change your planting rule to fire on the same julian day; or be satisified that the if differences only appear in leap years then the problem is with leap years..

But I can tell you than the plant model doesnt use year - though it does use day of year to work out day length..
