### ISSUE TITLE
An warning error occurred during modeling soybean

### ISSUE THREAD

**Issue by byaooo** [APSIMInitiative/APSIMClassic#2135]
Hi,
From the first day of the simulation(2015-1-1), some warning errors are reported in summary file. These errors occur every few days:
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     Bound check warning while getting variable.
     Variable  : st(1)
     Condition : -15.00 <= -17.81 <= 50.00
     Component name: paddock.soybean
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     Bound check warning while getting variable.
     Variable  : st(2)
     Condition : -15.00 <= -16.49 <= 50.00
     Component name: paddock.soybean
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     Bound check warning while getting variable.
     Variable  : st(3)
     Condition : -15.00 <= -15.21 <= 50.00
     Component name: paddock.soybean
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Another errors occurred after the end of the crop growth period：

30 December 2015(Day of year=364): 
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     soil_temp =    -20.95165
             less than lower limit of   -20.00000
     Component name: paddock.Soil Nitrogen
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                      APSIM Warning Error
                      -------------------
     soil_temp =    -20.01674
             less than lower limit of   -20.00000
     Component name: paddock.Soil Nitrogen
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I could not find the place to modify the soil_temp and st, and there errors doesn't exit when I change a metfile, how can I solve these errors? or these errors are not important to the yield of soybean?

Thank you!

**Comment by peter-devoil** [comment]
Have a look at a) tav and amp in your met file, and b) minimum temperature in the same place.

**Comment by byaooo** [comment]
> Have a look at a) tav and amp in your met file, and b) minimum temperature in the same place.

Thanks, the temperature at the site is really low and that should be the reason.
