### ISSUE TITLE
APSIM input data

### ISSUE THREAD

**Issue by BB1464** [APSIMInitiative/APSIMClassic#2139]
Good Morning Dear APSIM Expert,
      Please I am working on the apsim classic but I don't know how to bring in my dataset for observed growth and phenological stages into the module, I will really appreciate if I get response here. Thank you and best regard.

**Comment by peter-devoil** [comment]
Hi,
Apsim doesn't directly use observed data - it may use parameters developed from observed data, but not the data itself. The usual workflow is to construct simulations that represent your dataset / experiment; ie correct soil, met and crop management data, and then compare the simulation output with the data itself. That comparison can be done with the tool of your choice - excel, R...

**Comment by BB1464** [comment]
@peter-devoil, thank you for your reply, I really appreciate!!!
