### ISSUE TITLE
Cannot use defoliation or cut manager in Millet simulations

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2144]
Does anyone know how to use cut or defoliation in Millet simulations?  I have tried both managers but none of them work evidenced by unchanged yield or biomass. I have attached my simulations for check. Thank you!
[Millet.zip](https://github.com/APSIMInitiative/APSIMClassic/files/8598570/Millet.zip)

**Comment by peter-devoil** [comment]
Ah. That old millet model. There was a reason we invented nextgen; and old code like millet was one of them - it was quite a feat at the time, but there are easier ways to do it nowadays..

The short answer is "Use the WFmillet prototype". It's got the logic to handle the phenology component going backwards. 

The long answer: that cut manager is sending a "cutpasture" event to the millet module, which millet has never heard of, so ignores it. No effect as you describe. 

In other crops, we use a harvest event for this. The lucerne example simulation shows how to send (potentially many repeated) harvest events based on phenology. When the system wants to move to another phase (eg a wheat crop) the lucerne  crop is sent an "end_crop" event which terminates it.

**Comment by KeLiu7** [comment]
> Ah. That old millet model. There was a reason we invented nextgen; and old code like millet was one of them - it was quite a feat at the time, but there are easier ways to do it nowadays..
> 
> The short answer is "Use the WFmillet prototype". It's got the logic to handle the phenology component going backwards.
> 
> The long answer: that cut manager is sending a "cutpasture" event to the millet module, which millet has never heard of, so ignores it. No effect as you describe.
> 
> In other crops, we use a harvest event for this. The lucerne example simulation shows how to send (potentially many repeated) harvest events based on phenology. When the system wants to move to another phase (eg a wheat crop) the lucerne crop is sent an "end_crop" event which terminates it.

Hi Peter,

How can I make the following arguments work in my simulations? Could you please edit them in a manager and send back to me? Thanks!

      HarvestType hdata = new HarvestType();
      hdata.Remove = 0.0;  / specify fraction (0-1)
      paddock.Publish("harvest", hdata);
or
      HarvestType hdata = new HarvestType();
      hdata.Height = 100;  // height in mm
      paddock.Publish("harvest", hdata);
