### ISSUE TITLE
Unprompted fertilization events when using FertOnEvent Manager.Net

### ISSUE THREAD

**Issue by caityp** [APSIMInitiative/APSIMClassic#2149]
Hi there,
I am using the FertOnEvent rule to trigger fertilizer application whenever an irrigation event happens. The simulation is correctly applying fertilizer on irrigation events, but also adding a bunch of "phantom" fertilizer applications on days where irrigation does not happen. 
Simulation in question is attached. Any idea what might be going wrong?
[Visalia_200020_fixedsow_PRISM_fert.zip](https://github.com/APSIMInitiative/APSIMClassic/files/8765868/Visalia_200020_fixedsow_PRISM_fert.zip)

**Comment by peter-devoil** [comment]
There's a lot of managers in there. I suggest you turn them all off, and re-add one by one until your "phantom"s appear.

**Comment by caityp** [comment]
That did the trick. There was a conflict with another manager that set irrigation allocations and triggered irrigation at soil water deficit thresholds. The FertOnEvent manager would trigger fertilization when the irrigation threshold was hit, even if irrigation allocations were not available. I solved this by adding a conditional statement to the FertOnEvent manager to not allow fertilizer applications if allocation = 0. 
Thanks for the help!
