### ISSUE TITLE
How to calculate available dry matter yield in APSIM-Lucerne?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2151]
Does anyone know how daily avail_dm is calculated in APSIM-Lucerne? Is it similar to other crops below?

APSIM estimates above-ground growth from two calculations per day, one limited by radiant energy and the other limited by water available for transpiration. The lesser of these two values gives the biomass production for the day.

Many thanks!

**Comment by peter-devoil** [comment]
Yes, they're all much the same. The lucerne model is structurally very similar to the wheat model, mostly differing in grain DM allocation methodology - so the [detailed  description](https://www.apsim.info/wp-content/uploads/2019/09/WheatDocumentation.pdf) is mostly applicable.

**Comment by KeLiu7** [comment]
> Yes, they're all much the same. The lucerne model is structurally very similar to the wheat model, mostly differing in grain DM allocation methodology - so the [detailed description](https://www.apsim.info/wp-content/uploads/2019/09/WheatDocumentation.pdf) is mostly applicable.

Thanks Pete!
