### ISSUE TITLE
Fatal error when running sim

### ISSUE THREAD

**Issue by patF01** [APSIMInitiative/APSIMClassic#2152]
Hi, i really need some help! When i run a simulation using agpasture i get this fatal error.
APSIM  Fatal  Error
                      -------------------
     Each column in an APSIM input data file must have a unit and a heading.
     Filename =
     Component name: met
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by patF01** [comment]
This is my met file. im pretty sure ive done it right but cannot figure it out 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/106586098/171136187-157e976f-7ef5-49a2-96d5-4b61a8b8c54d.png">

**Comment by zur003** [comment]
Closing as resolved.
