### ISSUE TITLE
fatal error in running a simulation

### ISSUE THREAD

**Issue by patF01** [APSIMInitiative/APSIMClassic#2153]
hi im trying to run a mixed species pasture simulation with the agpasture model and lucerne, oats, and sweet sorghum, but i keep getting this.
 APSIM  Fatal  Error
                      -------------------
     The lower limit of     0.02 in layer 4 is below the air_dry value of     0.03
     Component name: mixed species pasture.SweetSorghum

**Comment by peter-devoil** [comment]
Have a look in your soil's Water node - there's a LL for each crop. That's the LL sweet sorghum is whingeing about. 
![image](https://user-images.githubusercontent.com/1924386/171516342-cb2acae8-1e90-4eba-aaec-f8d5c49cc418.png)


There's some good background reading on soil properties to be found in the [Soil Matters](https://www.apsim.info/wp-content/uploads/2019/10/Soil-matters.pdf) handbook
