### ISSUE TITLE
Output based on zadok stage

### ISSUE THREAD

**Issue by UKum540** [APSIMInitiative/APSIMClassic#2156]
Hi, 
I am looking for a way to code to get output for three Zadok stages.
I tried to find a similar issue but could not find one. There might be someone who has done this before.
Could someone help to code for that? Could you share the code, please?
Thank you in advance.
Kind regards,
Uttam

**Comment by peter-devoil** [comment]
Use one the "Fertilise on Z stage" manager components

Change the fertilising bit to "report do_output", where report is the name of your reporting module. Dont forget the underscore in do_output

**Comment by UKum540** [comment]
Hi Peter, I could do that. It's working now. Thanks!

**Comment by zur003** [comment]
Closing as resolved
