### ISSUE TITLE
Got an error, "Root element is missing" when rerun apsim file, and the file is not readable any more!!!

### ISSUE THREAD

**Issue by HongtaoXing** [APSIMInitiative/APSIMClassic#2160]
HI

I got an error message "Root element is missing",  when I tried to rerun my apsim file, which took me weeks to get lots of information in.  

I tried to open it in notepad and got some information out in order to rewrite it in a short time. But the whole file is single line as "NUL". 

Could you please help me out for this issue? This is really an urgent problem for me. 

Thanks you so much

HT

**Comment by peter-devoil** [comment]
One of the things we used to teach in the training workshops was the need to save and test frequently: with a complex system model like apsim, it becomes very hard to sort out mistakes or attribute changes when multiple edits are all jumbled together, far easier to make simple changes and test for the effects of those changes.

A frequent "bad, internal" error from apsim is an unhandled exception and often the only way to recover from it is to delete the file and restore from a backup/copy.

**Comment by HongtaoXing** [comment]
Thanks, Peter. 
From this, I would think more to balance a big apsim file with single optimisation code with multiple apsim files with little bit complex optimisation code. And also, keep apsim backups more frequently. 
One suggestion will be if APSIM gives an warning to save the apsim file to another drive, when APSIM is running in the other hard drives and the hard drive suddenly not accessible for many reasons. 
Thanks.
Have a great day. 
HT
