### ISSUE TITLE
loadApsim_R

### ISSUE THREAD

**Issue by UKum540** [APSIMInitiative/APSIMClassic#2162]
Hi,

I have generated >1000 out files via running a factorial simulation in APSIM classic. Now I am trying to read and combine all of them using "loadApsim" function in the APSIM package. 

After reading the first file in the directory it throws an error. "Error in `[[<-.data.frame`(`*tmp*`, ncol(data) + 1, value = "7.10 r4158") : 
  replacement has 1 row, data has 0"
  
I guess, this is because the file (s) does not have clearly categorized columns in the first three rows. 

ApsimVersion = 7.10 r4158
factors = Inital Nitrogen=20%+;ZS32=N0;ZS37=N0;ZS47=N0
Title = Fl;Inital Nitrogen=20%+;ZS32=N0;ZS37=N0;ZS47=N0 NMin25 Zadock32

Is there any solution to deselect first three rows from the outfile or upload all of them as a list under one vector and work on each of the later?

The code that I am using:

d  = APSIM:::loadApsim(dir = "C:/AK/tool/APSIM/APSIM_sim/Factorial/ZS",
                       loadAll= T, filter = '\\.out', returnFrame=T, fill=T, addConstants=T, n = 0)

Thank you

Uttam

**Comment by peter-devoil** [comment]
I've used variants of this (ugly) code in the past
```
# Generic function to read apsim output files. Adds factor levels if found.
read.apsim <- function(apsim.name) {
  header<-readLines(apsim.name, n=25)
  if (length(header) == 0 ) {return(NULL)}
  # assumes year or date is one of the column names
  i<-grep("year|date", trimws(tolower(header)), ignore.case=T)[1]  #look for a header with these keywords
  apsim <- read.table(apsim.name,skip=i+1,na.strings=c("NA","?"))
  names(apsim) <- unlist(strsplit(trimws(header[i]), " +"))
  
  # decode factor levels in header
  i<-grep("factors", trimws(tolower(header)), ignore.case=T)[1]  #look for a header with these keywords
  for (nv in unlist(strsplit(substring(header[i],11),";"))) {
    apsim[[ unlist(strsplit(nv, "="))[1] ]] <- unlist(strsplit(nv, "="))[2]
  }
  return(cbind(apsim.name, apsim))
}
...
df<-do.call(rbind, lapply(list.files(pattern="^Maize_.*[0-9]\\.out$"), read.apsim))
```
If you have multiple output files (eg daily and harvest), then you'll likely have to be a bit more careful with the pattern argument to list.files().

**Comment by UKum540** [comment]
Hi Peter, it worked with some modification. Thanks!! Sorry for the late respone, I dived deep into finishing that part of my work.
