### ISSUE TITLE
Request for Article on Freebairn soil erosion models 

### ISSUE THREAD

**Issue by araza1947** [APSIMInitiative/APSIMClassic#2163]
Dear APSIM community,

I am working on erosion estimation using APSIM erosion component. I am trying to investigate the fixed constants and empirical coefficients in Equation 1 (Freebairn model).  I was looking for original article of Equation 1 (https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/erosion/) for Submodel "Freebairn" soil erosion equations.

I searched in the article "Freebairn, D.F. and Wockner, G.H. (1986). A study of soil erosion on Vertisols of the Eastern Darling Downs, Australian Journal of Soil Research , 19 , 133-46" but equations derived in it are different from the equation 1.

It would be great if you provide me the related articles.

Your early response will be highly appreciated. 

Best Regards,
Ahsan Raza
University of Bonn, Germany

**Comment by zur003** [comment]
Closing as resolved
