### ISSUE TITLE
APSIM model simulates greenhouse gases

### ISSUE THREAD

**Issue by wky1221** [APSIMInitiative/APSIMClassic#2164]
APSIM模型 模拟温室气体时 outputfile 选component filter 里的soil, 可是只有N2O ，没有CO2和CH4，请问这两个气体应该选择什么可以输出呢？是否有公式转化呢？

When simulating greenhouse gases in the APSIM model, the ‘outputfile’ selects ‘soil’ in the ‘component filter’, but there is only N2O, but not CO2 and CH4, what should I choose to output these two gases? Is there a formula to convert them?

**Comment by peter-devoil** [comment]
Not that I'm aware of, sorry.

I vaguely remember @sno036 saying words along the lines that this family of N model is inappropriate for GHG studies.

**Comment by wky1221** [comment]
Thank you very much for your answer.
