### ISSUE TITLE
Output the mean tt before a certain crop stage

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2166]
Dear all, do you have any ideas about how to output the mean thermal time 10 days before flowering and 15 days after flowering?  

I know there are some similar examples in the tracker but it doesn't work for me... 

@jbrider @peter-devoil @hol353 Many thanks for your help!

**Comment by peter-devoil** [comment]
You can treat the tracker as a ringbuffer, and if it's the correct length, you only care about when to _stop_ adding TT values to it. 
[kl.zip](https://github.com/APSIMInitiative/APSIMClassic/files/9145978/kl.zip)

**Comment by peter-devoil** [comment]
Correct. The outputfile's variables list shows you which variables are exported by which module. Your radiation accumulator would be looking for "radn":

![image](https://user-images.githubusercontent.com/1924386/180119009-764b9125-9e35-4fe4-aa5f-ed5305822c0b.png)

You'll find that the "delta" bit is just a peculiarity of the maize module, each module has its own idea of nomenclature.

**Comment by KeLiu7** [comment]
Thank Peter for your help😊 Already sovled!
