### ISSUE TITLE
Does APSIM R manager always look for a 32-bit version of R?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2168]
I added an R manager to my simulation on a 64-bit version of windows/R. But it seems it looks for a 32-bit version:

![image](https://user-images.githubusercontent.com/39573622/189522977-f4053aa8-2e51-4500-94cf-cf7f9282d1d9.png)

BTW, is there an advanced example of R manager somweher? beside https://www.apsim.info/documentation/model-documentation/infrastructure-and-management-documentation/r-language-component/.

**Comment by peter-devoil** [comment]
Yes. Apsim's a 32 bit app and can't share the same address space with a 64 bit app.

The RComponent example shows the basics how to publish/subscribe/get/set, and the Livsim example(Advanced/Livsim) has a lot of code, but less interaction.

**Comment by BrianCollinss** [comment]
Thanks Peter. Is there any way I can change the path to 64-bit R? What's the work-around?

**Comment by peter-devoil** [comment]
Compile apsim as a 64 bit app?
