### ISSUE TITLE
Modelling mulching effects in APSIM

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2169]
Hi APSIM community,

Is APSIM able to simulate the impacts of mulching effects on crop phenology and production?  @peter-devoil @jbrider @mcleang @hol353 

Thanks for your suggestions in advance😊

**Comment by peter-devoil** [comment]
Not that I'm aware of. Mulch (ie Surface Organic Matter) affects the N balance, and modifies soil evaporation.

**Comment by KeLiu7** [comment]
Thanks P😊
