### ISSUE TITLE
Nothing report in the APSIM Oryza Simulations

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/APSIMClassic#2173]
[Oryza.zip](https://github.com/APSIMInitiative/APSIMClassic/files/9640998/Oryza.zip)
Dear all, could you please help me check why there are no values in the output? Simulations go well without error.
 
Many thanks!

**Comment by peter-devoil** [comment]
Try sowing on day 134 (leap year)

You may need to [search the code](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/Oryza/Oryza.for) to understand some of the informative messages

**Comment by KeLiu7** [comment]
> Try sowing on day 134 (leap year)
> 
> You may need to [search the code](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/Oryza/Oryza.for) to understand some of the informative messages

It works now. Mangy thanks Peter😊
