### ISSUE TITLE
ModelOverrides running every time

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/APSIMClassic#2182]
ModelOverrides is now being triggered on StartSimulation and EndSimulation to apply overrides (and cultivars?) and then undo the changes.
This works directly against the model used by ApsimServer that was based on running Apsim once to load everything into memory then change a few small parameters each run.

@hol353  Am I missing something in how to configure overrides to allow the previous/desired behaviour to work?

**Comment by BrianCollinss** [comment]
Is there ModelOverrides in Classic?

**Comment by jbrider** [comment]
Nope. Put it in the wrong repository.
