### ISSUE TITLE
APSIM Summer Fallow Question

### ISSUE THREAD

**Issue by s-aagarwal** [APSIMInitiative/APSIMClassic#2188]
Hi, 

I am trying to model a corn and soybean rotation, similar to how it was done in the, Creating a Wheat Lucerne Rotation tutorial (https://www.apsim.info/support/apsim-training-manuals/crop-rotations-in-apsim/). For the most part, it is going well, but I have a question about the summer fallow management tool, which is shown in the image attached down below. I was wondering what it wants me to enter when it says, "Enter the date of the pause." Is this the date when the summer fallow period begins?

![Summer Fallow](https://user-images.githubusercontent.com/113123675/208523062-49a3935e-44f1-4621-a2d9-ebef5369716f.jpg)

**Comment by peter-devoil** [comment]
We get into trouble with the word "fallow" - in this case we really mean "a period of time when there is no crop" - of any length from a couple of days to a year. In this case, we've put some logic in to make sure we don't try and plant 2 crops in a single season (eg the first crop fails). 

All the SummerFallow rule does is wait until it sees the nominated day go past (15-mar), and then allow the other rules (wheat sowing @15-may) to operate. It might not be relevant in your context - it's specific to the weather sequences in the met file.

The operation of these rules - each line in the rules section - is simply to gather their value every day (you could put them individually in a daily output file to cross check), and multiply them together. If the result is non-zero, the transition to the next state is feasible.
