### ISSUE TITLE
How to simulate nitrogen leaching

### ISSUE THREAD

**Issue by Huanliu89** [APSIMInitiative/APSIMClassic#2189]
I have established a simulation with 7 nitrogen levels from 0-200, while the output variable NO3- was the same. 
Is the NO3- variable not working?

**Comment by hol353** [comment]
What is the name of the NO3 variable are you are reporting?

Is there a crop in the simulation? If so, which one?

**Comment by Huanliu89** [comment]
Dear Dean,

I have a wheat simulation, and with fertilizer amount from 0 to 200 kg/ha.
The output NO3 variable is leach_NO3(), and the mineralization (dlt_n_min) also turned out 0.

**Comment by hol353** [comment]
leach_no3 is the amount of no3N leached from the bottom layer of the soil profile. Try no3() instead.

**Comment by Huanliu89** [comment]
Dear Holzworth,
Thanks for the advice.
I have tried, and the results are as below.  So I only need to compare the no31?
And the amount seems crazy.
Treatment 1:
***@***.***
Treatment 7:
***@***.***

**Comment by Huanliu89** [comment]
Hi Dean,
I have checked the output variables of soil again, and I see that NO3 mean the nitrate but the leaching nitrate.
And the website manual file did not show the N2O emission variable.
SoilN – APSIM<https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soiln/>
***@***.***

Kind regards,
Huan
