### ISSUE TITLE
Root turnover rate - unit

### ISSUE THREAD

**Issue by SFrav** [APSIMInitiative/APSIMClassic#2192]
Would it be possible to clarify the AgPasture parameter TissueTurnoverRateRoot? The description states that this is "Reference daily DM turnover rate for root tissues (/day)". However the default value of 0.02 seems too low to be KG per hectare per day. Is this a percentage per day?

**Comment by peter-devoil** [comment]
I can't say for sure, but it's used like [a fraction](https://github.com/APSIMInitiative/APSIMClassic/blob/master/Model/AgPasture/AgPasture.Species.cs#L1276) - between 0-1. @sno036 might have better insight.

**Comment by SFrav** [comment]
Thank you, Peter.
