### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by tolawaq** [APSIMInitiative/APSIMClassic#2193]
Dears,
I am a beginner of using crop models. I studied APSIM and did some exercises with inbuilt data. Now I want to calibrate with local weather data and experimental data (Ethiopian Maize) and finally want to prepare a manuscript. Can you help me on:
-how to call local weather dataset into APSIM?
-calibrate the crop characteristics (phenology) in the model?

Kindly, I am happy if you provide with brief steps.
Thanks,

**Comment by peter-devoil** [comment]
Hi Tolawaq,

Adding local met data is covered [here](https://www.apsim.info/support/apsim-training-manuals/creating-an-apsim-met-file-using-excel/), you should be warned that a lot of people have trouble using excel to make met files (tab characters mostly), and you may find it easier to use a text based tool like [vs code](https://code.visualstudio.com/download). Make sure you examine the met charts to see that there are no outrageous values.

To "calibrate" the model, typically there are two development points that the model requires - flowering and maturity. If you have these observations, the simplest procedure is to pick a cultivar that is similar to yours, and adjust two parameters - tt_emerg_to_endjuv and tt_flower_to_maturity. This is done by creating a new cultivar, and optimisiing it. There's an outline of the procedure [here](https://www.apsim.info/documentation/model-documentation/crop-module-documentation/adding-new-cultivars-to-an-existing-crop-module/#:~:text=To%20make%20a%20new%20cultivar,it's%20unique%20within%20the%20file.).

If you don't have these observations, you're in for some guessing..

Fitting the photoperiod sensitivity parameters requires observations in contrasting photoperiod environments.
