### ISSUE TITLE
Request Assistance about APSIM compilation

### ISSUE THREAD

**Issue by yangxuening** [APSIMInitiative/APSIMClassic#2196]
Dears,
I am interested in the fusion of APSIM model and remote sensing data. Now I have some ideas about changing APSIM source code, but I'm confused about APSIM compilation. 
How to compile APSIMClassic?

**Comment by peter-devoil** [comment]
There's an old [set of instructions](https://www.apsim.info/documentation/model-documentation/developer-documentation/building-apsim-from-source/) on the website.
