### ISSUE TITLE
Is it meaningful to have 0<XF<1?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2199]
I have never seen XF be set to anything but 0 and 1. Is it meaningful to have 0<XF<1?

**Comment by peter-devoil** [comment]
(eg) if it's set to 0.5, then root advancement goes from 25mm/day to 12.5mm/day. So it will reach depths at a later date.

**Comment by BrianCollinss** [comment]
Cheers.
