### ISSUE TITLE
Question: KL=0 vs XF=0

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/APSIMClassic#2203]
I understand that setting XF < 1 will reduce the rate of growth of the root in those layers. My question is about the difference between XF=0 and KL=0 in terms of root growth. Can roots still grow into a layer of KL=0?

**Comment by hol353** [comment]
KL drives water update by the plant. KL = 0 means no uptake. It doesn't constrain the rate of root exploration through a layer though.

XF = 0 means the roots won't enter that layer. XF = 0.5 means the roots will explore the layer at half the normal rate.

**Comment by BrianCollinss** [comment]
Thanks Dean.

**Comment by BrianCollinss** [comment]
Dean, just to clarify. When KL is zero (specially in deep layers), there is no water uptake and the water stored in those layers is stuck there or will eventually drain out of the profile. I may be wrong, but APSIM does not move water from the lower layers into upper layers, does it? So, my question is, is it a better idea to exclude those layers (KL=0) when calculate total PAW, just like when XF=0?

**Comment by hol353** [comment]
Mostly you are correct except for

> I may be wrong, but APSIM does not move water from the lower layers into upper layers, does it?

There can be small amounts of water move up (upward flow). Yes, you should exclude layers when KL=0 when calculating PAW.
