### ISSUE TITLE
Remove the generic nitrification inhibitor conversion to urea

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/APSIMClassic#2227]
From [@kirstenverburg](https://github.com/KirstenVer)

I would like to request a very small change to the Solute2 module in APSIM7.10 to allow a slightly more generic nitrification inhibitor to be simulated. The current module is great and allows for very flexible parameterisation, but one aspect that is currently hard-wired and specific to DCD is its conversion to urea upon degradation. As the current code already allows for what it suggests to be a generic NitrificationInhibitor in addition to dcd, it would be a simple change to remove the conversion to urea for the NitrificationInhibitor and keep it for the dcd.
 
I know we don’t normally make changes to APSIM Classic/7.10 anymore. However, this change will greatly assist a PhD student whom I am helping. She has a chemistry background working on synthesis of nitrification inhibitors but requested to learn more about modelling via a CSIRO top-up scholarship. She is a  novice model user who has no modelling background and her digital skills are limited too. Hence, the existing code in APSIM 7.10, even if listed as “Non-validated” is perfect for her, as she can play with the parameterisation (for DMPP) and evaluate outcomes, without requiring to code, and still has a few of your publications to refer to as background.

**Comment by BrianCollinss** [comment]
Dean, is there a "nitrification inhibitor" functionality in NextGen?

**Comment by hol353** [comment]
Not that I know of.
