### ISSUE TITLE
Releases are not being created

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/APSIMClassic#2230]

**Comment by jbrider** [comment]
@hol353 Have you tried to go to the builds page - I'm getting an error.
https://apsimdev.apsim.info/APSIM.Builds.Portal/Bob.aspx
Server Error in '/' Application.

**Comment by hol353** [comment]
Hmm this page isn't going to work anymore - it is on the old server. Do we still need it given we can download the releases from registrations.apsim.info? To get the diffs file when things go wrong on Jenkins, I can give you an ftp account login where you can download them yourself.

**Comment by jbrider** [comment]
Will the ftp login be public information? 
It was definitely required to be able to get the list of changed files at times.

Or is the idea to only give it on request?

**Comment by hol353** [comment]
Only give it on request when needed.
