### ISSUE TITLE
SoilN OC kg ha-1 <-> OC%

### ISSUE THREAD

**Issue by mnowatzke** [APSIMInitiative/APSIMClassic#2235]
I'm trying to convert back and forth between OC kg ha-1 lyr-1 to OC % lyr-1. In the SoilN documentation I just see this note.

nb. need to convert oc (%) to oc (kg/ha) by multiplying by layer depth and then doing a unit conversion.

What other APSIM outputs and/or inputs are needed to do this unit conversion?

Thanks

**Comment by peter-devoil** [comment]
Within the model, it keeps several pools of C in kg/ha. The calculation of OC (%) is [here](https://github.com/APSIMInitiative/APSIM710/blob/1a5379b97030d0c217ca3cb7cf6f65ade17ff107/Model/SoilN/SoilN.f90#L5175), the conversion of kg/ha to ppm is [here](https://github.com/APSIMInitiative/APSIM710/blob/1a5379b97030d0c217ca3cb7cf6f65ade17ff107/Model/SoilN/SoilN.f90#L2850) - you'll need bulk density..

**Comment by mnowatzke** [comment]
Thank you!
