### ISSUE TITLE
Error while creating .met file

### ISSUE THREAD

**Issue by 98Hashan** [APSIMInitiative/APSIMClassic#2247]
While creating .met file from excel file I tried to add TAV and AMP by using tool that provided in Apsim website. Then this error came. What should I do?
![20240827_110759](https://github.com/user-attachments/assets/aab1bdc6-83dd-4f12-adb5-d05611f4c58e)

**Comment by peter-devoil** [comment]
It looks legit, but does it have tab characters in it?
