### ISSUE TITLE
how much paddoks can i runt at once in apsim

### ISSUE THREAD

**Issue by 98Hashan** [APSIMInitiative/APSIMClassic#2253]
how much paddoks can i runt at once in apsim? If I run 28 paddocks, will it affect the accuracy ? Version is 7.10
![Uploading 20241021_231634.jpg…]()

**Comment by peter-devoil** [comment]
Not the accuracy, but runtime. It's not how many paddocks, but how many components in total: the message passing routines are fairly basic in Classic - NextGen can be much faster.
